// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax_1_16_6_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax_1_16_6_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax_1_16_6_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state1 = "1";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state2 = "10";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state3 = "100";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state4 = "1000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state5 = "10000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state6 = "100000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state8 = "10000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state9 = "100000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state10 = "1000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state11 = "10000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state12 = "100000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state61 = "1000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state62 = "10000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state63 = "100000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state64 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state65 = "10000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state66 = "100000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state67 = "1000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state68 = "10000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state69 = "100000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state70 = "1000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state71 = "10000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state72 = "100000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state73 = "1000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state74 = "10000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state75 = "100000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state76 = "1000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state77 = "10000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state78 = "100000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state79 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state80 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state81 = "100000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state82 = "1000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<83> softmax_1_16_6_s::ap_ST_fsm_state83 = "10000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_1 = "1";
const sc_lv<1> softmax_1_16_6_s::ap_const_lv1_0 = "0";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_2 = "10";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_3 = "11";
const sc_lv<1> softmax_1_16_6_s::ap_const_lv1_1 = "1";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_4 = "100";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_5 = "101";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_6 = "110";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_14 = "10100";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_15 = "10101";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_16 = "10110";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_17 = "10111";
const sc_lv<5> softmax_1_16_6_s::ap_const_lv5_0 = "00000";
const sc_lv<3> softmax_1_16_6_s::ap_const_lv3_1 = "1";
const sc_lv<40> softmax_1_16_6_s::ap_const_lv40_0 = "0000000000000000000000000000000000000000";
const sc_lv<3> softmax_1_16_6_s::ap_const_lv3_0 = "000";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_52 = "1010010";
const sc_lv<32> softmax_1_16_6_s::ap_const_lv32_7 = "111";
const sc_lv<5> softmax_1_16_6_s::ap_const_lv5_10 = "10000";
const sc_lv<5> softmax_1_16_6_s::ap_const_lv5_1 = "1";
const sc_lv<3> softmax_1_16_6_s::ap_const_lv3_6 = "110";
const sc_lv<16> softmax_1_16_6_s::ap_const_lv16_0 = "0000000000000000";
const bool softmax_1_16_6_s::ap_const_boolean_1 = true;

softmax_1_16_6_s::softmax_1_16_6_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_exp_41_25_s_fu_163 = new exp_41_25_s("grp_exp_41_25_s_fu_163");
    grp_exp_41_25_s_fu_163->ap_clk(ap_clk);
    grp_exp_41_25_s_fu_163->ap_rst(ap_rst);
    grp_exp_41_25_s_fu_163->ap_start(grp_exp_41_25_s_fu_163_ap_start);
    grp_exp_41_25_s_fu_163->ap_done(grp_exp_41_25_s_fu_163_ap_done);
    grp_exp_41_25_s_fu_163->ap_idle(grp_exp_41_25_s_fu_163_ap_idle);
    grp_exp_41_25_s_fu_163->ap_ready(grp_exp_41_25_s_fu_163_ap_ready);
    grp_exp_41_25_s_fu_163->x_V(sub_ln1193_reg_419);
    grp_exp_41_25_s_fu_163->ap_return(grp_exp_41_25_s_fu_163_ap_return);
    dut_sdiv_56ns_40sqcK_U52 = new dut_sdiv_56ns_40sqcK<1,60,56,40,40>("dut_sdiv_56ns_40sqcK_U52");
    dut_sdiv_56ns_40sqcK_U52->clk(ap_clk);
    dut_sdiv_56ns_40sqcK_U52->reset(ap_rst);
    dut_sdiv_56ns_40sqcK_U52->start(grp_fu_343_ap_start);
    dut_sdiv_56ns_40sqcK_U52->done(grp_fu_343_ap_done);
    dut_sdiv_56ns_40sqcK_U52->din0(grp_fu_343_p0);
    dut_sdiv_56ns_40sqcK_U52->din1(grp_fu_343_p1);
    dut_sdiv_56ns_40sqcK_U52->ce(ap_var_for_const0);
    dut_sdiv_56ns_40sqcK_U52->dout(grp_fu_343_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln1265_1_fu_325_p2);
    sensitive << ( sub_ln203_reg_361 );
    sensitive << ( zext_ln1265_1_fu_321_p1 );

    SC_METHOD(thread_add_ln1265_fu_277_p2);
    sensitive << ( sub_ln203_reg_361 );
    sensitive << ( zext_ln1265_fu_273_p1 );

    SC_METHOD(thread_add_ln323_fu_237_p2);
    sensitive << ( k_0_0_reg_118 );

    SC_METHOD(thread_add_ln324_fu_227_p2);
    sensitive << ( sub_ln203_reg_361 );
    sensitive << ( zext_ln324_fu_223_p1 );

    SC_METHOD(thread_add_ln326_fu_267_p2);
    sensitive << ( k1_0_0_reg_141 );

    SC_METHOD(thread_add_ln330_fu_315_p2);
    sensitive << ( k2_0_0_reg_152 );

    SC_METHOD(thread_add_ln703_fu_304_p2);
    sensitive << ( trunc_ln703_reg_424 );
    sensitive << ( p_Val2_35_0_reg_129 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_NS_fsm_state8);
    sensitive << ( ap_NS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln320_fu_174_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln320_fu_174_p2 );

    SC_METHOD(thread_grp_exp_41_25_s_fu_163_ap_start);
    sensitive << ( grp_exp_41_25_s_fu_163_ap_start_reg );

    SC_METHOD(thread_grp_fu_343_ap_start);
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_343_p0);
    sensitive << ( input_0_V_q0 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_343_p1);
    sensitive << ( sext_ln1148_reg_414 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_i_fu_180_p2);
    sensitive << ( i_0_reg_97 );

    SC_METHOD(thread_icmp_ln1494_fu_247_p2);
    sensitive << ( input_0_V_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_010_0_reg_108 );

    SC_METHOD(thread_icmp_ln320_fu_174_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_97 );

    SC_METHOD(thread_icmp_ln323_fu_217_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( k_0_0_reg_118 );

    SC_METHOD(thread_icmp_ln326_fu_261_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( k1_0_0_reg_141 );

    SC_METHOD(thread_icmp_ln330_fu_309_p2);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( k2_0_0_reg_152 );

    SC_METHOD(thread_input_0_V_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( input_0_V_addr_2_reg_409 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( input_0_V_addr_3_reg_443 );
    sensitive << ( ap_CS_fsm_state83 );
    sensitive << ( sext_ln203_fu_212_p1 );
    sensitive << ( sext_ln324_fu_232_p1 );
    sensitive << ( sext_ln1265_fu_282_p1 );
    sensitive << ( sext_ln1265_1_fu_330_p1 );

    SC_METHOD(thread_input_0_V_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state83 );

    SC_METHOD(thread_input_0_V_d0);
    sensitive << ( trunc_ln703_reg_424 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state83 );
    sensitive << ( trunc_ln703_1_fu_348_p1 );

    SC_METHOD(thread_input_0_V_we0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state83 );

    SC_METHOD(thread_select_ln102_fu_253_p3);
    sensitive << ( input_0_V_q0 );
    sensitive << ( p_010_0_reg_108 );
    sensitive << ( icmp_ln1494_fu_247_p2 );

    SC_METHOD(thread_sext_ln1148_fu_287_p1);
    sensitive << ( p_Val2_35_0_reg_129 );

    SC_METHOD(thread_sext_ln1265_1_fu_330_p1);
    sensitive << ( add_ln1265_1_fu_325_p2 );

    SC_METHOD(thread_sext_ln1265_fu_282_p1);
    sensitive << ( add_ln1265_fu_277_p2 );

    SC_METHOD(thread_sext_ln203_fu_212_p1);
    sensitive << ( sub_ln203_fu_206_p2 );

    SC_METHOD(thread_sext_ln324_fu_232_p1);
    sensitive << ( add_ln324_fu_227_p2 );

    SC_METHOD(thread_sext_ln703_1_fu_291_p0);
    sensitive << ( input_0_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_sext_ln703_1_fu_291_p1);
    sensitive << ( sext_ln703_1_fu_291_p0 );

    SC_METHOD(thread_sext_ln703_fu_243_p1);
    sensitive << ( p_010_0_reg_108 );

    SC_METHOD(thread_sub_ln1193_fu_295_p2);
    sensitive << ( sext_ln703_reg_391 );
    sensitive << ( sext_ln703_1_fu_291_p1 );

    SC_METHOD(thread_sub_ln203_fu_206_p2);
    sensitive << ( tmp_s_fu_186_p3 );
    sensitive << ( zext_ln203_fu_202_p1 );

    SC_METHOD(thread_tmp_53_fu_194_p3);
    sensitive << ( i_0_reg_97 );

    SC_METHOD(thread_tmp_s_fu_186_p3);
    sensitive << ( i_0_reg_97 );

    SC_METHOD(thread_trunc_ln703_1_fu_348_p1);
    sensitive << ( grp_fu_343_p2 );

    SC_METHOD(thread_trunc_ln703_fu_300_p1);
    sensitive << ( grp_exp_41_25_s_fu_163_ap_return );

    SC_METHOD(thread_zext_ln1265_1_fu_321_p1);
    sensitive << ( k2_0_0_reg_152 );

    SC_METHOD(thread_zext_ln1265_fu_273_p1);
    sensitive << ( k1_0_0_reg_141 );

    SC_METHOD(thread_zext_ln203_fu_202_p1);
    sensitive << ( tmp_53_fu_194_p3 );

    SC_METHOD(thread_zext_ln324_fu_223_p1);
    sensitive << ( k_0_0_reg_118 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln320_fu_174_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln323_fu_217_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln326_fu_261_p2 );
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( icmp_ln330_fu_309_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000000000000000000000000000000000000000000000000000000000000000000000000000000001";
    grp_exp_41_25_s_fu_163_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_1_16_6_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_0_V_address0, "(port)input_0_V_address0");
    sc_trace(mVcdFile, input_0_V_ce0, "(port)input_0_V_ce0");
    sc_trace(mVcdFile, input_0_V_we0, "(port)input_0_V_we0");
    sc_trace(mVcdFile, input_0_V_d0, "(port)input_0_V_d0");
    sc_trace(mVcdFile, input_0_V_q0, "(port)input_0_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_180_p2, "i_fu_180_p2");
    sc_trace(mVcdFile, i_reg_356, "i_reg_356");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln203_fu_206_p2, "sub_ln203_fu_206_p2");
    sc_trace(mVcdFile, sub_ln203_reg_361, "sub_ln203_reg_361");
    sc_trace(mVcdFile, icmp_ln320_fu_174_p2, "icmp_ln320_fu_174_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln323_fu_217_p2, "icmp_ln323_fu_217_p2");
    sc_trace(mVcdFile, add_ln323_fu_237_p2, "add_ln323_fu_237_p2");
    sc_trace(mVcdFile, add_ln323_reg_386, "add_ln323_reg_386");
    sc_trace(mVcdFile, sext_ln703_fu_243_p1, "sext_ln703_fu_243_p1");
    sc_trace(mVcdFile, sext_ln703_reg_391, "sext_ln703_reg_391");
    sc_trace(mVcdFile, select_ln102_fu_253_p3, "select_ln102_fu_253_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, add_ln326_fu_267_p2, "add_ln326_fu_267_p2");
    sc_trace(mVcdFile, add_ln326_reg_404, "add_ln326_reg_404");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, input_0_V_addr_2_reg_409, "input_0_V_addr_2_reg_409");
    sc_trace(mVcdFile, icmp_ln326_fu_261_p2, "icmp_ln326_fu_261_p2");
    sc_trace(mVcdFile, sext_ln1148_fu_287_p1, "sext_ln1148_fu_287_p1");
    sc_trace(mVcdFile, sext_ln1148_reg_414, "sext_ln1148_reg_414");
    sc_trace(mVcdFile, sub_ln1193_fu_295_p2, "sub_ln1193_fu_295_p2");
    sc_trace(mVcdFile, sub_ln1193_reg_419, "sub_ln1193_reg_419");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, trunc_ln703_fu_300_p1, "trunc_ln703_fu_300_p1");
    sc_trace(mVcdFile, trunc_ln703_reg_424, "trunc_ln703_reg_424");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, add_ln703_fu_304_p2, "add_ln703_fu_304_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, add_ln330_fu_315_p2, "add_ln330_fu_315_p2");
    sc_trace(mVcdFile, add_ln330_reg_438, "add_ln330_reg_438");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, input_0_V_addr_3_reg_443, "input_0_V_addr_3_reg_443");
    sc_trace(mVcdFile, icmp_ln330_fu_309_p2, "icmp_ln330_fu_309_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_exp_41_25_s_fu_163_ap_start, "grp_exp_41_25_s_fu_163_ap_start");
    sc_trace(mVcdFile, grp_exp_41_25_s_fu_163_ap_done, "grp_exp_41_25_s_fu_163_ap_done");
    sc_trace(mVcdFile, grp_exp_41_25_s_fu_163_ap_idle, "grp_exp_41_25_s_fu_163_ap_idle");
    sc_trace(mVcdFile, grp_exp_41_25_s_fu_163_ap_ready, "grp_exp_41_25_s_fu_163_ap_ready");
    sc_trace(mVcdFile, grp_exp_41_25_s_fu_163_ap_return, "grp_exp_41_25_s_fu_163_ap_return");
    sc_trace(mVcdFile, i_0_reg_97, "i_0_reg_97");
    sc_trace(mVcdFile, p_010_0_reg_108, "p_010_0_reg_108");
    sc_trace(mVcdFile, k_0_0_reg_118, "k_0_0_reg_118");
    sc_trace(mVcdFile, p_Val2_35_0_reg_129, "p_Val2_35_0_reg_129");
    sc_trace(mVcdFile, k1_0_0_reg_141, "k1_0_0_reg_141");
    sc_trace(mVcdFile, k2_0_0_reg_152, "k2_0_0_reg_152");
    sc_trace(mVcdFile, ap_CS_fsm_state83, "ap_CS_fsm_state83");
    sc_trace(mVcdFile, grp_exp_41_25_s_fu_163_ap_start_reg, "grp_exp_41_25_s_fu_163_ap_start_reg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_NS_fsm_state8, "ap_NS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, sext_ln203_fu_212_p1, "sext_ln203_fu_212_p1");
    sc_trace(mVcdFile, sext_ln324_fu_232_p1, "sext_ln324_fu_232_p1");
    sc_trace(mVcdFile, sext_ln1265_fu_282_p1, "sext_ln1265_fu_282_p1");
    sc_trace(mVcdFile, sext_ln1265_1_fu_330_p1, "sext_ln1265_1_fu_330_p1");
    sc_trace(mVcdFile, trunc_ln703_1_fu_348_p1, "trunc_ln703_1_fu_348_p1");
    sc_trace(mVcdFile, tmp_53_fu_194_p3, "tmp_53_fu_194_p3");
    sc_trace(mVcdFile, tmp_s_fu_186_p3, "tmp_s_fu_186_p3");
    sc_trace(mVcdFile, zext_ln203_fu_202_p1, "zext_ln203_fu_202_p1");
    sc_trace(mVcdFile, zext_ln324_fu_223_p1, "zext_ln324_fu_223_p1");
    sc_trace(mVcdFile, add_ln324_fu_227_p2, "add_ln324_fu_227_p2");
    sc_trace(mVcdFile, icmp_ln1494_fu_247_p2, "icmp_ln1494_fu_247_p2");
    sc_trace(mVcdFile, zext_ln1265_fu_273_p1, "zext_ln1265_fu_273_p1");
    sc_trace(mVcdFile, add_ln1265_fu_277_p2, "add_ln1265_fu_277_p2");
    sc_trace(mVcdFile, sext_ln703_1_fu_291_p0, "sext_ln703_1_fu_291_p0");
    sc_trace(mVcdFile, sext_ln703_1_fu_291_p1, "sext_ln703_1_fu_291_p1");
    sc_trace(mVcdFile, zext_ln1265_1_fu_321_p1, "zext_ln1265_1_fu_321_p1");
    sc_trace(mVcdFile, add_ln1265_1_fu_325_p2, "add_ln1265_1_fu_325_p2");
    sc_trace(mVcdFile, grp_fu_343_p0, "grp_fu_343_p0");
    sc_trace(mVcdFile, grp_fu_343_p1, "grp_fu_343_p1");
    sc_trace(mVcdFile, grp_fu_343_p2, "grp_fu_343_p2");
    sc_trace(mVcdFile, grp_fu_343_ap_start, "grp_fu_343_ap_start");
    sc_trace(mVcdFile, grp_fu_343_ap_done, "grp_fu_343_ap_done");
#endif

    }
}

softmax_1_16_6_s::~softmax_1_16_6_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_exp_41_25_s_fu_163;
    delete dut_sdiv_56ns_40sqcK_U52;
}

void softmax_1_16_6_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void softmax_1_16_6_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_exp_41_25_s_fu_163_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_NS_fsm_state8.read()))) {
            grp_exp_41_25_s_fu_163_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_exp_41_25_s_fu_163_ap_ready.read())) {
            grp_exp_41_25_s_fu_163_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln330_fu_309_p2.read()))) {
        i_0_reg_97 = i_reg_356.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_97 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        k1_0_0_reg_141 = add_ln326_reg_404.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln323_fu_217_p2.read(), ap_const_lv1_1))) {
        k1_0_0_reg_141 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln326_fu_261_p2.read()))) {
        k2_0_0_reg_152 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state83.read())) {
        k2_0_0_reg_152 = add_ln330_reg_438.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        k_0_0_reg_118 = add_ln323_reg_386.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        k_0_0_reg_118 = ap_const_lv3_1;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        p_010_0_reg_108 = select_ln102_fu_253_p3.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_010_0_reg_108 = input_0_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        p_Val2_35_0_reg_129 = add_ln703_fu_304_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(icmp_ln323_fu_217_p2.read(), ap_const_lv1_1))) {
        p_Val2_35_0_reg_129 = ap_const_lv40_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln323_fu_217_p2.read()))) {
        add_ln323_reg_386 = add_ln323_fu_237_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln326_reg_404 = add_ln326_fu_267_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        add_ln330_reg_438 = add_ln330_fu_315_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_356 = i_fu_180_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln326_fu_261_p2.read()))) {
        input_0_V_addr_2_reg_409 =  (sc_lv<7>) (sext_ln1265_fu_282_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln330_fu_309_p2.read()))) {
        input_0_V_addr_3_reg_443 =  (sc_lv<7>) (sext_ln1265_1_fu_330_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln326_fu_261_p2.read()))) {
        sext_ln1148_reg_414 = sext_ln1148_fu_287_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln323_fu_217_p2.read(), ap_const_lv1_1))) {
        sext_ln703_reg_391 = sext_ln703_fu_243_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sub_ln1193_reg_419 = sub_ln1193_fu_295_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln320_fu_174_p2.read(), ap_const_lv1_0))) {
        sub_ln203_reg_361 = sub_ln203_fu_206_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        trunc_ln703_reg_424 = trunc_ln703_fu_300_p1.read();
    }
}

void softmax_1_16_6_s::thread_add_ln1265_1_fu_325_p2() {
    add_ln1265_1_fu_325_p2 = (!sub_ln203_reg_361.read().is_01() || !zext_ln1265_1_fu_321_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sub_ln203_reg_361.read()) + sc_biguint<8>(zext_ln1265_1_fu_321_p1.read()));
}

void softmax_1_16_6_s::thread_add_ln1265_fu_277_p2() {
    add_ln1265_fu_277_p2 = (!sub_ln203_reg_361.read().is_01() || !zext_ln1265_fu_273_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sub_ln203_reg_361.read()) + sc_biguint<8>(zext_ln1265_fu_273_p1.read()));
}

void softmax_1_16_6_s::thread_add_ln323_fu_237_p2() {
    add_ln323_fu_237_p2 = (!k_0_0_reg_118.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k_0_0_reg_118.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax_1_16_6_s::thread_add_ln324_fu_227_p2() {
    add_ln324_fu_227_p2 = (!sub_ln203_reg_361.read().is_01() || !zext_ln324_fu_223_p1.read().is_01())? sc_lv<8>(): (sc_bigint<8>(sub_ln203_reg_361.read()) + sc_biguint<8>(zext_ln324_fu_223_p1.read()));
}

void softmax_1_16_6_s::thread_add_ln326_fu_267_p2() {
    add_ln326_fu_267_p2 = (!k1_0_0_reg_141.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k1_0_0_reg_141.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax_1_16_6_s::thread_add_ln330_fu_315_p2() {
    add_ln330_fu_315_p2 = (!k2_0_0_reg_152.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k2_0_0_reg_152.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax_1_16_6_s::thread_add_ln703_fu_304_p2() {
    add_ln703_fu_304_p2 = (!p_Val2_35_0_reg_129.read().is_01() || !trunc_ln703_reg_424.read().is_01())? sc_lv<40>(): (sc_bigint<40>(p_Val2_35_0_reg_129.read()) + sc_biguint<40>(trunc_ln703_reg_424.read()));
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void softmax_1_16_6_s::thread_ap_CS_fsm_state83() {
    ap_CS_fsm_state83 = ap_CS_fsm.read()[82];
}

void softmax_1_16_6_s::thread_ap_NS_fsm_state8() {
    ap_NS_fsm_state8 = ap_NS_fsm.read()[7];
}

void softmax_1_16_6_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln320_fu_174_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax_1_16_6_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax_1_16_6_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln320_fu_174_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax_1_16_6_s::thread_grp_exp_41_25_s_fu_163_ap_start() {
    grp_exp_41_25_s_fu_163_ap_start = grp_exp_41_25_s_fu_163_ap_start_reg.read();
}

void softmax_1_16_6_s::thread_grp_fu_343_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        grp_fu_343_ap_start = ap_const_logic_1;
    } else {
        grp_fu_343_ap_start = ap_const_logic_0;
    }
}

void softmax_1_16_6_s::thread_grp_fu_343_p0() {
    grp_fu_343_p0 = esl_concat<40,16>(input_0_V_q0.read(), ap_const_lv16_0);
}

void softmax_1_16_6_s::thread_grp_fu_343_p1() {
    grp_fu_343_p1 =  (sc_lv<40>) (sext_ln1148_reg_414.read());
}

void softmax_1_16_6_s::thread_i_fu_180_p2() {
    i_fu_180_p2 = (!i_0_reg_97.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_97.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void softmax_1_16_6_s::thread_icmp_ln1494_fu_247_p2() {
    icmp_ln1494_fu_247_p2 = (!p_010_0_reg_108.read().is_01() || !input_0_V_q0.read().is_01())? sc_lv<1>(): (sc_bigint<40>(p_010_0_reg_108.read()) > sc_bigint<40>(input_0_V_q0.read()));
}

void softmax_1_16_6_s::thread_icmp_ln320_fu_174_p2() {
    icmp_ln320_fu_174_p2 = (!i_0_reg_97.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_97.read() == ap_const_lv5_10);
}

void softmax_1_16_6_s::thread_icmp_ln323_fu_217_p2() {
    icmp_ln323_fu_217_p2 = (!k_0_0_reg_118.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k_0_0_reg_118.read() == ap_const_lv3_6);
}

void softmax_1_16_6_s::thread_icmp_ln326_fu_261_p2() {
    icmp_ln326_fu_261_p2 = (!k1_0_0_reg_141.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k1_0_0_reg_141.read() == ap_const_lv3_6);
}

void softmax_1_16_6_s::thread_icmp_ln330_fu_309_p2() {
    icmp_ln330_fu_309_p2 = (!k2_0_0_reg_152.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k2_0_0_reg_152.read() == ap_const_lv3_6);
}

void softmax_1_16_6_s::thread_input_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state83.read())) {
        input_0_V_address0 = input_0_V_addr_3_reg_443.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        input_0_V_address0 =  (sc_lv<7>) (sext_ln1265_1_fu_330_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        input_0_V_address0 = input_0_V_addr_2_reg_409.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        input_0_V_address0 =  (sc_lv<7>) (sext_ln1265_fu_282_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        input_0_V_address0 =  (sc_lv<7>) (sext_ln324_fu_232_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        input_0_V_address0 =  (sc_lv<7>) (sext_ln203_fu_212_p1.read());
    } else {
        input_0_V_address0 = "XXXXXXX";
    }
}

void softmax_1_16_6_s::thread_input_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state83.read()))) {
        input_0_V_ce0 = ap_const_logic_1;
    } else {
        input_0_V_ce0 = ap_const_logic_0;
    }
}

void softmax_1_16_6_s::thread_input_0_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state83.read())) {
        input_0_V_d0 = trunc_ln703_1_fu_348_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        input_0_V_d0 = trunc_ln703_reg_424.read();
    } else {
        input_0_V_d0 =  (sc_lv<40>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void softmax_1_16_6_s::thread_input_0_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state83.read()))) {
        input_0_V_we0 = ap_const_logic_1;
    } else {
        input_0_V_we0 = ap_const_logic_0;
    }
}

void softmax_1_16_6_s::thread_select_ln102_fu_253_p3() {
    select_ln102_fu_253_p3 = (!icmp_ln1494_fu_247_p2.read()[0].is_01())? sc_lv<40>(): ((icmp_ln1494_fu_247_p2.read()[0].to_bool())? p_010_0_reg_108.read(): input_0_V_q0.read());
}

void softmax_1_16_6_s::thread_sext_ln1148_fu_287_p1() {
    sext_ln1148_fu_287_p1 = esl_sext<56,40>(p_Val2_35_0_reg_129.read());
}

void softmax_1_16_6_s::thread_sext_ln1265_1_fu_330_p1() {
    sext_ln1265_1_fu_330_p1 = esl_sext<64,8>(add_ln1265_1_fu_325_p2.read());
}

void softmax_1_16_6_s::thread_sext_ln1265_fu_282_p1() {
    sext_ln1265_fu_282_p1 = esl_sext<64,8>(add_ln1265_fu_277_p2.read());
}

void softmax_1_16_6_s::thread_sext_ln203_fu_212_p1() {
    sext_ln203_fu_212_p1 = esl_sext<64,8>(sub_ln203_fu_206_p2.read());
}

void softmax_1_16_6_s::thread_sext_ln324_fu_232_p1() {
    sext_ln324_fu_232_p1 = esl_sext<64,8>(add_ln324_fu_227_p2.read());
}

void softmax_1_16_6_s::thread_sext_ln703_1_fu_291_p0() {
    sext_ln703_1_fu_291_p0 = input_0_V_q0.read();
}

void softmax_1_16_6_s::thread_sext_ln703_1_fu_291_p1() {
    sext_ln703_1_fu_291_p1 = esl_sext<41,40>(sext_ln703_1_fu_291_p0.read());
}

void softmax_1_16_6_s::thread_sext_ln703_fu_243_p1() {
    sext_ln703_fu_243_p1 = esl_sext<41,40>(p_010_0_reg_108.read());
}

void softmax_1_16_6_s::thread_sub_ln1193_fu_295_p2() {
    sub_ln1193_fu_295_p2 = (!sext_ln703_1_fu_291_p1.read().is_01() || !sext_ln703_reg_391.read().is_01())? sc_lv<41>(): (sc_bigint<41>(sext_ln703_1_fu_291_p1.read()) - sc_bigint<41>(sext_ln703_reg_391.read()));
}

void softmax_1_16_6_s::thread_sub_ln203_fu_206_p2() {
    sub_ln203_fu_206_p2 = (!tmp_s_fu_186_p3.read().is_01() || !zext_ln203_fu_202_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_s_fu_186_p3.read()) - sc_biguint<8>(zext_ln203_fu_202_p1.read()));
}

void softmax_1_16_6_s::thread_tmp_53_fu_194_p3() {
    tmp_53_fu_194_p3 = esl_concat<5,1>(i_0_reg_97.read(), ap_const_lv1_0);
}

void softmax_1_16_6_s::thread_tmp_s_fu_186_p3() {
    tmp_s_fu_186_p3 = esl_concat<5,3>(i_0_reg_97.read(), ap_const_lv3_0);
}

void softmax_1_16_6_s::thread_trunc_ln703_1_fu_348_p1() {
    trunc_ln703_1_fu_348_p1 = grp_fu_343_p2.read().range(40-1, 0);
}

void softmax_1_16_6_s::thread_trunc_ln703_fu_300_p1() {
    trunc_ln703_fu_300_p1 = grp_exp_41_25_s_fu_163_ap_return.read().range(40-1, 0);
}

void softmax_1_16_6_s::thread_zext_ln1265_1_fu_321_p1() {
    zext_ln1265_1_fu_321_p1 = esl_zext<8,3>(k2_0_0_reg_152.read());
}

void softmax_1_16_6_s::thread_zext_ln1265_fu_273_p1() {
    zext_ln1265_fu_273_p1 = esl_zext<8,3>(k1_0_0_reg_141.read());
}

void softmax_1_16_6_s::thread_zext_ln203_fu_202_p1() {
    zext_ln203_fu_202_p1 = esl_zext<8,6>(tmp_53_fu_194_p3.read());
}

void softmax_1_16_6_s::thread_zext_ln324_fu_223_p1() {
    zext_ln324_fu_223_p1 = esl_zext<8,3>(k_0_0_reg_118.read());
}

void softmax_1_16_6_s::thread_ap_NS_fsm() {
    if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state1))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state1;
        }
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state2))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln320_fu_174_p2.read(), ap_const_lv1_1))) {
            ap_NS_fsm = ap_ST_fsm_state1;
        } else {
            ap_NS_fsm = ap_ST_fsm_state3;
        }
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state3))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state4))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(icmp_ln323_fu_217_p2.read(), ap_const_lv1_1))) {
            ap_NS_fsm = ap_ST_fsm_state6;
        } else {
            ap_NS_fsm = ap_ST_fsm_state5;
        }
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state5))
    {
        ap_NS_fsm = ap_ST_fsm_state4;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state6))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln326_fu_261_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state23;
        } else {
            ap_NS_fsm = ap_ST_fsm_state7;
        }
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state7))
    {
        ap_NS_fsm = ap_ST_fsm_state8;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state8))
    {
        ap_NS_fsm = ap_ST_fsm_state9;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state9))
    {
        ap_NS_fsm = ap_ST_fsm_state10;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state10))
    {
        ap_NS_fsm = ap_ST_fsm_state11;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state11))
    {
        ap_NS_fsm = ap_ST_fsm_state12;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state12))
    {
        ap_NS_fsm = ap_ST_fsm_state13;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state13))
    {
        ap_NS_fsm = ap_ST_fsm_state14;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state14))
    {
        ap_NS_fsm = ap_ST_fsm_state15;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state15))
    {
        ap_NS_fsm = ap_ST_fsm_state16;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state16))
    {
        ap_NS_fsm = ap_ST_fsm_state17;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state17))
    {
        ap_NS_fsm = ap_ST_fsm_state18;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state18))
    {
        ap_NS_fsm = ap_ST_fsm_state19;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state19))
    {
        ap_NS_fsm = ap_ST_fsm_state20;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state20))
    {
        ap_NS_fsm = ap_ST_fsm_state21;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state21))
    {
        ap_NS_fsm = ap_ST_fsm_state22;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state22))
    {
        ap_NS_fsm = ap_ST_fsm_state6;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state23))
    {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln330_fu_309_p2.read()))) {
            ap_NS_fsm = ap_ST_fsm_state2;
        } else {
            ap_NS_fsm = ap_ST_fsm_state24;
        }
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state24))
    {
        ap_NS_fsm = ap_ST_fsm_state25;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state25))
    {
        ap_NS_fsm = ap_ST_fsm_state26;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state26))
    {
        ap_NS_fsm = ap_ST_fsm_state27;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state27))
    {
        ap_NS_fsm = ap_ST_fsm_state28;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state28))
    {
        ap_NS_fsm = ap_ST_fsm_state29;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state29))
    {
        ap_NS_fsm = ap_ST_fsm_state30;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state30))
    {
        ap_NS_fsm = ap_ST_fsm_state31;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state31))
    {
        ap_NS_fsm = ap_ST_fsm_state32;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state32))
    {
        ap_NS_fsm = ap_ST_fsm_state33;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state33))
    {
        ap_NS_fsm = ap_ST_fsm_state34;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state34))
    {
        ap_NS_fsm = ap_ST_fsm_state35;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state35))
    {
        ap_NS_fsm = ap_ST_fsm_state36;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state36))
    {
        ap_NS_fsm = ap_ST_fsm_state37;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state37))
    {
        ap_NS_fsm = ap_ST_fsm_state38;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state38))
    {
        ap_NS_fsm = ap_ST_fsm_state39;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state39))
    {
        ap_NS_fsm = ap_ST_fsm_state40;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state40))
    {
        ap_NS_fsm = ap_ST_fsm_state41;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state41))
    {
        ap_NS_fsm = ap_ST_fsm_state42;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state42))
    {
        ap_NS_fsm = ap_ST_fsm_state43;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state43))
    {
        ap_NS_fsm = ap_ST_fsm_state44;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state44))
    {
        ap_NS_fsm = ap_ST_fsm_state45;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state45))
    {
        ap_NS_fsm = ap_ST_fsm_state46;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state46))
    {
        ap_NS_fsm = ap_ST_fsm_state47;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state47))
    {
        ap_NS_fsm = ap_ST_fsm_state48;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state48))
    {
        ap_NS_fsm = ap_ST_fsm_state49;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state49))
    {
        ap_NS_fsm = ap_ST_fsm_state50;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state50))
    {
        ap_NS_fsm = ap_ST_fsm_state51;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state51))
    {
        ap_NS_fsm = ap_ST_fsm_state52;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state52))
    {
        ap_NS_fsm = ap_ST_fsm_state53;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state53))
    {
        ap_NS_fsm = ap_ST_fsm_state54;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state54))
    {
        ap_NS_fsm = ap_ST_fsm_state55;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state55))
    {
        ap_NS_fsm = ap_ST_fsm_state56;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state56))
    {
        ap_NS_fsm = ap_ST_fsm_state57;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state57))
    {
        ap_NS_fsm = ap_ST_fsm_state58;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state58))
    {
        ap_NS_fsm = ap_ST_fsm_state59;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state59))
    {
        ap_NS_fsm = ap_ST_fsm_state60;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state60))
    {
        ap_NS_fsm = ap_ST_fsm_state61;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state61))
    {
        ap_NS_fsm = ap_ST_fsm_state62;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state62))
    {
        ap_NS_fsm = ap_ST_fsm_state63;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state63))
    {
        ap_NS_fsm = ap_ST_fsm_state64;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state64))
    {
        ap_NS_fsm = ap_ST_fsm_state65;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state65))
    {
        ap_NS_fsm = ap_ST_fsm_state66;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state66))
    {
        ap_NS_fsm = ap_ST_fsm_state67;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state67))
    {
        ap_NS_fsm = ap_ST_fsm_state68;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state68))
    {
        ap_NS_fsm = ap_ST_fsm_state69;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state69))
    {
        ap_NS_fsm = ap_ST_fsm_state70;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state70))
    {
        ap_NS_fsm = ap_ST_fsm_state71;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state71))
    {
        ap_NS_fsm = ap_ST_fsm_state72;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state72))
    {
        ap_NS_fsm = ap_ST_fsm_state73;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state73))
    {
        ap_NS_fsm = ap_ST_fsm_state74;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state74))
    {
        ap_NS_fsm = ap_ST_fsm_state75;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state75))
    {
        ap_NS_fsm = ap_ST_fsm_state76;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state76))
    {
        ap_NS_fsm = ap_ST_fsm_state77;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state77))
    {
        ap_NS_fsm = ap_ST_fsm_state78;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state78))
    {
        ap_NS_fsm = ap_ST_fsm_state79;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state79))
    {
        ap_NS_fsm = ap_ST_fsm_state80;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state80))
    {
        ap_NS_fsm = ap_ST_fsm_state81;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state81))
    {
        ap_NS_fsm = ap_ST_fsm_state82;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state82))
    {
        ap_NS_fsm = ap_ST_fsm_state83;
    }
    else if (esl_seteq<1,83,83>(ap_CS_fsm.read(), ap_ST_fsm_state83))
    {
        ap_NS_fsm = ap_ST_fsm_state23;
    }
    else
    {
        ap_NS_fsm =  (sc_lv<83>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}
}

