directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#16 RESOURCE_NAME SF_LOOP_3:mul#11:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#14 RESOURCE_NAME SF_LOOP_3:mul#11:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#11 RESOURCE_NAME SF_LOOP_3:mul#11:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt:for:guess_inv:mul RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:mul#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5:quant_val:mul#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#1:mul#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:sqr RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:RMS_NORM_LOOP_1#2:mul RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt#1:for:guess_inv:mul RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1:quant_val:mul#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:mul#1 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:mul#1:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#6 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:mul#1:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#20 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:mul#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2:mul#1 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:mul#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:mul#1 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:mul#1:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#68 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#21:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#21 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#21:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#21 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#21:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#23 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#23:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#23 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#23:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt:for:acc#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#84 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc#37 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#17 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#19 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#20 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#80 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#17:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#94 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#17:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:acc#17 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#17:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:acc#29 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_3:acc#7 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#1:acc#11 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:x:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_5:acc#6 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_3:if:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#18 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#24 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#24:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#24 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#24:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#26 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#26:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#26 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#26:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt:for:acc#2 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_4:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_4:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_4:acc#1:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc RESOURCE_NAME attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc RESOURCE_NAME attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:acc RESOURCE_NAME attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#3:acc RESOURCE_NAME attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_round#1:qelse:acc RESOURCE_NAME attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_round:qelse:acc RESOURCE_NAME attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/INIT_2D_MEM_LOOP_2#2:acc RESOURCE_NAME INIT_2D_MEM_LOOP_2#2:acc:rg
directive set /dut/dut:core/dut:core:conc/for:for:acc#2 RESOURCE_NAME INIT_2D_MEM_LOOP_2#2:acc:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:acc#3 RESOURCE_NAME INIT_2D_MEM_LOOP_2:acc:rg
directive set /dut/dut:core/dut:core:conc/INIT_2D_MEM_LOOP_2:acc RESOURCE_NAME INIT_2D_MEM_LOOP_2:acc:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:acc#2 RESOURCE_NAME INIT_2D_MEM_LOOP_2:acc:rg
directive set /dut/dut:core/dut:core:conc/INIT_2D_MEM_LOOP_2#1:acc RESOURCE_NAME INIT_2D_MEM_LOOP_2#1:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_2:acc#5 RESOURCE_NAME INIT_2D_MEM_LOOP_2#1:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#2:mux RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:mux:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#1:mux RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:mux:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5:mux RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:mux:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:mul#1 RESOURCE_NAME RMS_NORM_LOOP_2#2:mul:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:mul RESOURCE_NAME RMS_NORM_LOOP_2#2:mul:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:RMS_NORM_LOOP_1#1:mul RESOURCE_NAME RMS_NORM_LOOP_1#1:RMS_NORM_LOOP_1#1:mul:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:mul RESOURCE_NAME RMS_NORM_LOOP_1#1:RMS_NORM_LOOP_1#1:mul:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:acc#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:acc#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:x:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:acc#3 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:acc#4 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#12 RESOURCE_NAME SF_LOOP_3:mul#12:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#19 RESOURCE_NAME SF_LOOP_3:mul#12:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#4 RESOURCE_NAME SF_LOOP_3:mul:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul RESOURCE_NAME SF_LOOP_3:mul:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#13 RESOURCE_NAME SF_LOOP_3:mul#10:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#10 RESOURCE_NAME SF_LOOP_3:mul#10:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#4 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#4:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#9 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#4:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#8 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#5 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#9 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#9:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#17 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#9:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#9:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#18 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:mul#2 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/for:for:acc#3 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_3:acc#2:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3:acc#2 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_3:acc#2:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#1:acc#12 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_3:acc#2:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_3:acc#2 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_2:acc#7:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_2:acc#7 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_2:acc#7:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3#2:acc#2 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3:acc#12 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#23 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#1:acc#10 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:acc#28 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_3:acc#6 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:x:acc#4 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_5:acc#5 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#14 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:acc#18 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#18:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#21 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#18:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#20 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#18:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#18 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#18:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#20 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#18:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:qif:acc#3 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#15 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3:acc#10 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc#44 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_3:if:acc#5 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_2:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:qif:acc#3 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#12 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:acc#19 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#19:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#24 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#19:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#19 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#19:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#23 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#19:rg
