// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "softmax.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic softmax::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic softmax::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<60> softmax::ap_ST_fsm_state1 = "1";
const sc_lv<60> softmax::ap_ST_fsm_state2 = "10";
const sc_lv<60> softmax::ap_ST_fsm_state3 = "100";
const sc_lv<60> softmax::ap_ST_fsm_state4 = "1000";
const sc_lv<60> softmax::ap_ST_fsm_state5 = "10000";
const sc_lv<60> softmax::ap_ST_fsm_state6 = "100000";
const sc_lv<60> softmax::ap_ST_fsm_state7 = "1000000";
const sc_lv<60> softmax::ap_ST_fsm_state8 = "10000000";
const sc_lv<60> softmax::ap_ST_fsm_state9 = "100000000";
const sc_lv<60> softmax::ap_ST_fsm_state10 = "1000000000";
const sc_lv<60> softmax::ap_ST_fsm_state11 = "10000000000";
const sc_lv<60> softmax::ap_ST_fsm_state12 = "100000000000";
const sc_lv<60> softmax::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state44 = "10000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state45 = "100000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state46 = "1000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state47 = "10000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state48 = "100000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state49 = "1000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state50 = "10000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state51 = "100000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state52 = "1000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state53 = "10000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state54 = "100000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state55 = "1000000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state56 = "10000000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state57 = "100000000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state58 = "1000000000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state59 = "10000000000000000000000000000000000000000000000000000000000";
const sc_lv<60> softmax::ap_ST_fsm_state60 = "100000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> softmax::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> softmax::ap_const_lv32_1 = "1";
const sc_lv<1> softmax::ap_const_lv1_0 = "0";
const sc_lv<32> softmax::ap_const_lv32_2 = "10";
const sc_lv<32> softmax::ap_const_lv32_4 = "100";
const sc_lv<32> softmax::ap_const_lv32_5 = "101";
const sc_lv<32> softmax::ap_const_lv32_6 = "110";
const sc_lv<32> softmax::ap_const_lv32_7 = "111";
const sc_lv<1> softmax::ap_const_lv1_1 = "1";
const sc_lv<32> softmax::ap_const_lv32_8 = "1000";
const sc_lv<32> softmax::ap_const_lv32_A = "1010";
const sc_lv<32> softmax::ap_const_lv32_B = "1011";
const sc_lv<32> softmax::ap_const_lv32_C = "1100";
const sc_lv<5> softmax::ap_const_lv5_0 = "00000";
const sc_lv<3> softmax::ap_const_lv3_0 = "000";
const sc_lv<32> softmax::ap_const_lv32_3 = "11";
const sc_lv<32> softmax::ap_const_lv32_3B = "111011";
const sc_lv<32> softmax::ap_const_lv32_9 = "1001";
const sc_lv<32> softmax::ap_const_lv32_2B7E = "10101101111110";
const sc_lv<5> softmax::ap_const_lv5_10 = "10000";
const sc_lv<5> softmax::ap_const_lv5_1 = "1";
const sc_lv<3> softmax::ap_const_lv3_6 = "110";
const sc_lv<3> softmax::ap_const_lv3_1 = "1";
const sc_lv<12> softmax::ap_const_lv12_0 = "000000000000";
const bool softmax::ap_const_boolean_1 = true;

softmax::softmax(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_pow_32_20_s_fu_223 = new pow_32_20_s("grp_pow_32_20_s_fu_223");
    grp_pow_32_20_s_fu_223->ap_clk(ap_clk);
    grp_pow_32_20_s_fu_223->ap_rst(ap_rst);
    grp_pow_32_20_s_fu_223->ap_start(grp_pow_32_20_s_fu_223_ap_start);
    grp_pow_32_20_s_fu_223->ap_done(grp_pow_32_20_s_fu_223_ap_done);
    grp_pow_32_20_s_fu_223->ap_idle(grp_pow_32_20_s_fu_223_ap_idle);
    grp_pow_32_20_s_fu_223->ap_ready(grp_pow_32_20_s_fu_223_ap_ready);
    grp_pow_32_20_s_fu_223->x_V(ap_var_for_const0);
    grp_pow_32_20_s_fu_223->y_V(sub_ln703_reg_561);
    grp_pow_32_20_s_fu_223->ap_return(grp_pow_32_20_s_fu_223_ap_return);
    attention_sdiv_44Bew_U78 = new attention_sdiv_44Bew<1,48,44,32,32>("attention_sdiv_44Bew_U78");
    attention_sdiv_44Bew_U78->clk(ap_clk);
    attention_sdiv_44Bew_U78->reset(ap_rst);
    attention_sdiv_44Bew_U78->start(grp_fu_469_ap_start);
    attention_sdiv_44Bew_U78->done(grp_fu_469_ap_done);
    attention_sdiv_44Bew_U78->din0(grp_fu_469_p0);
    attention_sdiv_44Bew_U78->din1(grp_fu_469_p1);
    attention_sdiv_44Bew_U78->ce(ap_var_for_const1);
    attention_sdiv_44Bew_U78->dout(grp_fu_469_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln369_fu_295_p2);
    sensitive << ( k4_0_0_reg_144 );

    SC_METHOD(thread_add_ln370_fu_305_p2);
    sensitive << ( sub_ln370_reg_487 );
    sensitive << ( zext_ln370_1_fu_301_p1 );

    SC_METHOD(thread_add_ln379_fu_359_p2);
    sensitive << ( k5_0_0_reg_178 );

    SC_METHOD(thread_add_ln380_fu_369_p2);
    sensitive << ( sub_ln380_reg_518 );
    sensitive << ( zext_ln380_1_fu_365_p1 );

    SC_METHOD(thread_add_ln390_fu_399_p2);
    sensitive << ( k6_0_0_reg_201 );

    SC_METHOD(thread_add_ln391_fu_409_p2);
    sensitive << ( sub_ln380_reg_518 );
    sensitive << ( zext_ln391_fu_405_p1 );

    SC_METHOD(thread_add_ln401_fu_441_p2);
    sensitive << ( k7_0_0_reg_212 );

    SC_METHOD(thread_add_ln402_fu_451_p2);
    sensitive << ( sub_ln380_reg_518 );
    sensitive << ( zext_ln402_fu_447_p1 );

    SC_METHOD(thread_add_ln703_fu_429_p2);
    sensitive << ( grp_pow_32_20_s_fu_223_ap_return );
    sensitive << ( v234_V_0_reg_189 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state60);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln375_fu_315_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln375_fu_315_p2 );

    SC_METHOD(thread_grp_fu_469_ap_start);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_469_p0);
    sensitive << ( v214_0_V_q0 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_469_p1);
    sensitive << ( sext_ln1148_reg_556 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_pow_32_20_s_fu_223_ap_start);
    sensitive << ( grp_pow_32_20_s_fu_223_ap_start_reg );

    SC_METHOD(thread_i7_fu_257_p2);
    sensitive << ( i7_0_reg_133 );

    SC_METHOD(thread_i8_fu_321_p2);
    sensitive << ( i8_0_reg_155 );

    SC_METHOD(thread_icmp_ln1494_fu_379_p2);
    sensitive << ( v214_0_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( v224_V_0_reg_166 );

    SC_METHOD(thread_icmp_ln367_fu_251_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i7_0_reg_133 );

    SC_METHOD(thread_icmp_ln369_fu_289_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( k4_0_0_reg_144 );

    SC_METHOD(thread_icmp_ln375_fu_315_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i8_0_reg_155 );

    SC_METHOD(thread_icmp_ln379_fu_353_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( k5_0_0_reg_178 );

    SC_METHOD(thread_icmp_ln390_fu_393_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( k6_0_0_reg_201 );

    SC_METHOD(thread_icmp_ln401_fu_435_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( k7_0_0_reg_212 );

    SC_METHOD(thread_select_ln383_fu_385_p3);
    sensitive << ( v214_0_V_q0 );
    sensitive << ( v224_V_0_reg_166 );
    sensitive << ( icmp_ln1494_fu_379_p2 );

    SC_METHOD(thread_sext_ln1148_fu_419_p1);
    sensitive << ( v234_V_0_reg_189 );

    SC_METHOD(thread_sext_ln370_fu_310_p1);
    sensitive << ( add_ln370_fu_305_p2 );

    SC_METHOD(thread_sext_ln380_fu_374_p1);
    sensitive << ( add_ln380_fu_369_p2 );

    SC_METHOD(thread_sext_ln391_fu_414_p1);
    sensitive << ( add_ln391_fu_409_p2 );

    SC_METHOD(thread_sext_ln402_fu_456_p1);
    sensitive << ( add_ln402_fu_451_p2 );

    SC_METHOD(thread_sub_ln370_fu_283_p2);
    sensitive << ( tmp_s_fu_263_p3 );
    sensitive << ( zext_ln370_fu_279_p1 );

    SC_METHOD(thread_sub_ln380_fu_347_p2);
    sensitive << ( tmp_3_fu_327_p3 );
    sensitive << ( zext_ln380_fu_343_p1 );

    SC_METHOD(thread_sub_ln703_fu_423_p2);
    sensitive << ( v214_0_V_q0 );
    sensitive << ( v224_V_0_reg_166 );

    SC_METHOD(thread_tmp_1_fu_271_p3);
    sensitive << ( i7_0_reg_133 );

    SC_METHOD(thread_tmp_3_fu_327_p3);
    sensitive << ( i8_0_reg_155 );

    SC_METHOD(thread_tmp_4_fu_335_p3);
    sensitive << ( i8_0_reg_155 );

    SC_METHOD(thread_tmp_s_fu_263_p3);
    sensitive << ( i7_0_reg_133 );

    SC_METHOD(thread_trunc_ln703_fu_474_p1);
    sensitive << ( grp_fu_469_p2 );

    SC_METHOD(thread_v213_0_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( sext_ln370_fu_310_p1 );

    SC_METHOD(thread_v213_0_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_v214_0_V_address0);
    sensitive << ( sext_ln370_reg_500 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( v214_0_V_addr_2_reg_551 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( v214_0_V_addr_3_reg_579 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state60 );
    sensitive << ( sext_ln380_fu_374_p1 );
    sensitive << ( sext_ln391_fu_414_p1 );
    sensitive << ( sext_ln402_fu_456_p1 );

    SC_METHOD(thread_v214_0_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( grp_pow_32_20_s_fu_223_ap_done );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state60 );

    SC_METHOD(thread_v214_0_V_d0);
    sensitive << ( v213_0_V_q0 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( grp_pow_32_20_s_fu_223_ap_return );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state60 );
    sensitive << ( trunc_ln703_fu_474_p1 );

    SC_METHOD(thread_v214_0_V_we0);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( grp_pow_32_20_s_fu_223_ap_done );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state60 );

    SC_METHOD(thread_zext_ln370_1_fu_301_p1);
    sensitive << ( k4_0_0_reg_144 );

    SC_METHOD(thread_zext_ln370_fu_279_p1);
    sensitive << ( tmp_1_fu_271_p3 );

    SC_METHOD(thread_zext_ln380_1_fu_365_p1);
    sensitive << ( k5_0_0_reg_178 );

    SC_METHOD(thread_zext_ln380_fu_343_p1);
    sensitive << ( tmp_4_fu_335_p3 );

    SC_METHOD(thread_zext_ln391_fu_405_p1);
    sensitive << ( k6_0_0_reg_201 );

    SC_METHOD(thread_zext_ln402_fu_447_p1);
    sensitive << ( k7_0_0_reg_212 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln367_fu_251_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln369_fu_289_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln375_fu_315_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln379_fu_353_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln390_fu_393_p2 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( grp_pow_32_20_s_fu_223_ap_done );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( icmp_ln401_fu_435_p2 );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000000000000000000000000000000000000000000000000001";
    grp_pow_32_20_s_fu_223_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "softmax_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, v213_0_V_address0, "(port)v213_0_V_address0");
    sc_trace(mVcdFile, v213_0_V_ce0, "(port)v213_0_V_ce0");
    sc_trace(mVcdFile, v213_0_V_q0, "(port)v213_0_V_q0");
    sc_trace(mVcdFile, v214_0_V_address0, "(port)v214_0_V_address0");
    sc_trace(mVcdFile, v214_0_V_ce0, "(port)v214_0_V_ce0");
    sc_trace(mVcdFile, v214_0_V_we0, "(port)v214_0_V_we0");
    sc_trace(mVcdFile, v214_0_V_d0, "(port)v214_0_V_d0");
    sc_trace(mVcdFile, v214_0_V_q0, "(port)v214_0_V_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i7_fu_257_p2, "i7_fu_257_p2");
    sc_trace(mVcdFile, i7_reg_482, "i7_reg_482");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sub_ln370_fu_283_p2, "sub_ln370_fu_283_p2");
    sc_trace(mVcdFile, sub_ln370_reg_487, "sub_ln370_reg_487");
    sc_trace(mVcdFile, icmp_ln367_fu_251_p2, "icmp_ln367_fu_251_p2");
    sc_trace(mVcdFile, add_ln369_fu_295_p2, "add_ln369_fu_295_p2");
    sc_trace(mVcdFile, add_ln369_reg_495, "add_ln369_reg_495");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, sext_ln370_fu_310_p1, "sext_ln370_fu_310_p1");
    sc_trace(mVcdFile, sext_ln370_reg_500, "sext_ln370_reg_500");
    sc_trace(mVcdFile, icmp_ln369_fu_289_p2, "icmp_ln369_fu_289_p2");
    sc_trace(mVcdFile, i8_fu_321_p2, "i8_fu_321_p2");
    sc_trace(mVcdFile, i8_reg_513, "i8_reg_513");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, sub_ln380_fu_347_p2, "sub_ln380_fu_347_p2");
    sc_trace(mVcdFile, sub_ln380_reg_518, "sub_ln380_reg_518");
    sc_trace(mVcdFile, icmp_ln375_fu_315_p2, "icmp_ln375_fu_315_p2");
    sc_trace(mVcdFile, add_ln379_fu_359_p2, "add_ln379_fu_359_p2");
    sc_trace(mVcdFile, add_ln379_reg_528, "add_ln379_reg_528");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln379_fu_353_p2, "icmp_ln379_fu_353_p2");
    sc_trace(mVcdFile, select_ln383_fu_385_p3, "select_ln383_fu_385_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, add_ln390_fu_399_p2, "add_ln390_fu_399_p2");
    sc_trace(mVcdFile, add_ln390_reg_546, "add_ln390_reg_546");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, v214_0_V_addr_2_reg_551, "v214_0_V_addr_2_reg_551");
    sc_trace(mVcdFile, icmp_ln390_fu_393_p2, "icmp_ln390_fu_393_p2");
    sc_trace(mVcdFile, sext_ln1148_fu_419_p1, "sext_ln1148_fu_419_p1");
    sc_trace(mVcdFile, sext_ln1148_reg_556, "sext_ln1148_reg_556");
    sc_trace(mVcdFile, sub_ln703_fu_423_p2, "sub_ln703_fu_423_p2");
    sc_trace(mVcdFile, sub_ln703_reg_561, "sub_ln703_reg_561");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, add_ln703_fu_429_p2, "add_ln703_fu_429_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_pow_32_20_s_fu_223_ap_ready, "grp_pow_32_20_s_fu_223_ap_ready");
    sc_trace(mVcdFile, grp_pow_32_20_s_fu_223_ap_done, "grp_pow_32_20_s_fu_223_ap_done");
    sc_trace(mVcdFile, add_ln401_fu_441_p2, "add_ln401_fu_441_p2");
    sc_trace(mVcdFile, add_ln401_reg_574, "add_ln401_reg_574");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, v214_0_V_addr_3_reg_579, "v214_0_V_addr_3_reg_579");
    sc_trace(mVcdFile, icmp_ln401_fu_435_p2, "icmp_ln401_fu_435_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_pow_32_20_s_fu_223_ap_start, "grp_pow_32_20_s_fu_223_ap_start");
    sc_trace(mVcdFile, grp_pow_32_20_s_fu_223_ap_idle, "grp_pow_32_20_s_fu_223_ap_idle");
    sc_trace(mVcdFile, grp_pow_32_20_s_fu_223_ap_return, "grp_pow_32_20_s_fu_223_ap_return");
    sc_trace(mVcdFile, i7_0_reg_133, "i7_0_reg_133");
    sc_trace(mVcdFile, k4_0_0_reg_144, "k4_0_0_reg_144");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i8_0_reg_155, "i8_0_reg_155");
    sc_trace(mVcdFile, v224_V_0_reg_166, "v224_V_0_reg_166");
    sc_trace(mVcdFile, k5_0_0_reg_178, "k5_0_0_reg_178");
    sc_trace(mVcdFile, v234_V_0_reg_189, "v234_V_0_reg_189");
    sc_trace(mVcdFile, k6_0_0_reg_201, "k6_0_0_reg_201");
    sc_trace(mVcdFile, k7_0_0_reg_212, "k7_0_0_reg_212");
    sc_trace(mVcdFile, ap_CS_fsm_state60, "ap_CS_fsm_state60");
    sc_trace(mVcdFile, grp_pow_32_20_s_fu_223_ap_start_reg, "grp_pow_32_20_s_fu_223_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, sext_ln380_fu_374_p1, "sext_ln380_fu_374_p1");
    sc_trace(mVcdFile, sext_ln391_fu_414_p1, "sext_ln391_fu_414_p1");
    sc_trace(mVcdFile, sext_ln402_fu_456_p1, "sext_ln402_fu_456_p1");
    sc_trace(mVcdFile, trunc_ln703_fu_474_p1, "trunc_ln703_fu_474_p1");
    sc_trace(mVcdFile, tmp_1_fu_271_p3, "tmp_1_fu_271_p3");
    sc_trace(mVcdFile, tmp_s_fu_263_p3, "tmp_s_fu_263_p3");
    sc_trace(mVcdFile, zext_ln370_fu_279_p1, "zext_ln370_fu_279_p1");
    sc_trace(mVcdFile, zext_ln370_1_fu_301_p1, "zext_ln370_1_fu_301_p1");
    sc_trace(mVcdFile, add_ln370_fu_305_p2, "add_ln370_fu_305_p2");
    sc_trace(mVcdFile, tmp_4_fu_335_p3, "tmp_4_fu_335_p3");
    sc_trace(mVcdFile, tmp_3_fu_327_p3, "tmp_3_fu_327_p3");
    sc_trace(mVcdFile, zext_ln380_fu_343_p1, "zext_ln380_fu_343_p1");
    sc_trace(mVcdFile, zext_ln380_1_fu_365_p1, "zext_ln380_1_fu_365_p1");
    sc_trace(mVcdFile, add_ln380_fu_369_p2, "add_ln380_fu_369_p2");
    sc_trace(mVcdFile, icmp_ln1494_fu_379_p2, "icmp_ln1494_fu_379_p2");
    sc_trace(mVcdFile, zext_ln391_fu_405_p1, "zext_ln391_fu_405_p1");
    sc_trace(mVcdFile, add_ln391_fu_409_p2, "add_ln391_fu_409_p2");
    sc_trace(mVcdFile, zext_ln402_fu_447_p1, "zext_ln402_fu_447_p1");
    sc_trace(mVcdFile, add_ln402_fu_451_p2, "add_ln402_fu_451_p2");
    sc_trace(mVcdFile, grp_fu_469_p0, "grp_fu_469_p0");
    sc_trace(mVcdFile, grp_fu_469_p1, "grp_fu_469_p1");
    sc_trace(mVcdFile, grp_fu_469_p2, "grp_fu_469_p2");
    sc_trace(mVcdFile, grp_fu_469_ap_start, "grp_fu_469_ap_start");
    sc_trace(mVcdFile, grp_fu_469_ap_done, "grp_fu_469_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

softmax::~softmax() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_pow_32_20_s_fu_223;
    delete attention_sdiv_44Bew_U78;
}

void softmax::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void softmax::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv32_2B7E;
}

void softmax::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pow_32_20_s_fu_223_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
            grp_pow_32_20_s_fu_223_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pow_32_20_s_fu_223_ap_ready.read())) {
            grp_pow_32_20_s_fu_223_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln369_fu_289_p2.read(), ap_const_lv1_1))) {
        i7_0_reg_133 = i7_reg_482.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i7_0_reg_133 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln367_fu_251_p2.read(), ap_const_lv1_1))) {
        i8_0_reg_155 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln401_fu_435_p2.read()))) {
        i8_0_reg_155 = i8_reg_513.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        k4_0_0_reg_144 = add_ln369_reg_495.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(icmp_ln367_fu_251_p2.read(), ap_const_lv1_0))) {
        k4_0_0_reg_144 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        k5_0_0_reg_178 = add_ln379_reg_528.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln375_fu_315_p2.read()))) {
        k5_0_0_reg_178 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln379_fu_353_p2.read(), ap_const_lv1_1))) {
        k6_0_0_reg_201 = ap_const_lv3_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                esl_seteq<1,1,1>(grp_pow_32_20_s_fu_223_ap_done.read(), ap_const_logic_1))) {
        k6_0_0_reg_201 = add_ln390_reg_546.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln390_fu_393_p2.read(), ap_const_lv1_1))) {
        k7_0_0_reg_212 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state60.read())) {
        k7_0_0_reg_212 = add_ln401_reg_574.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        v224_V_0_reg_166 = select_ln383_fu_385_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln375_fu_315_p2.read()))) {
        v224_V_0_reg_166 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(icmp_ln379_fu_353_p2.read(), ap_const_lv1_1))) {
        v234_V_0_reg_189 = ap_const_lv32_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
                esl_seteq<1,1,1>(grp_pow_32_20_s_fu_223_ap_done.read(), ap_const_logic_1))) {
        v234_V_0_reg_189 = add_ln703_fu_429_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln369_reg_495 = add_ln369_fu_295_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln379_reg_528 = add_ln379_fu_359_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        add_ln390_reg_546 = add_ln390_fu_399_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        add_ln401_reg_574 = add_ln401_fu_441_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i7_reg_482 = i7_fu_257_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i8_reg_513 = i8_fu_321_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln390_fu_393_p2.read(), ap_const_lv1_1))) {
        sext_ln1148_reg_556 = sext_ln1148_fu_419_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln369_fu_289_p2.read()))) {
        sext_ln370_reg_500 = sext_ln370_fu_310_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln367_fu_251_p2.read(), ap_const_lv1_0))) {
        sub_ln370_reg_487 = sub_ln370_fu_283_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln375_fu_315_p2.read()))) {
        sub_ln380_reg_518 = sub_ln380_fu_347_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sub_ln703_reg_561 = sub_ln703_fu_423_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln390_fu_393_p2.read()))) {
        v214_0_V_addr_2_reg_551 =  (sc_lv<7>) (sext_ln391_fu_414_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln401_fu_435_p2.read()))) {
        v214_0_V_addr_3_reg_579 =  (sc_lv<7>) (sext_ln402_fu_456_p1.read());
    }
}

void softmax::thread_add_ln369_fu_295_p2() {
    add_ln369_fu_295_p2 = (!k4_0_0_reg_144.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k4_0_0_reg_144.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax::thread_add_ln370_fu_305_p2() {
    add_ln370_fu_305_p2 = (!sub_ln370_reg_487.read().is_01() || !zext_ln370_1_fu_301_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln370_reg_487.read()) + sc_biguint<8>(zext_ln370_1_fu_301_p1.read()));
}

void softmax::thread_add_ln379_fu_359_p2() {
    add_ln379_fu_359_p2 = (!k5_0_0_reg_178.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k5_0_0_reg_178.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax::thread_add_ln380_fu_369_p2() {
    add_ln380_fu_369_p2 = (!sub_ln380_reg_518.read().is_01() || !zext_ln380_1_fu_365_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln380_reg_518.read()) + sc_biguint<8>(zext_ln380_1_fu_365_p1.read()));
}

void softmax::thread_add_ln390_fu_399_p2() {
    add_ln390_fu_399_p2 = (!k6_0_0_reg_201.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k6_0_0_reg_201.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax::thread_add_ln391_fu_409_p2() {
    add_ln391_fu_409_p2 = (!sub_ln380_reg_518.read().is_01() || !zext_ln391_fu_405_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln380_reg_518.read()) + sc_biguint<8>(zext_ln391_fu_405_p1.read()));
}

void softmax::thread_add_ln401_fu_441_p2() {
    add_ln401_fu_441_p2 = (!k7_0_0_reg_212.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(k7_0_0_reg_212.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void softmax::thread_add_ln402_fu_451_p2() {
    add_ln402_fu_451_p2 = (!sub_ln380_reg_518.read().is_01() || !zext_ln402_fu_447_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(sub_ln380_reg_518.read()) + sc_biguint<8>(zext_ln402_fu_447_p1.read()));
}

void softmax::thread_add_ln703_fu_429_p2() {
    add_ln703_fu_429_p2 = (!v234_V_0_reg_189.read().is_01() || !grp_pow_32_20_s_fu_223_ap_return.read().is_01())? sc_lv<32>(): (sc_bigint<32>(v234_V_0_reg_189.read()) + sc_biguint<32>(grp_pow_32_20_s_fu_223_ap_return.read()));
}

void softmax::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void softmax::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void softmax::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void softmax::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void softmax::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void softmax::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void softmax::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void softmax::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void softmax::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void softmax::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void softmax::thread_ap_CS_fsm_state60() {
    ap_CS_fsm_state60 = ap_CS_fsm.read()[59];
}

void softmax::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void softmax::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void softmax::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void softmax::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
          esl_seteq<1,1,1>(icmp_ln375_fu_315_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void softmax::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void softmax::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln375_fu_315_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void softmax::thread_grp_fu_469_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_469_ap_start = ap_const_logic_1;
    } else {
        grp_fu_469_ap_start = ap_const_logic_0;
    }
}

void softmax::thread_grp_fu_469_p0() {
    grp_fu_469_p0 = esl_concat<32,12>(v214_0_V_q0.read(), ap_const_lv12_0);
}

void softmax::thread_grp_fu_469_p1() {
    grp_fu_469_p1 =  (sc_lv<32>) (sext_ln1148_reg_556.read());
}

void softmax::thread_grp_pow_32_20_s_fu_223_ap_start() {
    grp_pow_32_20_s_fu_223_ap_start = grp_pow_32_20_s_fu_223_ap_start_reg.read();
}

void softmax::thread_i7_fu_257_p2() {
    i7_fu_257_p2 = (!i7_0_reg_133.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i7_0_reg_133.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void softmax::thread_i8_fu_321_p2() {
    i8_fu_321_p2 = (!i8_0_reg_155.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i8_0_reg_155.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void softmax::thread_icmp_ln1494_fu_379_p2() {
    icmp_ln1494_fu_379_p2 = (!v214_0_V_q0.read().is_01() || !v224_V_0_reg_166.read().is_01())? sc_lv<1>(): (sc_bigint<32>(v214_0_V_q0.read()) > sc_bigint<32>(v224_V_0_reg_166.read()));
}

void softmax::thread_icmp_ln367_fu_251_p2() {
    icmp_ln367_fu_251_p2 = (!i7_0_reg_133.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i7_0_reg_133.read() == ap_const_lv5_10);
}

void softmax::thread_icmp_ln369_fu_289_p2() {
    icmp_ln369_fu_289_p2 = (!k4_0_0_reg_144.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k4_0_0_reg_144.read() == ap_const_lv3_6);
}

void softmax::thread_icmp_ln375_fu_315_p2() {
    icmp_ln375_fu_315_p2 = (!i8_0_reg_155.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(i8_0_reg_155.read() == ap_const_lv5_10);
}

void softmax::thread_icmp_ln379_fu_353_p2() {
    icmp_ln379_fu_353_p2 = (!k5_0_0_reg_178.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k5_0_0_reg_178.read() == ap_const_lv3_6);
}

void softmax::thread_icmp_ln390_fu_393_p2() {
    icmp_ln390_fu_393_p2 = (!k6_0_0_reg_201.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k6_0_0_reg_201.read() == ap_const_lv3_6);
}

void softmax::thread_icmp_ln401_fu_435_p2() {
    icmp_ln401_fu_435_p2 = (!k7_0_0_reg_212.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(k7_0_0_reg_212.read() == ap_const_lv3_6);
}

void softmax::thread_select_ln383_fu_385_p3() {
    select_ln383_fu_385_p3 = (!icmp_ln1494_fu_379_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln1494_fu_379_p2.read()[0].to_bool())? v214_0_V_q0.read(): v224_V_0_reg_166.read());
}

void softmax::thread_sext_ln1148_fu_419_p1() {
    sext_ln1148_fu_419_p1 = esl_sext<44,32>(v234_V_0_reg_189.read());
}

void softmax::thread_sext_ln370_fu_310_p1() {
    sext_ln370_fu_310_p1 = esl_sext<64,8>(add_ln370_fu_305_p2.read());
}

void softmax::thread_sext_ln380_fu_374_p1() {
    sext_ln380_fu_374_p1 = esl_sext<64,8>(add_ln380_fu_369_p2.read());
}

void softmax::thread_sext_ln391_fu_414_p1() {
    sext_ln391_fu_414_p1 = esl_sext<64,8>(add_ln391_fu_409_p2.read());
}

void softmax::thread_sext_ln402_fu_456_p1() {
    sext_ln402_fu_456_p1 = esl_sext<64,8>(add_ln402_fu_451_p2.read());
}

void softmax::thread_sub_ln370_fu_283_p2() {
    sub_ln370_fu_283_p2 = (!tmp_s_fu_263_p3.read().is_01() || !zext_ln370_fu_279_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_s_fu_263_p3.read()) - sc_biguint<8>(zext_ln370_fu_279_p1.read()));
}

void softmax::thread_sub_ln380_fu_347_p2() {
    sub_ln380_fu_347_p2 = (!tmp_3_fu_327_p3.read().is_01() || !zext_ln380_fu_343_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_3_fu_327_p3.read()) - sc_biguint<8>(zext_ln380_fu_343_p1.read()));
}

void softmax::thread_sub_ln703_fu_423_p2() {
    sub_ln703_fu_423_p2 = (!v214_0_V_q0.read().is_01() || !v224_V_0_reg_166.read().is_01())? sc_lv<32>(): (sc_biguint<32>(v214_0_V_q0.read()) - sc_biguint<32>(v224_V_0_reg_166.read()));
}

void softmax::thread_tmp_1_fu_271_p3() {
    tmp_1_fu_271_p3 = esl_concat<5,1>(i7_0_reg_133.read(), ap_const_lv1_0);
}

void softmax::thread_tmp_3_fu_327_p3() {
    tmp_3_fu_327_p3 = esl_concat<5,3>(i8_0_reg_155.read(), ap_const_lv3_0);
}

void softmax::thread_tmp_4_fu_335_p3() {
    tmp_4_fu_335_p3 = esl_concat<5,1>(i8_0_reg_155.read(), ap_const_lv1_0);
}

void softmax::thread_tmp_s_fu_263_p3() {
    tmp_s_fu_263_p3 = esl_concat<5,3>(i7_0_reg_133.read(), ap_const_lv3_0);
}

void softmax::thread_trunc_ln703_fu_474_p1() {
    trunc_ln703_fu_474_p1 = grp_fu_469_p2.read().range(32-1, 0);
}

void softmax::thread_v213_0_V_address0() {
    v213_0_V_address0 =  (sc_lv<7>) (sext_ln370_fu_310_p1.read());
}

void softmax::thread_v213_0_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        v213_0_V_ce0 = ap_const_logic_1;
    } else {
        v213_0_V_ce0 = ap_const_logic_0;
    }
}

void softmax::thread_v214_0_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state60.read())) {
        v214_0_V_address0 = v214_0_V_addr_3_reg_579.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        v214_0_V_address0 =  (sc_lv<7>) (sext_ln402_fu_456_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        v214_0_V_address0 = v214_0_V_addr_2_reg_551.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        v214_0_V_address0 =  (sc_lv<7>) (sext_ln391_fu_414_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        v214_0_V_address0 =  (sc_lv<7>) (sext_ln380_fu_374_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        v214_0_V_address0 =  (sc_lv<7>) (sext_ln370_reg_500.read());
    } else {
        v214_0_V_address0 = "XXXXXXX";
    }
}

void softmax::thread_v214_0_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(grp_pow_32_20_s_fu_223_ap_done.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state60.read()))) {
        v214_0_V_ce0 = ap_const_logic_1;
    } else {
        v214_0_V_ce0 = ap_const_logic_0;
    }
}

void softmax::thread_v214_0_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state60.read())) {
        v214_0_V_d0 = trunc_ln703_fu_474_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        v214_0_V_d0 = grp_pow_32_20_s_fu_223_ap_return.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        v214_0_V_d0 = v213_0_V_q0.read();
    } else {
        v214_0_V_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void softmax::thread_v214_0_V_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && 
          esl_seteq<1,1,1>(grp_pow_32_20_s_fu_223_ap_done.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state60.read()))) {
        v214_0_V_we0 = ap_const_logic_1;
    } else {
        v214_0_V_we0 = ap_const_logic_0;
    }
}

void softmax::thread_zext_ln370_1_fu_301_p1() {
    zext_ln370_1_fu_301_p1 = esl_zext<8,3>(k4_0_0_reg_144.read());
}

void softmax::thread_zext_ln370_fu_279_p1() {
    zext_ln370_fu_279_p1 = esl_zext<8,6>(tmp_1_fu_271_p3.read());
}

void softmax::thread_zext_ln380_1_fu_365_p1() {
    zext_ln380_1_fu_365_p1 = esl_zext<8,3>(k5_0_0_reg_178.read());
}

void softmax::thread_zext_ln380_fu_343_p1() {
    zext_ln380_fu_343_p1 = esl_zext<8,6>(tmp_4_fu_335_p3.read());
}

void softmax::thread_zext_ln391_fu_405_p1() {
    zext_ln391_fu_405_p1 = esl_zext<8,3>(k6_0_0_reg_201.read());
}

void softmax::thread_zext_ln402_fu_447_p1() {
    zext_ln402_fu_447_p1 = esl_zext<8,3>(k7_0_0_reg_212.read());
}

void softmax::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln367_fu_251_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln369_fu_289_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln375_fu_315_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln379_fu_353_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln390_fu_393_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(grp_pow_32_20_s_fu_223_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln401_fu_435_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state13;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state44;
            break;
        case 8796093022208 : 
            ap_NS_fsm = ap_ST_fsm_state45;
            break;
        case 17592186044416 : 
            ap_NS_fsm = ap_ST_fsm_state46;
            break;
        case 35184372088832 : 
            ap_NS_fsm = ap_ST_fsm_state47;
            break;
        case 70368744177664 : 
            ap_NS_fsm = ap_ST_fsm_state48;
            break;
        case 140737488355328 : 
            ap_NS_fsm = ap_ST_fsm_state49;
            break;
        case 281474976710656 : 
            ap_NS_fsm = ap_ST_fsm_state50;
            break;
        case 562949953421312 : 
            ap_NS_fsm = ap_ST_fsm_state51;
            break;
        case 1125899906842624 : 
            ap_NS_fsm = ap_ST_fsm_state52;
            break;
        case 2251799813685248 : 
            ap_NS_fsm = ap_ST_fsm_state53;
            break;
        case 4503599627370496 : 
            ap_NS_fsm = ap_ST_fsm_state54;
            break;
        case 9007199254740992 : 
            ap_NS_fsm = ap_ST_fsm_state55;
            break;
        case 18014398509481984 : 
            ap_NS_fsm = ap_ST_fsm_state56;
            break;
        case 36028797018963968 : 
            ap_NS_fsm = ap_ST_fsm_state57;
            break;
        case 72057594037927936 : 
            ap_NS_fsm = ap_ST_fsm_state58;
            break;
        case 144115188075855872 : 
            ap_NS_fsm = ap_ST_fsm_state59;
            break;
        case 288230376151711744 : 
            ap_NS_fsm = ap_ST_fsm_state60;
            break;
        case 576460752303423488 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<60>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

