directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:and#1.mdf.sva REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5:and#1.mdf.sva
directive set /dut/dut:core/core/exitL:exit:LINEAR_FORWARD_NO_MUL_LOOP_5.lpi#2 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5:and#1.mdf.sva
directive set /dut/dut:core/core/exitL:exit:LINEAR_FORWARD_NO_MUL_LOOP_5.lpi#3 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5:and#1.mdf.sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2(39) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2(39)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2.dfm#1(39) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2(39)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2(38:0) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2(38:0)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2.dfm#1(38:0) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1:max_val.lpi#2(38:0)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2(39) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2(39)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2.dfm#1(39) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2(39)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2(38:0) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2(38:0)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2.dfm#1(38:0) REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:max_val.lpi#2(38:0)
directive set /dut/dut:core/core/exitL:exit:LINEAR_FORWARD_NO_MUL_LOOP_5#3.lpi#2 REGISTER_NAME exitL:exit:LINEAR_FORWARD_NO_MUL_LOOP_5#3.lpi#2
directive set /dut/dut:core/core/exitL:exit:LINEAR_FORWARD_NO_MUL_LOOP_5#3.lpi#3 REGISTER_NAME exitL:exit:LINEAR_FORWARD_NO_MUL_LOOP_5#3.lpi#2
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val.lpi#3 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#188.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:mux1h#3.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:mux1h#3.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val.lpi#3 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val.lpi#3
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#192.sdt(6:0) REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val.lpi#3
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).lpi#3(1:0) REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).lpi#3(1:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#3:l(2:0).lpi#3(1:0) REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).lpi#3(1:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#17.cse.sva REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).lpi#3(1:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.2 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.2
directive set /dut/dut:core/core/exit:LINEAR_FORWARD_NO_MUL_LOOP_3.lpi#3.dfm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.2
directive set /dut/dut:core/core/exit:APPLY_ROTARY_POS_EMB_LOOP_3.sva.dfm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.2
directive set /dut/dut:core/core/exit:QUANTIZE_ACTIVATION_LOOP_2#1.sva.dfm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.2
directive set /dut/dut:core/core/exit:QUANTIZE_ACTIVATION_LOOP_2.sva.dfm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.2
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val.lpi#3 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val.lpi#3
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#187.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val.lpi#3
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val.lpi#3.dfm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val.lpi#3.dfm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#191.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val.lpi#3.dfm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13.psp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#233.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#235.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13.psp
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#13.psp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#209.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#211.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#213.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#215.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#217.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#219.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#221.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#223.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#37.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#13.sdt
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_4:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/ATTN_2D_LOOP_2:h(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_2:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:k(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3:ko(2:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#3:l(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SF_LOOP_3:acc#85.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:k(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:k(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#3.psp.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:acc#16.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#33.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#181.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_4#1:ji(4:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_4:ji(4:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:div.svs REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:div.svs.1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#3:weight_val:div.svs REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:weight_val:div.svs REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:acc#16.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:mul.sdt#1.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#53.cse.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:l(2:0).lpi#3(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:d(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc.psp.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#242.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:l(2:0).lpi#3.dfm(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:slc(ATTN_2D_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:slc(GEMM_3D_FLOAT_LOOP_3#1:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:slc(GEMM_3D_FLOAT_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:slc(LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:slc(RMS_NORM_LOOP_1#2:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SF_LOOP_3:slc(SF_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_3:slc(SOFTMAX_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:slc(SOFTMAX_LOOP_4:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:slc(SOFTMAX_LOOP_5:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:slc(TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/attention_sqrt#1:for:slc(attention_sqrt#1:for:acc)(3).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/attention_sqrt:for:slc(attention_sqrt:for:acc)(3).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/for#1:for:slc(for#1:for:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:or.itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:acc#13.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:acc#17.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:acc#7.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:acc#7.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#2:ki(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:acc#11.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:acc#11.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/SF_LOOP_3:acc#9.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:x:acc.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:acc#6.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:acc#12.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:acc#17.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:acc#6.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:acc#6.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#1:ki(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#3:ki(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_4#1:ji(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_4:ji(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:acc#10.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:acc#10.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/SF_LOOP_3:acc#58.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:x:acc#4.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:acc#5.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#22.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#25.itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:d(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#36.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#34.cse.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:l(2:0).lpi#3(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:k(5:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:k(5:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:k(5:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:k(5:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#22.cse.sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).lpi#3.dfm(1:0) REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#4.psp.sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_2#1:j(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:k(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#2:ko(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SF_LOOP_3:d(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:k(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_3:k(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_3:k(2:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:acc#30.psp.sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2:and#1.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:LINEAR_FORWARD_NO_MUL_LOOP_2:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0 REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0 REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5#1-4:attention_round#1:slc()(40).svs.st REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5-4:attention_round:slc()(40).svs.st REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:not.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:RESHAPE_2D_TO_3D_LOOP_3:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:not.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:not.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/for:for:for:for:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:qif:acc#3.ncse(2:0) REGISTER_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#15.cse.sva REGISTER_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:mux#2.itm REGISTER_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/SF_LOOP_3:d(2:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0) REGISTER_NAME CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#179.sdt REGISTER_NAME CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:mux#3.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:k(5:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:k(5:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#32.sdt REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#128.cse.sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:mux#11.itm(3:0) REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#185.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#185.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:lshift.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#185.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:mul.sdt#15.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:mul.sdt#15.sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:mul.sdt#15.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#190.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#190.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val.lpi#3.dfm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#190.sdt
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:mux1h#2.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#190.sdt
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:mux1h#2.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#190.sdt
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#28.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#190.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#208.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#226.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#234.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:slc(attention<5,1,384,384,8,48>:attn_weights:rsci.data_out_d)(39-0)#4.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/softmax<1,8,6>:sum.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/softmax<1,8,6>:sum.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/rms_norm<384>#1:variance#1.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/rms_norm<384>:variance#1.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/rms_norm<384>:variance#1.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/rms_norm<384>#1:variance#1.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/rms_norm<384>#1:variance.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/rms_norm<384>:variance.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:_qr.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#2:slc(attention<5,1,384,384,8,48>:v_proj_re:rsci.data_out_d)(39-0).psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/SF_LOOP_3:mul.sdt.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4-17:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#193.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#195.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#197.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#199.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#201.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#203.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#205.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1-2:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:slc(attention<5,1,384,384,8,48>:q_proj_re:rsci.data_out_d)(39-0).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/attention_abs#3:_qr.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/attention_abs#7:_qr.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4:acc#193.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#5.psp.sva REGISTER_NAME SF_LOOP_3:acc#5.psp.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#2:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#5.psp.sva
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2.dfr.sva REGISTER_NAME SF_LOOP_3:acc#5.psp.sva
directive set /dut/dut:core/core/RMS_NORM_LOOP_2.dfr.sva REGISTER_NAME SF_LOOP_3:acc#5.psp.sva
directive set /dut/dut:core/core/attention_sqrt#1:guess.sva(39:30) REGISTER_NAME SF_LOOP_3:acc#5.psp.sva
directive set /dut/dut:core/core/attention_sqrt:guess.sva(39:30) REGISTER_NAME SF_LOOP_3:acc#5.psp.sva
directive set /dut/dut:core/core/SF_LOOP_3:acc#45.itm REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/attention<5,1,384,384,8,48>:q_proj_re:vinit.ndx.sva REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/output:vinit.ndx.sva REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#3:acc.itm REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2:acc.itm REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:acc#3.itm REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:acc#3.itm REGISTER_NAME SF_LOOP_3:acc#45.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#53.itm(27:15) REGISTER_NAME SF_LOOP_3:acc#53.itm(27:15)
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:i(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#53.itm(27:15)
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:i(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#53.itm(27:15)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#53.itm(27:15)
directive set /dut/dut:core/core/SF_LOOP_3:acc#53.itm(14:0) REGISTER_NAME SF_LOOP_3:acc#53.itm(14:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#53.itm(14:0)
directive set /dut/dut:core/core/SF_LOOP_3:acc#38.itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#40.itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#3:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#39.itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:sinval:slc(sin_tab,*40)(39-0).psp.sva REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#2:acc.itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/attention<5,1,384,384,8,48>:v_proj_re:vinit.ndx.sva REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#2:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/for:for:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/for:for:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_2#1:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_2:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:mux#4.itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:mux#4.itm REGISTER_NAME SF_LOOP_3:acc#38.itm
directive set /dut/dut:core/core/operator+<40,24,true,AC_TRN,AC_WRAP>:acc#8.psp REGISTER_NAME operator+<40,24,true,AC_TRN,AC_WRAP>:acc#8.psp
directive set /dut/dut:core/core/attention_exp:exp_half:mul#4.cse.sva REGISTER_NAME operator+<40,24,true,AC_TRN,AC_WRAP>:acc#8.psp
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#11.sdt REGISTER_NAME operator+<40,24,true,AC_TRN,AC_WRAP>:acc#8.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SOFTMAX_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_2#1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_2#2:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SF_LOOP_1:h(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_1#1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#41.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#41.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#177.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#41.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#28.cse.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#28.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#241.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#28.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:mux#10.itm(3:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#28.cse.sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:acc#11.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#28.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#42.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#42.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#178.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#42.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#43.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#43.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#180.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#43.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#34.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#34.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#161.cse.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#34.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#23.cse.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#23.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#240.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#23.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:ki(4:0).sva(3:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#23.cse.sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:acc#10.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#23.cse.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#45.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#45.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#239.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#45.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:acc#20.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#20.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#183.sdt REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#20.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:lshift.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#20.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1-6:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-16:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-20:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-22:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-14:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-12:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-10:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-24:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-26:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-28:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-2:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-30:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-32:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-34:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-36:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-6:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-8:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-4:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-48:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-46:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-44:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-42:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-40:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4-38:slc(GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul)(55-16).itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#207.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:_qr.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:slc(attention<5,1,384,384,8,48>:k_proj_re:rsci.data_out_d)(39-0).psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:slc(output:rsci.data_out_d)(39-0).psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:RMS_NORM_LOOP_2#2:slc()(71-32)#1.ncse.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:slc(RMS_NORM_LOOP_2:mul)(67-28).ncse.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/SF_LOOP_3:slc(attention<5,1,384,384,8,48>:attn_weights,*40)(39-0).psp.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:slc(attention<5,1,384,384,8,48>:attn_weights:rsci.data_out_d)(39-0).psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_max<attn_fixed_t>#1:conc.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_max<attn_fixed_t>:attention_max<attn_fixed_t>:and.mut REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_round:a#1.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_round:a.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_sqrt#1:guess.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_sqrt:guess.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/drf(output).sdt#1.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/drf(output).sdt#2.sva.1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1-4:slc(GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul)(55-16).itm
directive set /dut/dut:core/core/attention_sqrt#1:guess.sva(29:0) REGISTER_NAME attention_sqrt#1:guess.sva(29:0)
directive set /dut/dut:core/core/attention_sqrt:guess.sva(29:0) REGISTER_NAME attention_sqrt#1:guess.sva(29:0)
directive set /dut/dut:core/core/attention_exp:exp_half:slc(operator+<40,24,true,AC_TRN,AC_WRAP>:acc)(77-48).psp.sva REGISTER_NAME attention_sqrt#1:guess.sva(29:0)
directive set /dut/dut:core/core/attention_abs#4:qif:acc:pmx.lpi#1.dfm REGISTER_NAME attention_abs#4:qif:acc:pmx.lpi#1.dfm
directive set /dut/dut:core/core/attention_abs:qif:acc:pmx.lpi#1.dfm REGISTER_NAME attention_abs#4:qif:acc:pmx.lpi#1.dfm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#52.itm REGISTER_NAME attention_abs#4:qif:acc:pmx.lpi#1.dfm
directive set /dut/dut:core/core/attention_sqrt#1:for:i(4:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/attention_sqrt:for:i(4:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/attention_sqrt#1:for:i(4:0).sva#1 REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/attention_sqrt:for:i(4:0).sva#1 REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:k(4:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#1:ko(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#3:ko(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_2:j(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_3#1:jo(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_3:jo(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:k(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_2:j(2:0).sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc.cse.sva REGISTER_NAME attention_sqrt#1:for:i(4:0).sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_2#1:slc()(40)#1.svs REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_2#1:slc()(40)#1.svs
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_2:slc()(40)#1.svs REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_2#1:slc()(40)#1.svs
directive set /dut/dut:core/core/lfst:exit:LINEAR_FORWARD_NO_MUL_LOOP_4#3.sva REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_2#1:slc()(40)#1.svs
directive set /dut/dut:core/core/lfst:exit:LINEAR_FORWARD_NO_MUL_LOOP_4.sva REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_2#1:slc()(40)#1.svs
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1#1:scale.sva REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:scale.sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1:scale.sva REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:scale.sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#237.itm REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:scale.sva
directive set /dut/dut:core/core/softmax<1,8,6>:max_val.sva REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:scale.sva
directive set /dut/dut:core/core/softmax<1,8,6>:max_val.sva.dfm REGISTER_NAME QUANTIZE_ACTIVATION_LOOP_1#1:scale.sva
directive set /dut/dut:core/core/attention_round#1:_qr(39:16)#3.lpi#3.dfm REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/attention_round#1:_qr(39:16).sva#1 REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/attention_round:_qr(39:16)#3.lpi#3.dfm REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/attention_round:_qr(39:16).sva#1 REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:cosval:slc(cos_tab,*40)(39-0).psp.sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/SF_LOOP_3:acc#47.itm REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:x.lpi#3.dfm#1(20:1) REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#1:acc.itm REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/attention<5,1,384,384,8,48>:k_proj_re:vinit.ndx.sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:j(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:j(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:i(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:i(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/for#1:for:j(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/for#1:for:j(8:0).sva#1 REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#1:i(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:i(8:0).sva REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#1:i(8:0).sva#1 REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:i(8:0).sva#1 REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#17.sdt REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#33.itm REGISTER_NAME attention_round#1:_qr(39:16)#3.lpi#3.dfm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0.1 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0.1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3.stage_0.1 REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0.1
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:unequal.tmp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0.1
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:unequal.tmp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0.1
directive set /dut/dut:core/core/exit:APPLY_ROTARY_POS_EMB_LOOP_3.sva REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_3#3.stage_0.1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#8.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#8.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:acc#12.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#8.sdt
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:mul#1.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#8.sdt
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:mul#1.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#8.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/operator+<40,24,true,AC_TRN,AC_WRAP>:acc#7.psp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#14.psp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#225.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#227.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#229.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:acc#231.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:slc(attention<5,1,384,384,8,48>:v_cache_upd:rsci.data_out_d)(39-0)#4.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12.sdt
