directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:SF_LOOP_3:acc RESOURCE_NAME SF_LOOP_3:SF_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#57 RESOURCE_NAME SF_LOOP_3:SF_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#49 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#49:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#49 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#49:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#36 RESOURCE_NAME SF_LOOP_3:acc#5:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#5 RESOURCE_NAME SF_LOOP_3:acc#5:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#47 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#47:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#47 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#47:rg
directive set /dut/dut:core/dut:core:conc/operator+<40,24,true,AC_TRN,AC_WRAP>:acc#6 RESOURCE_NAME operator+<40,24,true,AC_TRN,AC_WRAP>:acc#6:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#53 RESOURCE_NAME operator+<40,24,true,AC_TRN,AC_WRAP>:acc#6:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#53 RESOURCE_NAME operator+<40,24,true,AC_TRN,AC_WRAP>:acc#6:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#29 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#29:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#29 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#29:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#31 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#31 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val:acc RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#33 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#33 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:acc RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-4:attention_round:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-4:attention_round#1:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-3:attention_round:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#50 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12:rg
directive set /dut/dut:core/dut:core:conc/operator+<40,24,true,AC_TRN,AC_WRAP>:acc#7 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12:rg
directive set /dut/dut:core/dut:core:conc/rms_norm<384>:val:acc RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12:rg
directive set /dut/dut:core/dut:core:conc/rms_norm<384>#1:val:acc RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#12:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:RMS_NORM_LOOP_1#2:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/attention_exp:exp_half:mul#5 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/attention_sqrt:for:guess_inv:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-4:quant_val:mul#2 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-4:quant_val:mul#2 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1-1:GEMM_3D_FLOAT_LOOP_4#1:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:RMS_NORM_LOOP_1#1:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/attention_exp:exp_half:mul#6 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/attention_exp:exp_half:mul#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/attention_exp:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4-9:GEMM_3D_FLOAT_LOOP_4:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1-6:GEMM_3D_FLOAT_LOOP_4#1:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#8 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#8:rg
directive set /dut/dut:core/dut:core:conc/attention_abs#2:qif:acc#1 RESOURCE_NAME attention_abs#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_abs#6:qif:acc#1 RESOURCE_NAME attention_abs#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_abs#3:qif:acc#1 RESOURCE_NAME attention_abs#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_abs#1:qif:acc RESOURCE_NAME attention_abs#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_abs#5:qif:acc RESOURCE_NAME attention_abs#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#43 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#43:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#43 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#43:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:acc#17 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#22 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:acc#28 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#32 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc#44 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#177 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#44:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#44 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#10:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#10 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#10:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#250 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#10:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#17 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#17:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#40 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#17:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#45 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#17:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#83 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#17:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#20 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#17:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#249 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#46 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#72 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#6:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#1:acc#10 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#6:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#2:acc#10 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#6:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_3:acc#6 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#6:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:x:acc#4 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#6:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#15 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#15:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#3:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#15:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#70 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#15:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#2:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#15:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#188:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#60 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#188:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#188 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#188:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#1:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#188:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#30:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#85 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#30:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc#30 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#30:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5:acc#2 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#30:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#27 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#27 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#53 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#16 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_3:acc#45 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#45:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:acc#29 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#45:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#180 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#45:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#34 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#45:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#14 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#45:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#21 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#15:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#84 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#15:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#67 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#15:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:acc#15 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#15:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#178 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#15:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#72 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#15:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#15 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#15:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#18 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#15:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#243 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#15:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#65 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#7:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_3:acc#7 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#7:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#1:acc#11 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#7:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#2:acc#11 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#7:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:x:acc RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#7:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#59 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_3:acc#1 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:qif:acc#3 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#179 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#12 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#30 RESOURCE_NAME CACHE_UPDATE_LOOP_3:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#62 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3#2:acc#1 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:qif:acc#3 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:qif:acc#3:rg
directive set /dut/dut:core/dut:core:conc/for:for:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#184:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#63 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#184:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#184 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#184:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3#2:acc#2 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#18:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#18 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#18:rg
directive set /dut/dut:core/dut:core:conc/for:for:acc#3 RESOURCE_NAME CACHE_UPDATE_LOOP_3:acc#18:rg
directive set /dut/dut:core/dut:core:conc/operator+<40,24,true,AC_TRN,AC_WRAP>:acc#5 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#30:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#23 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#30:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:acc#30 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#30:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:acc#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#30:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3#1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#30:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:acc#3 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#16:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#2 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#16:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3#1:acc#16 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#16:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#181 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#16:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3:acc#1 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#16:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#19 RESOURCE_NAME CACHE_UPDATE_LOOP_3#1:acc#16:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#252 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#43:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#43 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#43:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#61 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#187:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#187 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#187:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#41 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#41:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_2#1:acc#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#41:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#253 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#41:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#246 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#47:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4:acc#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#47:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#47 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#47:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#42 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#239 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#2:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc#1 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val:acc#1 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc#1:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#20 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#20:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#21 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#20:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#13 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#13:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#8 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#10:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#10 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#10:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#7 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#9:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#9 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#9:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#5 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#7:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#7 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#7:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-2:quantized_value_clamped:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-1:quantized_value_clamped:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-2:quantized_value_clamped:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:qelse:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:qelse:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-3:quantized_value_clamped:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5-3:quantized_value_clamped:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-4:quantized_value_clamped:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5-3:quantized_value_clamped:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-3:quantized_value_clamped:qelse:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5-3:quantized_value_clamped:qelse:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-4:quantized_value_clamped:qelse:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5-3:quantized_value_clamped:qelse:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-2:quantized_value_clamped:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-1:quantized_value_clamped:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-2:quantized_value_clamped:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5-1:quantized_value_clamped:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-1:quantized_value_clamped:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5-1:quantized_value_clamped:acc:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#38 RESOURCE_NAME SF_LOOP_3:acc#54:rg
directive set /dut/dut:core/dut:core:conc/SF_LOOP_3:acc#54 RESOURCE_NAME SF_LOOP_3:acc#54:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-3:attention_round:qif:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qif:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_2#1:acc#4 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_2#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/attention_sqrt:for:acc#5 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_2#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_3:acc#3 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_2#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#45 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#45:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#45 RESOURCE_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#45:rg
directive set /dut/dut:core/dut:core:conc/attention_max<attn_fixed_t>:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/attention_max<attn_fixed_t>#1:acc RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5-3:attention_round:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:acc#1 RESOURCE_NAME QUANTIZE_ACTIVATION_LOOP_5#1-3:attention_round#1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#6 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#8:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#8 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#8:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5:weight_val:div RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:div:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:div RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:div:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:div RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:div:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_5#3:weight_val:div RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:div:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#51 RESOURCE_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#51 RESOURCE_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc#1 RESOURCE_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#3:acc RESOURCE_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:acc RESOURCE_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/attention_abs:qif:acc RESOURCE_NAME attention_abs#4:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/attention_abs#4:qif:acc RESOURCE_NAME attention_abs#4:qif:acc:rg
directive set /dut/dut:core/dut:core:conc/operator+<40,24,true,AC_TRN,AC_WRAP>:acc#8 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#39:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#12 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#39:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#39 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#39:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:acc#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#234 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#208 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:acc#5 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:acc#1 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#237 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#233 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#254 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#111 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#111:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:x:acc#2 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#224:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#224 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4:acc#224:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#226 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#40:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#229 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#40:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#238 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#40:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#40 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#40:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#217 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#37:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:acc#37 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#37:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#236 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:acc#37:rg
