// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _apply_rotary_pos_emb_HH_
#define _apply_rotary_pos_emb_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "apply_rotary_pos_g8j.h"
#include "apply_rotary_pos_hbi.h"
#include "apply_rotary_pos_ibs.h"

namespace ap_rtl {

struct apply_rotary_pos_emb : public sc_module {
    // Port declarations 26
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<5> > input_q_0_V_address0;
    sc_out< sc_logic > input_q_0_V_ce0;
    sc_in< sc_lv<40> > input_q_0_V_q0;
    sc_out< sc_lv<5> > input_q_0_V_address1;
    sc_out< sc_logic > input_q_0_V_ce1;
    sc_in< sc_lv<40> > input_q_0_V_q1;
    sc_out< sc_lv<5> > input_k_0_V_address0;
    sc_out< sc_logic > input_k_0_V_ce0;
    sc_in< sc_lv<40> > input_k_0_V_q0;
    sc_out< sc_lv<5> > input_k_0_V_address1;
    sc_out< sc_logic > input_k_0_V_ce1;
    sc_in< sc_lv<40> > input_k_0_V_q1;
    sc_out< sc_lv<5> > output_q_0_V_address0;
    sc_out< sc_logic > output_q_0_V_ce0;
    sc_out< sc_logic > output_q_0_V_we0;
    sc_out< sc_lv<40> > output_q_0_V_d0;
    sc_out< sc_lv<5> > output_k_0_V_address0;
    sc_out< sc_logic > output_k_0_V_ce0;
    sc_out< sc_logic > output_k_0_V_we0;
    sc_out< sc_lv<40> > output_k_0_V_d0;


    // Module declarations
    apply_rotary_pos_emb(sc_module_name name);
    SC_HAS_PROCESS(apply_rotary_pos_emb);

    ~apply_rotary_pos_emb();

    sc_trace_file* mVcdFile;

    apply_rotary_pos_g8j* cos_tab_V_5_U;
    apply_rotary_pos_hbi* sin_tab_V_5_U;
    apply_rotary_pos_ibs* rotated_q_0_V_U;
    apply_rotary_pos_ibs* rotated_k_0_V_U;
    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<7> > cos_tab_V_5_address0;
    sc_signal< sc_logic > cos_tab_V_5_ce0;
    sc_signal< sc_lv<17> > cos_tab_V_5_q0;
    sc_signal< sc_lv<7> > sin_tab_V_5_address0;
    sc_signal< sc_logic > sin_tab_V_5_ce0;
    sc_signal< sc_lv<17> > sin_tab_V_5_q0;
    sc_signal< sc_lv<2> > i_fu_312_p2;
    sc_signal< sc_lv<2> > i_reg_558;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<6> > sub_ln1265_fu_338_p2;
    sc_signal< sc_lv<6> > sub_ln1265_reg_563;
    sc_signal< sc_lv<1> > icmp_ln209_fu_306_p2;
    sc_signal< sc_lv<3> > add_ln211_fu_354_p2;
    sc_signal< sc_lv<3> > add_ln211_reg_572;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > sext_ln203_fu_369_p1;
    sc_signal< sc_lv<64> > sext_ln203_reg_577;
    sc_signal< sc_lv<1> > icmp_ln211_fu_348_p2;
    sc_signal< sc_lv<64> > sext_ln1265_fu_390_p1;
    sc_signal< sc_lv<64> > sext_ln1265_reg_593;
    sc_signal< sc_lv<2> > i_2_fu_416_p2;
    sc_signal< sc_lv<2> > i_2_reg_612;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<6> > sub_ln1116_fu_442_p2;
    sc_signal< sc_lv<6> > sub_ln1116_reg_617;
    sc_signal< sc_lv<1> > icmp_ln221_fu_410_p2;
    sc_signal< sc_lv<4> > add_ln223_fu_454_p2;
    sc_signal< sc_lv<4> > add_ln223_reg_625;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<64> > sext_ln1116_fu_475_p1;
    sc_signal< sc_lv<64> > sext_ln1116_reg_630;
    sc_signal< sc_lv<1> > icmp_ln223_fu_448_p2;
    sc_signal< sc_lv<17> > cos_tab_V_5_load_reg_666;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<40> > input_q_0_V_load_2_reg_671;
    sc_signal< sc_lv<17> > sin_tab_V_5_load_reg_676;
    sc_signal< sc_lv<40> > rotated_q_0_V_q0;
    sc_signal< sc_lv<40> > rotated_q_0_V_load_reg_681;
    sc_signal< sc_lv<40> > input_k_0_V_load_2_reg_686;
    sc_signal< sc_lv<40> > rotated_k_0_V_q0;
    sc_signal< sc_lv<40> > rotated_k_0_V_load_reg_691;
    sc_signal< sc_lv<56> > mul_ln1118_fu_489_p2;
    sc_signal< sc_lv<56> > mul_ln1118_reg_696;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<56> > mul_ln1118_4_fu_501_p2;
    sc_signal< sc_lv<56> > mul_ln1118_4_reg_701;
    sc_signal< sc_lv<56> > mul_ln1118_5_fu_510_p2;
    sc_signal< sc_lv<56> > mul_ln1118_5_reg_706;
    sc_signal< sc_lv<56> > mul_ln1118_6_fu_519_p2;
    sc_signal< sc_lv<56> > mul_ln1118_6_reg_711;
    sc_signal< sc_lv<5> > rotated_q_0_V_address0;
    sc_signal< sc_logic > rotated_q_0_V_ce0;
    sc_signal< sc_logic > rotated_q_0_V_we0;
    sc_signal< sc_lv<40> > rotated_q_0_V_d0;
    sc_signal< sc_lv<5> > rotated_q_0_V_address1;
    sc_signal< sc_logic > rotated_q_0_V_ce1;
    sc_signal< sc_logic > rotated_q_0_V_we1;
    sc_signal< sc_lv<5> > rotated_k_0_V_address0;
    sc_signal< sc_logic > rotated_k_0_V_ce0;
    sc_signal< sc_logic > rotated_k_0_V_we0;
    sc_signal< sc_lv<40> > rotated_k_0_V_d0;
    sc_signal< sc_lv<5> > rotated_k_0_V_address1;
    sc_signal< sc_logic > rotated_k_0_V_ce1;
    sc_signal< sc_logic > rotated_k_0_V_we1;
    sc_signal< sc_lv<2> > i_0_reg_262;
    sc_signal< sc_lv<3> > k_0_0_reg_273;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<2> > i14_0_reg_284;
    sc_signal< sc_lv<4> > k16_0_0_reg_295;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<64> > zext_ln224_fu_460_p1;
    sc_signal< sc_lv<4> > tmp_72_fu_326_p3;
    sc_signal< sc_lv<6> > tmp_71_fu_318_p3;
    sc_signal< sc_lv<6> > zext_ln1265_fu_334_p1;
    sc_signal< sc_lv<6> > zext_ln203_fu_360_p1;
    sc_signal< sc_lv<6> > add_ln203_fu_364_p2;
    sc_signal< sc_lv<4> > zext_ln211_fu_344_p1;
    sc_signal< sc_lv<4> > add_ln212_fu_375_p2;
    sc_signal< sc_lv<6> > zext_ln1265_3_fu_381_p1;
    sc_signal< sc_lv<6> > add_ln1265_fu_385_p2;
    sc_signal< sc_lv<4> > tmp_74_fu_430_p3;
    sc_signal< sc_lv<6> > tmp_73_fu_422_p3;
    sc_signal< sc_lv<6> > zext_ln1116_fu_438_p1;
    sc_signal< sc_lv<6> > zext_ln1116_2_fu_466_p1;
    sc_signal< sc_lv<6> > add_ln1116_fu_470_p2;
    sc_signal< sc_lv<17> > mul_ln1118_fu_489_p0;
    sc_signal< sc_lv<56> > sext_ln1118_5_fu_486_p1;
    sc_signal< sc_lv<40> > mul_ln1118_fu_489_p1;
    sc_signal< sc_lv<17> > mul_ln1118_4_fu_501_p0;
    sc_signal< sc_lv<56> > sext_ln1118_7_fu_498_p1;
    sc_signal< sc_lv<40> > mul_ln1118_4_fu_501_p1;
    sc_signal< sc_lv<17> > mul_ln1118_5_fu_510_p0;
    sc_signal< sc_lv<40> > mul_ln1118_5_fu_510_p1;
    sc_signal< sc_lv<17> > mul_ln1118_6_fu_519_p0;
    sc_signal< sc_lv<40> > mul_ln1118_6_fu_519_p1;
    sc_signal< sc_lv<56> > add_ln1192_fu_525_p2;
    sc_signal< sc_lv<56> > add_ln1192_1_fu_540_p2;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_state4;
    static const sc_lv<9> ap_ST_fsm_state5;
    static const sc_lv<9> ap_ST_fsm_state6;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<3> ap_const_lv3_6;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<40> ap_const_lv40_0;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_37;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln1116_fu_470_p2();
    void thread_add_ln1192_1_fu_540_p2();
    void thread_add_ln1192_fu_525_p2();
    void thread_add_ln1265_fu_385_p2();
    void thread_add_ln203_fu_364_p2();
    void thread_add_ln211_fu_354_p2();
    void thread_add_ln212_fu_375_p2();
    void thread_add_ln223_fu_454_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_cos_tab_V_5_address0();
    void thread_cos_tab_V_5_ce0();
    void thread_i_2_fu_416_p2();
    void thread_i_fu_312_p2();
    void thread_icmp_ln209_fu_306_p2();
    void thread_icmp_ln211_fu_348_p2();
    void thread_icmp_ln221_fu_410_p2();
    void thread_icmp_ln223_fu_448_p2();
    void thread_input_k_0_V_address0();
    void thread_input_k_0_V_address1();
    void thread_input_k_0_V_ce0();
    void thread_input_k_0_V_ce1();
    void thread_input_q_0_V_address0();
    void thread_input_q_0_V_address1();
    void thread_input_q_0_V_ce0();
    void thread_input_q_0_V_ce1();
    void thread_mul_ln1118_4_fu_501_p0();
    void thread_mul_ln1118_4_fu_501_p1();
    void thread_mul_ln1118_4_fu_501_p2();
    void thread_mul_ln1118_5_fu_510_p0();
    void thread_mul_ln1118_5_fu_510_p1();
    void thread_mul_ln1118_5_fu_510_p2();
    void thread_mul_ln1118_6_fu_519_p0();
    void thread_mul_ln1118_6_fu_519_p1();
    void thread_mul_ln1118_6_fu_519_p2();
    void thread_mul_ln1118_fu_489_p0();
    void thread_mul_ln1118_fu_489_p1();
    void thread_mul_ln1118_fu_489_p2();
    void thread_output_k_0_V_address0();
    void thread_output_k_0_V_ce0();
    void thread_output_k_0_V_d0();
    void thread_output_k_0_V_we0();
    void thread_output_q_0_V_address0();
    void thread_output_q_0_V_ce0();
    void thread_output_q_0_V_d0();
    void thread_output_q_0_V_we0();
    void thread_rotated_k_0_V_address0();
    void thread_rotated_k_0_V_address1();
    void thread_rotated_k_0_V_ce0();
    void thread_rotated_k_0_V_ce1();
    void thread_rotated_k_0_V_d0();
    void thread_rotated_k_0_V_we0();
    void thread_rotated_k_0_V_we1();
    void thread_rotated_q_0_V_address0();
    void thread_rotated_q_0_V_address1();
    void thread_rotated_q_0_V_ce0();
    void thread_rotated_q_0_V_ce1();
    void thread_rotated_q_0_V_d0();
    void thread_rotated_q_0_V_we0();
    void thread_rotated_q_0_V_we1();
    void thread_sext_ln1116_fu_475_p1();
    void thread_sext_ln1118_5_fu_486_p1();
    void thread_sext_ln1118_7_fu_498_p1();
    void thread_sext_ln1265_fu_390_p1();
    void thread_sext_ln203_fu_369_p1();
    void thread_sin_tab_V_5_address0();
    void thread_sin_tab_V_5_ce0();
    void thread_sub_ln1116_fu_442_p2();
    void thread_sub_ln1265_fu_338_p2();
    void thread_tmp_71_fu_318_p3();
    void thread_tmp_72_fu_326_p3();
    void thread_tmp_73_fu_422_p3();
    void thread_tmp_74_fu_430_p3();
    void thread_zext_ln1116_2_fu_466_p1();
    void thread_zext_ln1116_fu_438_p1();
    void thread_zext_ln1265_3_fu_381_p1();
    void thread_zext_ln1265_fu_334_p1();
    void thread_zext_ln203_fu_360_p1();
    void thread_zext_ln211_fu_344_p1();
    void thread_zext_ln224_fu_460_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
