
# Loop constraints
directive set /dut/core/core:rlp CSTEPS_FROM {{. == 0}}
directive set /dut/core/core:rlp/main CSTEPS_FROM {{. == 111} {.. == 0}}
directive set /dut/core/core:rlp/main/for:for CSTEPS_FROM {{. == 3} {.. == 1}}
directive set /dut/core/core:rlp/main/compute_sqrt:for CSTEPS_FROM {{. == 16} {.. == 7}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2 CSTEPS_FROM {{. == 6} {.. == 39}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4 CSTEPS_FROM {{. == 1} {.. == 0}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5 CSTEPS_FROM {{. == 6} {.. == 0}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit CSTEPS_FROM {{. == 2} {.. == 54}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2 CSTEPS_FROM {{. == 66} {.. == 54}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3 CSTEPS_FROM {{. == 1} {.. == 0}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4 CSTEPS_FROM {{. == 2} {.. == 0}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5 CSTEPS_FROM {{. == 6} {.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3 CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2 CSTEPS_FROM {{. == 4} {.. == 0}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6 CSTEPS_FROM {{. == 5} {.. == 0}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2 CSTEPS_FROM {{. == 1} {.. == 0}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3 CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2 CSTEPS_FROM {{. == 1} {.. == 0}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3 CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3 CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4 CSTEPS_FROM {{. == 5} {.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3 CSTEPS_FROM {{. == 13} {.. == 0}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1 CSTEPS_FROM {{. == 3} {.. == 54}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3 CSTEPS_FROM {{. == 2} {.. == 2}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4 CSTEPS_FROM {{. == 5} {.. == 2}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5 CSTEPS_FROM {{. == 22} {.. == 2}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1 CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1 CSTEPS_FROM {{. == 5} {.. == 2}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2 CSTEPS_FROM {{. == 1} {.. == 54}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3 CSTEPS_FROM {{. == 3} {.. == 0}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_1#2 CSTEPS_FROM {{. == 4} {.. == 54}}
directive set /dut/core/core:rlp/main/compute_sqrt#1:for CSTEPS_FROM {{. == 16} {.. == 60}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2 CSTEPS_FROM {{. == 6} {.. == 79}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1 CSTEPS_FROM {{. == 1} {.. == 111}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1 CSTEPS_FROM {{. == 1} {.. == 0}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1 CSTEPS_FROM {{. == 6} {.. == 0}}
directive set /dut/core/core:rlp/main/output:vinit CSTEPS_FROM {{. == 2} {.. == 111}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3 CSTEPS_FROM {{. == 34} {.. == 111}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3 CSTEPS_FROM {{. == 1} {.. == 0}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3 CSTEPS_FROM {{. == 2} {.. == 0}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3 CSTEPS_FROM {{. == 4} {.. == 1}}
directive set /dut/core/core:rlp/main/for#1:for CSTEPS_FROM {{. == 3} {.. == 111}}

# IO operation constraints
directive set /dut/core/core:rlp/main/for:for/for:for:io_read(strm_in) CSTEPS_FROM {{.. == 0}}
directive set /dut/core/core:rlp/main/for#1:for/for#1:for:io_write(strm_out) CSTEPS_FROM {{.. == 2}}

# Sync operation constraints

# Real operation constraints
directive set /dut/core/core:rlp/main/for:for/for:for:write_mem(input:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for:for/for:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for:for/RMS_NORM_LOOP_1#1:RMS_NORM_LOOP_1#1:mul CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/for:for/RMS_NORM_LOOP_1#1:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/for:for/RMS_NORM_LOOP_1#1:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for:for/for:for:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for:for/RMS_NORM_LOOP_1#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#5 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#12 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#17 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#11 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#10 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#16 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#19 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#9 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#8 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#15 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#7 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#6 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#14 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#18 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#20 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#21 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#22 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#23 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#26 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#28 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#30 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#32 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#34 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#36 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#38 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#40 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#42 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#44 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#46 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#48 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#50 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#52 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#24 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#25 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#27 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#29 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#31 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#33 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#35 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#37 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#39 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#41 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#43 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#45 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#47 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#49 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#51 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>:acc#53 CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/rms_norm<384>:val:acc CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/attention_abs:qif:acc CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/attention_abs:mux CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/compute_sqrt:for/operator_<40,24,true,AC_TRN,AC_WRAP>#1:div CSTEPS_FROM {{.. == 0}}
directive set /dut/core/core:rlp/main/compute_sqrt:for/compute_sqrt:for:guess_inv:mul CSTEPS_FROM {{.. == 15}}
directive set /dut/core/core:rlp/main/compute_sqrt:for/compute_sqrt:for:acc#1 CSTEPS_FROM {{.. == 16}}
directive set /dut/core/core:rlp/main/compute_sqrt:for/compute_sqrt:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/compute_sqrt:for/compute_sqrt:for:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/rms_norm<384>:div CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:read_mem(input:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:read_rom(ln_weight_in.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:mul#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:mul CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:write_mem(input:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/QUANTIZE_ACTIVATION_LOOP_1:max_val:read_mem(input:rsc.@)#2 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/attention_abs#1:qif:acc CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/attention_abs#2:qif:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/attention_abs#2:mux CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/QUANTIZE_ACTIVATION_LOOP_2:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/attention_abs#3:qif:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/QUANTIZE_ACTIVATION_LOOP_2:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/QUANTIZE_ACTIVATION_LOOP_2:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:RMS_NORM_LOOP_2:mux1h CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:RMS_NORM_LOOP_2:mux1h#1 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2/RMS_NORM_LOOP_2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention_max<attn_fixed_t>:acc CSTEPS_FROM {{.. == 40}}
directive set /dut/core/core:rlp/main/attention_max<attn_fixed_t>:attention_max<attn_fixed_t>:and CSTEPS_FROM {{.. == 40}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_1:scale:div CSTEPS_FROM {{.. == 40}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:quant_val:read_mem(input:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:quant_val:mul#1 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/attention_round:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/attention_round:qif:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/attention_round:qelse:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/attention_round:mux CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:qelse:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:nor CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:quantized_value_clamped:mux1h CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:write_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_5/QUANTIZE_ACTIVATION_LOOP_5:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_4/QUANTIZE_ACTIVATION_LOOP_4:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3/QUANTIZE_ACTIVATION_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit/INIT_2D_MEM_LOOP_2:write_mem(attention<5,1,384,384,8,48>:q_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit/INIT_2D_MEM_LOOP_2#1:write_mem(attention<5,1,384,384,8,48>:k_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit/INIT_2D_MEM_LOOP_2#2:write_mem(attention<5,1,384,384,8,48>:v_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit/INIT_2D_MEM_LOOP_2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit/INIT_2D_MEM_LOOP_2#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention<5,1,384,384,8,48>:q_proj_re:vinit/INIT_2D_MEM_LOOP_2#2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4:packed_val:read_rom(q_weights.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val:read_rom(k_weights.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val:read_rom(v_weights.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:weight_val:mux CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:if:read_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:else:if:read_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:else:if:acc#2 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:read_mem(attention<5,1,384,384,8,48>:q_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:mux CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:LINEAR_FORWARD_NO_MUL_LOOP_5:and CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:write_mem(attention<5,1,384,384,8,48>:q_proj_re:rsc.@) CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:mux CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:if:read_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:else:if:read_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:else:if:acc#2 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:read_mem(attention<5,1,384,384,8,48>:k_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:mux CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:LINEAR_FORWARD_NO_MUL_LOOP_5#1:and CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:write_mem(attention<5,1,384,384,8,48>:k_proj_re:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#1:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:mux CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:if:read_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:else:if:read_mem(attention<5,1,384,384,8,48>:quantized_hidden_states:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:else:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:read_mem(attention<5,1,384,384,8,48>:v_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:mux CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:LINEAR_FORWARD_NO_MUL_LOOP_5#2:and CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:write_mem(attention<5,1,384,384,8,48>:v_proj_re:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_5/LINEAR_FORWARD_NO_MUL_LOOP_5#2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#1:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_4/LINEAR_FORWARD_NO_MUL_LOOP_4#2:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_3#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_3#2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_3#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_3/LINEAR_FORWARD_NO_MUL_LOOP_3#2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2:read_mem(attention<5,1,384,384,8,48>:q_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2:LINEAR_FORWARD_NO_MUL_LOOP_2:div#1 CSTEPS_FROM {{.. == 33}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2:write_mem(attention<5,1,384,384,8,48>:q_proj_re:rsc.@) CSTEPS_FROM {{.. == 65}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#1:read_mem(attention<5,1,384,384,8,48>:k_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#1:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#1:LINEAR_FORWARD_NO_MUL_LOOP_2#1:div#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#1:write_mem(attention<5,1,384,384,8,48>:k_proj_re:rsc.@) CSTEPS_FROM {{.. == 34}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#2:read_mem(attention<5,1,384,384,8,48>:v_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#2:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#2:LINEAR_FORWARD_NO_MUL_LOOP_2#2:div#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#2:write_mem(attention<5,1,384,384,8,48>:v_proj_re:rsc.@) CSTEPS_FROM {{.. == 33}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2/LINEAR_FORWARD_NO_MUL_LOOP_2#2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3:read_mem(attention<5,1,384,384,8,48>:q_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3:write_mem(attention<5,1,384,384,8,48>:q_proj:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3#1:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3#1:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3#1:read_mem(attention<5,1,384,384,8,48>:k_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3#1:write_mem(attention<5,1,384,384,8,48>:k_proj:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3#1:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_3/RESHAPE_2D_TO_3D_LOOP_3#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2/RESHAPE_2D_TO_3D_LOOP_2#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:read_mem(attention<5,1,384,384,8,48>:v_proj_re:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:write_mem(attention<5,1,384,384,8,48>:v_proj:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#30 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#44 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#36 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#37 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:read_mem(attention<5,1,384,384,8,48>:q_proj:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#6 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:write_mem(apply_rotary_pos_emb<1,8,48>:rotated_q:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:read_mem(attention<5,1,384,384,8,48>:k_proj:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#12 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:write_mem(apply_rotary_pos_emb<1,8,48>:rotated_k:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:read_mem(attention<5,1,384,384,8,48>:q_proj:rsc.@)#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:write_mem(apply_rotary_pos_emb<1,8,48>:rotated_q:rsc.@)#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:read_mem(attention<5,1,384,384,8,48>:k_proj:rsc.@)#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:write_mem(apply_rotary_pos_emb<1,8,48>:rotated_k:rsc.@)#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/APPLY_ROTARY_POS_EMB_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_3#2/RESHAPE_2D_TO_3D_LOOP_3#2:mux#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/RESHAPE_2D_TO_3D_LOOP_2#2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RESHAPE_2D_TO_3D_LOOP_2#2/APPLY_ROTARY_POS_EMB_LOOP_1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:sinval:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:sinval:read_rom(sin_tab.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:cosval:read_rom(cos_tab.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:acc#28 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:acc#23 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:read_mem(attention<5,1,384,384,8,48>:q_proj:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:mul#3 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:read_mem(apply_rotary_pos_emb<1,8,48>:rotated_q:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:mul#4 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:acc#7 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:write_mem(attention<5,1,384,384,8,48>:q_embed:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:read_mem(attention<5,1,384,384,8,48>:k_proj:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:mul#8 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:read_mem(apply_rotary_pos_emb<1,8,48>:rotated_k:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:mul#9 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:acc#14 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:write_mem(attention<5,1,384,384,8,48>:k_embed:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_6/APPLY_ROTARY_POS_EMB_LOOP_6:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/APPLY_ROTARY_POS_EMB_LOOP_4/APPLY_ROTARY_POS_EMB_LOOP_4:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:read_mem(attention<5,1,384,384,8,48>:k_embed:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:qif:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:qif:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:qif:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:qif:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:qif:read_rom(k_cache.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:mux CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:write_mem(attention<5,1,384,384,8,48>:k_cache_upd:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:read_mem(attention<5,1,384,384,8,48>:v_proj:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:qif:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:qif:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:qif:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:qif:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:qif:read_rom(v_cache.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:mux CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#9 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:write_mem(attention<5,1,384,384,8,48>:v_cache_upd:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_3/CACHE_UPDATE_LOOP_3#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_2#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_2/CACHE_UPDATE_LOOP_2#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/CACHE_UPDATE_LOOP_1/CACHE_UPDATE_LOOP_1#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#10 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:read_mem(attention<5,1,384,384,8,48>:k_cache_upd:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#11 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:write_mem(attention<5,1,384,384,8,48>:k_proj_transposed:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_3/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_2/TRANSPOSE_LAST_TWO_DIMS_LOOP_2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/TRANSPOSE_LAST_TWO_DIMS_LOOP_1/TRANSPOSE_LAST_TWO_DIMS_LOOP_1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_3:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_3:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_3:write_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:read_mem(attention<5,1,384,384,8,48>:q_embed:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:read_mem(attention<5,1,384,384,8,48>:k_proj_transposed:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:write_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_4/GEMM_3D_FLOAT_LOOP_4:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_3:acc#3 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_3/GEMM_3D_FLOAT_LOOP_3:acc CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1/GEMM_3D_FLOAT_LOOP_1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#9 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#17 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#10 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#11 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#16 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#25 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#13 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#14 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#15 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#17 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#24 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#29 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#18 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#16 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#14 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#23 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#13 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#12 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#22 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#28 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#31 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#8 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#11 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#12 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#15 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#10 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#21 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#9 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#20 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#27 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#19 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#18 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#26 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#30 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#5 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#19 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#32 CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#34 CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#33 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#6 CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#35 CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#7 CSTEPS_FROM {{.. == 8}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#20 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#56 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#6 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#51 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#45 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#43 CSTEPS_FROM {{.. == 8}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#7 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#36 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#37 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#38 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#39 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#40 CSTEPS_FROM {{.. == 7}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#41 CSTEPS_FROM {{.. == 8}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#1 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#42 CSTEPS_FROM {{.. == 8}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#44 CSTEPS_FROM {{.. == 8}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#46 CSTEPS_FROM {{.. == 8}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#2 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#47 CSTEPS_FROM {{.. == 9}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#48 CSTEPS_FROM {{.. == 9}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#3 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#49 CSTEPS_FROM {{.. == 9}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#4 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#50 CSTEPS_FROM {{.. == 9}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#52 CSTEPS_FROM {{.. == 10}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#53 CSTEPS_FROM {{.. == 10}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#54 CSTEPS_FROM {{.. == 10}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:mul#5 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#55 CSTEPS_FROM {{.. == 11}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#57 CSTEPS_FROM {{.. == 11}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#58 CSTEPS_FROM {{.. == 11}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:SF_LOOP_3:SF_LOOP_3:acc CSTEPS_FROM {{.. == 12}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:write_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 12}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_3/SF_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SF_LOOP_1/SF_LOOP_1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_2:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:if:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:if:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:if:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:acc#3 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:mux CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_3/SOFTMAX_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:x:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:x:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:x:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:x:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:sqr CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/operator+<40,24,true,AC_TRN,AC_WRAP>:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:acc#3 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:write_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:acc#6 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_4/SOFTMAX_LOOP_4:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:acc#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:SOFTMAX_LOOP_5:div#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:write_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 21}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_5/SOFTMAX_LOOP_5:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/SOFTMAX_LOOP_1/SOFTMAX_LOOP_1:acc#1 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_3#1:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_3#1:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_3#1:write_mem(attention<5,1,384,384,8,48>:attn_output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:read_mem(attention<5,1,384,384,8,48>:attn_output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#14 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#13 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:read_mem(attention<5,1,384,384,8,48>:attn_weights:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#16 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#15 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#17 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:read_mem(attention<5,1,384,384,8,48>:v_cache_upd:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:mul CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:write_mem(attention<5,1,384,384,8,48>:attn_output:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_4#1/GEMM_3D_FLOAT_LOOP_4#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_3#1:acc#3 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_3#1/GEMM_3D_FLOAT_LOOP_3#1:acc CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/GEMM_3D_FLOAT_LOOP_1#1/GEMM_3D_FLOAT_LOOP_1#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3/ATTN_2D_LOOP_3:acc#12 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3/ATTN_2D_LOOP_3:acc#8 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3/ATTN_2D_LOOP_3:read_mem(attention<5,1,384,384,8,48>:attn_output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3/ATTN_2D_LOOP_3:write_mem(attention<5,1,384,384,8,48>:attn_output_2D:rsc.@) CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3/ATTN_2D_LOOP_3:acc#7 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_3/ATTN_2D_LOOP_3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/ATTN_2D_LOOP_2/ATTN_2D_LOOP_2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_1#2/RMS_NORM_LOOP_1#2:read_mem(attention<5,1,384,384,8,48>:attn_output_2D:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_1#2/RMS_NORM_LOOP_1#2:RMS_NORM_LOOP_1#2:mul CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_1#2/RMS_NORM_LOOP_1#2:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_1#2/RMS_NORM_LOOP_1#2:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_1#2/RMS_NORM_LOOP_1#2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#5 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#13 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#12 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#17 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#11 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#10 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#16 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#19 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#9 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#8 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#15 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#7 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#6 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#14 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#18 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#20 CSTEPS_FROM {{.. == 55}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#21 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#22 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#23 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#26 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#28 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#30 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#32 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#34 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#36 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#38 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#40 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#42 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#44 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#46 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#48 CSTEPS_FROM {{.. == 59}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#50 CSTEPS_FROM {{.. == 59}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#52 CSTEPS_FROM {{.. == 59}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#24 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#25 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#27 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#29 CSTEPS_FROM {{.. == 56}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#31 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#33 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#35 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#37 CSTEPS_FROM {{.. == 57}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#39 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#41 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#43 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#45 CSTEPS_FROM {{.. == 58}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#47 CSTEPS_FROM {{.. == 59}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#49 CSTEPS_FROM {{.. == 59}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#51 CSTEPS_FROM {{.. == 59}}
directive set /dut/core/core:rlp/main/operator_<40,24,true,AC_TRN,AC_WRAP>#2:acc#53 CSTEPS_FROM {{.. == 60}}
directive set /dut/core/core:rlp/main/rms_norm<384>#1:val:acc CSTEPS_FROM {{.. == 60}}
directive set /dut/core/core:rlp/main/attention_abs#4:qif:acc CSTEPS_FROM {{.. == 60}}
directive set /dut/core/core:rlp/main/attention_abs#4:mux CSTEPS_FROM {{.. == 60}}
directive set /dut/core/core:rlp/main/compute_sqrt#1:for/operator_<40,24,true,AC_TRN,AC_WRAP>#3:div CSTEPS_FROM {{.. == 0}}
directive set /dut/core/core:rlp/main/compute_sqrt#1:for/compute_sqrt#1:for:guess_inv:mul CSTEPS_FROM {{.. == 15}}
directive set /dut/core/core:rlp/main/compute_sqrt#1:for/compute_sqrt#1:for:acc#1 CSTEPS_FROM {{.. == 16}}
directive set /dut/core/core:rlp/main/compute_sqrt#1:for/compute_sqrt#1:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/compute_sqrt#1:for/compute_sqrt#1:for:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/rms_norm<384>#1:div CSTEPS_FROM {{.. == 60}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:read_mem(attention<5,1,384,384,8,48>:attn_output_2D:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:read_rom(ln_weight.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:mul#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:mul CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:write_mem(attention<5,1,384,384,8,48>:attn_output_2D:rsc.@) CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/QUANTIZE_ACTIVATION_LOOP_1#1:max_val:read_mem(attention<5,1,384,384,8,48>:attn_output_2D:rsc.@)#2 CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/attention_abs#5:qif:acc CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/attention_abs#6:qif:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/attention_abs#6:mux CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/QUANTIZE_ACTIVATION_LOOP_2#1:acc#4 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/attention_abs#7:qif:acc#1 CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/QUANTIZE_ACTIVATION_LOOP_2#1:acc#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/QUANTIZE_ACTIVATION_LOOP_2#1:acc#6 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:RMS_NORM_LOOP_2#2:mux1h CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:RMS_NORM_LOOP_2#2:mux1h#1 CSTEPS_FROM {{.. == 6}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:mux#5 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:mux#4 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/RMS_NORM_LOOP_2#2/RMS_NORM_LOOP_2#2:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/attention_max<attn_fixed_t>#1:acc CSTEPS_FROM {{.. == 80}}
directive set /dut/core/core:rlp/main/attention_max<attn_fixed_t>#1:attention_max<attn_fixed_t>#1:and CSTEPS_FROM {{.. == 80}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_1#1:scale:div CSTEPS_FROM {{.. == 80}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:quant_val:read_mem(attention<5,1,384,384,8,48>:attn_output_2D:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:quant_val:mul#1 CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/attention_round#1:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/attention_round#1:qif:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/attention_round#1:qelse:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/attention_round#1:mux CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:qelse:acc CSTEPS_FROM {{.. == 4}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:nor CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:quantized_value_clamped:mux1h CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:write_mem(attention<5,1,384,384,8,48>:quantized_final_output:rsc.@) CSTEPS_FROM {{.. == 5}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_5#1/QUANTIZE_ACTIVATION_LOOP_5#1:acc#3 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_4#1/QUANTIZE_ACTIVATION_LOOP_4#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_3#1:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/QUANTIZE_ACTIVATION_LOOP_3#1/QUANTIZE_ACTIVATION_LOOP_3#1:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/output:vinit/INIT_2D_MEM_LOOP_2#3:write_mem(output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/output:vinit/INIT_2D_MEM_LOOP_2#3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val:read_rom(o_weights.rom_map_1) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:weight_val:mux CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:if:read_mem(attention<5,1,384,384,8,48>:quantized_final_output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:else:if:read_mem(attention<5,1,384,384,8,48>:quantized_final_output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:else:if:acc#2 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#3:read_mem(output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:mux CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:LINEAR_FORWARD_NO_MUL_LOOP_5#3:and CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#3:acc CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#3:write_mem(output:rsc.@) CSTEPS_FROM {{.. == 3}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3/LINEAR_FORWARD_NO_MUL_LOOP_5#3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3/LINEAR_FORWARD_NO_MUL_LOOP_4#3:acc#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3:acc#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3/LINEAR_FORWARD_NO_MUL_LOOP_3#3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_2#3:read_mem(output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_2#3:mul#1 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_2#3:LINEAR_FORWARD_NO_MUL_LOOP_2#3:div#1 CSTEPS_FROM {{.. == 2}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_2#3:write_mem(output:rsc.@) CSTEPS_FROM {{.. == 33}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/LINEAR_FORWARD_NO_MUL_LOOP_2#3/LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for#1:for/for#1:for:read_mem(output:rsc.@) CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for#1:for/for#1:for:acc#2 CSTEPS_FROM {{.. == 1}}
directive set /dut/core/core:rlp/main/for#1:for/for#1:for:acc CSTEPS_FROM {{.. == 1}}

# Probe constraints
