directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/operator_<40,24,true,AC_TRN,AC_WRAP>#3:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/SF_LOOP_3:mul#16.itm REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:cosval:slc(cos_tab,*40)(39-0).psp.sva REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2:acc.itm REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/attention<5,1,384,384,8,48>:q_proj_re:vinit.ndx.sva REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:j(8:0).sva REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#1:i(8:0).sva REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:i(8:0).sva REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#1:i(8:0).sva#1 REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:i(8:0).sva#1 REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:acc#3.itm REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:acc#3.itm REGISTER_NAME operator_<40,24,true,AC_TRN,AC_WRAP>#1:slc(operator_<40,24,true,AC_TRN,AC_WRAP>#1:div:cmp.z)(17-0).itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#2:acc.itm REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/attention<5,1,384,384,8,48>:v_proj_re:vinit.ndx.sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:j(8:0).sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:j(8:0).sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:i(8:0).sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:i(8:0).sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/for:for:j(8:0).sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/for:for:j(8:0).sva#1 REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#82.psp REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#17.sdt REGISTER_NAME INIT_2D_MEM_LOOP_2#2:acc.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4:ki(4:0).sva(3:0) REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:ki(4:0).sva(3:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:acc#10.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:ki(4:0).sva(3:0)
directive set /dut/dut:core/core/SF_LOOP_3:acc#8.sdt REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_4:ki(4:0).sva(3:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:slc(LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val,LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:conc#1*1)(1-0).svs REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:slc(LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val,LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:conc#1*1)(1-0).svs
directive set /dut/dut:core/core/SF_LOOP_3:acc#90.psp REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:slc(LINEAR_FORWARD_NO_MUL_LOOP_4#2:packed_val,LINEAR_FORWARD_NO_MUL_LOOP_5#2:weight_val:conc#1*1)(1-0).svs
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:or.itm REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5:or.itm
directive set /dut/dut:core/core/exit:APPLY_ROTARY_POS_EMB_LOOP_3.sva REGISTER_NAME LINEAR_FORWARD_NO_MUL_LOOP_5:or.itm
directive set /dut/dut:core/core/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#2:acc.itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#3:acc.itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:acc.itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:sinval:slc(sin_tab,*40)(39-0).psp.sva REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:read_rom(ln_weight.rom_map_1).itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:read_rom(ln_weight_in.rom_map_1).itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#2:j(8:0).sva#1 REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#22.itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#24.itm REGISTER_NAME operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:acc.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#2:asn.psp REGISTER_NAME INIT_2D_MEM_LOOP_2#2:asn.psp
directive set /dut/dut:core/core/drf(output).sdt#2.sva REGISTER_NAME INIT_2D_MEM_LOOP_2#2:asn.psp
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:asn.itm REGISTER_NAME INIT_2D_MEM_LOOP_2#2:asn.psp
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#1:asn.psp REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#3:asn.psp REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/drf(output).sdt#1.sva REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/drf(output).sdt#3.sva REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:asn#2.itm REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:asn.itm#1 REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:asn.itm#1 REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/softmax<1,8,6>:max_val.sva REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/softmax<1,8,6>:max_val.sva.dfm REGISTER_NAME INIT_2D_MEM_LOOP_2#1:asn.psp
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:acc#11.psp REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3:acc#11.psp
directive set /dut/dut:core/core/SF_LOOP_3:acc#92.psp REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3:acc#11.psp
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_4:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/ATTN_2D_LOOP_2:h(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_2:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SOFTMAX_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#3:l(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5#1:k(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5:k(2:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SF_LOOP_3:acc#61.cse REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:acc#17.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/SF_LOOP_3:acc#80.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:l(2:0).sva(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#36.cse.sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:acc#17.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/SF_LOOP_3:acc#84.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_3:acc#37.cse.sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:qif:acc#3.ncse(2:0) REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:l(2:0).sva#1 REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#69.psp REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#91.psp REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:k(2:0).sva#1 REGISTER_NAME RESHAPE_2D_TO_3D_LOOP_3#2:mux#3.itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:d(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:k(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:l(5:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:l(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/SF_LOOP_3:acc#88.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:slc(ATTN_2D_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:slc(GEMM_3D_FLOAT_LOOP_4#1:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:slc(GEMM_3D_FLOAT_LOOP_4:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:slc(LINEAR_FORWARD_NO_MUL_LOOP_2#3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:slc(RMS_NORM_LOOP_1#2:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:slc(RMS_NORM_LOOP_2#2:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:slc(RMS_NORM_LOOP_2:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SF_LOOP_3:slc(SF_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_3:slc(SOFTMAX_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:slc(SOFTMAX_LOOP_4:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:slc(SOFTMAX_LOOP_5:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:slc(TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/compute_sqrt#1:for:slc(compute_sqrt#1:for:acc)(3).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/compute_sqrt:for:slc(compute_sqrt:for:acc)(3).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/for#1:for:slc(for#1:for:acc)(2).itm REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:slc(APPLY_ROTARY_POS_EMB_LOOP_6:acc)(2).itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:acc#13.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:acc#7.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:acc#7.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#2:ki(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:acc#11.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:acc#11.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/SF_LOOP_3:acc#63.cse REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:x:acc.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:acc#6.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#29.psp
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:acc#12.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3#1:acc#6.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:acc#6.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#1:ki(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_4#3:ki(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_4#1:ji(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_4:ji(4:0).sva(3:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:acc#10.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:acc#10.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/SF_LOOP_3:acc#59.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:x:acc#4.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:acc#5.sdt REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#22.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/compute_sqrt#1:for:i(3:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/compute_sqrt#1:for:i(3:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/compute_sqrt:for:i(3:0).sva REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/compute_sqrt:for:i(3:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#28.sdt
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/ATTN_2D_LOOP_3:d(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3#1:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#1:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:k(5:0).sva#1 REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:l(2:0).sva(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#3:l(2:0).sva(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5#1:k(2:0).sva(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5:k(2:0).sva(1:0) REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/SF_LOOP_3:acc#70.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/SF_LOOP_3:acc#89.psp REGISTER_NAME APPLY_ROTARY_POS_EMB_LOOP_6:k(5:0).sva#1
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:k(5:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:k(5:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:k(5:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:k(5:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:k(4:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/SF_LOOP_3:acc#87.psp REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_2#1:j(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:k(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#2:ko(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SF_LOOP_3:d(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_5:k(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/TRANSPOSE_LAST_TWO_DIMS_LOOP_2:j(2:0).sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_3:acc#30.psp.sva REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:k(2:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_2#1:j(2:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2:and#1.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:LINEAR_FORWARD_NO_MUL_LOOP_2:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:or.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:LINEAR_FORWARD_NO_MUL_LOOP_5:and#1.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:and#1.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3#2:not.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:RESHAPE_2D_TO_3D_LOOP_3:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:unequal.tmp REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:unequal.tmp REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/for:for:for:for:nor.itm REGISTER_NAME CACHE_UPDATE_LOOP_3:CACHE_UPDATE_LOOP_3:nor.itm
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0) REGISTER_NAME CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5:l(2:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/SF_LOOP_3:acc#81.psp REGISTER_NAME CACHE_UPDATE_LOOP_3:qif:acc#3.ncse(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_3:k(5:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_3:k(5:0).sva#1 REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:slc(LINEAR_FORWARD_NO_MUL_LOOP_4#1:packed_val,LINEAR_FORWARD_NO_MUL_LOOP_5#1:weight_val:conc#1*1)(1-0).svs REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#3:weight_val:LINEAR_FORWARD_NO_MUL_LOOP_5#3:weight_val:slc(LINEAR_FORWARD_NO_MUL_LOOP_4#3:packed_val,LINEAR_FORWARD_NO_MUL_LOOP_5#3:weight_val:conc#1*1)(1-0).svs REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_5#2:l(2:0).sva(1:0) REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/SF_LOOP_3:acc#83.psp REGISTER_NAME CACHE_UPDATE_LOOP_3:k(5:0).sva#1
directive set /dut/dut:core/core/SF_LOOP_3:acc#26.itm REGISTER_NAME SF_LOOP_3:acc#26.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#1:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#26.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#3:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#26.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:i(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#26.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:i(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#26.itm
directive set /dut/dut:core/core/SF_LOOP_3:acc#17.itm REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/SF_LOOP_3:mul#18.itm REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:mux#4.itm REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:mux#4.itm REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_2#1:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_2:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2#2:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/for#1:for:j(8:0).sva REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/for#1:for:j(8:0).sva#1 REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/attention<5,1,384,384,8,48>:k_proj_re:vinit.ndx.sva REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/output:vinit.ndx.sva REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#1:acc.itm REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/INIT_2D_MEM_LOOP_2#3:acc.itm REGISTER_NAME SF_LOOP_3:acc#17.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_3:asn.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:asn#4.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:asn#4.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_1:scale.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/RMS_NORM_LOOP_1#2:slc(attention<5,1,384,384,8,48>:attn_output_2D,*40)(39-0).cse.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:x.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5#1:quant_val:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/RMS_NORM_LOOP_2:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:asn#1.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/SF_LOOP_3:slc(attention<5,1,384,384,8,48>:attn_weights,*40)(39-0).psp.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/attention_max<attn_fixed_t>#1:conc.psp REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/attention_max<attn_fixed_t>:attention_max<attn_fixed_t>:and.mut REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/compute_sqrt#1:guess.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/compute_sqrt:guess.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_3:asn.psp
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_2#1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/RESHAPE_2D_TO_3D_LOOP_2#2:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_1#1:i(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SF_LOOP_1:h(3:0).sva(2:0) REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SOFTMAX_LOOP_3:k(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/SOFTMAX_LOOP_3:k(2:0).sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3:ko(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_1#1:i(3:0).sva(2:0)
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#1:ko(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_3#3:ko(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/CACHE_UPDATE_LOOP_2:j(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_3#1:jo(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_3:jo(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/SOFTMAX_LOOP_4:k(2:0).sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/SF_LOOP_3:d(2:0).sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:l(2:0).sva
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4#1:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/GEMM_3D_FLOAT_LOOP_4:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/softmax<1,8,6>:sum.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/rms_norm<384>#1:variance#1.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/rms_norm<384>:variance#1.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/rms_norm<384>#1:variance#1.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/rms_norm<384>:variance#1.sva#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/rms_norm<384>#1:variance.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/rms_norm<384>:variance.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/QUANTIZE_ACTIVATION_LOOP_5:quant_val:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/APPLY_ROTARY_POS_EMB_LOOP_6:asn.itm#1 REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:asn.itm REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/drf(output).sdt.sva REGISTER_NAME GEMM_3D_FLOAT_LOOP_4#1:asn.itm
directive set /dut/dut:core/core/RMS_NORM_LOOP_2#2.dfr.sva REGISTER_NAME RMS_NORM_LOOP_2#2.dfr.sva
directive set /dut/dut:core/core/RMS_NORM_LOOP_2.dfr.sva REGISTER_NAME RMS_NORM_LOOP_2#2.dfr.sva
directive set /dut/dut:core/core/compute_sqrt#1:guess.sva(39:30) REGISTER_NAME RMS_NORM_LOOP_2#2.dfr.sva
directive set /dut/dut:core/core/compute_sqrt:guess.sva(39:30) REGISTER_NAME RMS_NORM_LOOP_2#2.dfr.sva
directive set /dut/dut:core/core/LINEAR_FORWARD_NO_MUL_LOOP_2:j(8:0).sva#1 REGISTER_NAME RMS_NORM_LOOP_2#2.dfr.sva
