// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "quantize_activation.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic quantize_activation::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic quantize_activation::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<43> quantize_activation::ap_ST_fsm_state1 = "1";
const sc_lv<43> quantize_activation::ap_ST_fsm_state2 = "10";
const sc_lv<43> quantize_activation::ap_ST_fsm_state3 = "100";
const sc_lv<43> quantize_activation::ap_ST_fsm_state4 = "1000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state5 = "10000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state6 = "100000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state7 = "1000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state8 = "10000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state9 = "100000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state10 = "1000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state11 = "10000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state12 = "100000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state32 = "10000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state33 = "100000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state34 = "1000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state35 = "10000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state36 = "100000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state37 = "1000000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state38 = "10000000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state39 = "100000000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state40 = "1000000000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state41 = "10000000000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state42 = "100000000000000000000000000000000000000000";
const sc_lv<43> quantize_activation::ap_ST_fsm_state43 = "1000000000000000000000000000000000000000000";
const sc_lv<32> quantize_activation::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> quantize_activation::ap_const_lv32_2 = "10";
const sc_lv<32> quantize_activation::ap_const_lv32_1C = "11100";
const sc_lv<32> quantize_activation::ap_const_lv32_1 = "1";
const sc_lv<1> quantize_activation::ap_const_lv1_0 = "0";
const sc_lv<32> quantize_activation::ap_const_lv32_3 = "11";
const sc_lv<32> quantize_activation::ap_const_lv32_5 = "101";
const sc_lv<32> quantize_activation::ap_const_lv32_6 = "110";
const sc_lv<32> quantize_activation::ap_const_lv32_7 = "111";
const sc_lv<32> quantize_activation::ap_const_lv32_16 = "10110";
const sc_lv<32> quantize_activation::ap_const_lv32_18 = "11000";
const sc_lv<32> quantize_activation::ap_const_lv32_19 = "11001";
const sc_lv<32> quantize_activation::ap_const_lv32_1A = "11010";
const sc_lv<32> quantize_activation::ap_const_lv32_1B = "11011";
const sc_lv<32> quantize_activation::ap_const_lv32_20 = "100000";
const sc_lv<32> quantize_activation::ap_const_lv32_22 = "100010";
const sc_lv<32> quantize_activation::ap_const_lv32_23 = "100011";
const sc_lv<32> quantize_activation::ap_const_lv32_27 = "100111";
const sc_lv<32> quantize_activation::ap_const_lv32_28 = "101000";
const sc_lv<32> quantize_activation::ap_const_lv32_29 = "101001";
const sc_lv<11> quantize_activation::ap_const_lv11_0 = "00000000000";
const sc_lv<9> quantize_activation::ap_const_lv9_0 = "000000000";
const sc_lv<1> quantize_activation::ap_const_lv1_1 = "1";
const sc_lv<3> quantize_activation::ap_const_lv3_0 = "000";
const sc_lv<32> quantize_activation::ap_const_lv32_2A = "101010";
const sc_lv<32> quantize_activation::ap_const_lv32_1D = "11101";
const sc_lv<32> quantize_activation::ap_const_lv32_42FE0000 = "1000010111111100000000000000000";
const sc_lv<32> quantize_activation::ap_const_lv32_17 = "10111";
const sc_lv<32> quantize_activation::ap_const_lv32_3727C5AC = "110111001001111100010110101100";
const sc_lv<32> quantize_activation::ap_const_lv32_4 = "100";
const sc_lv<32> quantize_activation::ap_const_lv32_21 = "100001";
const sc_lv<11> quantize_activation::ap_const_lv11_600 = "11000000000";
const sc_lv<11> quantize_activation::ap_const_lv11_1 = "1";
const sc_lv<32> quantize_activation::ap_const_lv32_1E = "11110";
const sc_lv<8> quantize_activation::ap_const_lv8_FF = "11111111";
const sc_lv<23> quantize_activation::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> quantize_activation::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<32> quantize_activation::ap_const_lv32_3F = "111111";
const sc_lv<32> quantize_activation::ap_const_lv32_34 = "110100";
const sc_lv<32> quantize_activation::ap_const_lv32_3E = "111110";
const sc_lv<54> quantize_activation::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<63> quantize_activation::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> quantize_activation::ap_const_lv12_433 = "10000110011";
const sc_lv<12> quantize_activation::ap_const_lv12_14 = "10100";
const sc_lv<12> quantize_activation::ap_const_lv12_FEC = "111111101100";
const sc_lv<32> quantize_activation::ap_const_lv32_B = "1011";
const sc_lv<12> quantize_activation::ap_const_lv12_36 = "110110";
const sc_lv<7> quantize_activation::ap_const_lv7_0 = "0000000";
const sc_lv<32> quantize_activation::ap_const_lv32_1F = "11111";
const sc_lv<32> quantize_activation::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<9> quantize_activation::ap_const_lv9_180 = "110000000";
const sc_lv<9> quantize_activation::ap_const_lv9_1 = "1";
const sc_lv<2> quantize_activation::ap_const_lv2_0 = "00";
const sc_lv<3> quantize_activation::ap_const_lv3_4 = "100";
const sc_lv<3> quantize_activation::ap_const_lv3_1 = "1";
const sc_lv<32> quantize_activation::ap_const_lv32_3F000000 = "111111000000000000000000000000";
const sc_lv<32> quantize_activation::ap_const_lv32_BF000000 = "10111111000000000000000000000000";
const sc_lv<9> quantize_activation::ap_const_lv9_181 = "110000001";
const sc_lv<32> quantize_activation::ap_const_lv32_8 = "1000";
const sc_lv<8> quantize_activation::ap_const_lv8_7F = "1111111";
const sc_lv<32> quantize_activation::ap_const_lv32_37 = "110111";
const sc_lv<32> quantize_activation::ap_const_lv32_FFFFFF80 = "11111111111111111111111110000000";
const sc_lv<25> quantize_activation::ap_const_lv25_0 = "0000000000000000000000000";
const sc_lv<8> quantize_activation::ap_const_lv8_80 = "10000000";
const sc_lv<5> quantize_activation::ap_const_lv5_4 = "100";
const sc_lv<5> quantize_activation::ap_const_lv5_2 = "10";
const bool quantize_activation::ap_const_boolean_1 = true;

quantize_activation::quantize_activation(sc_module_name name) : sc_module(name), mVcdFile(0) {
    attention_fadd_32pcA_U33 = new attention_fadd_32pcA<1,5,32,32,32>("attention_fadd_32pcA_U33");
    attention_fadd_32pcA_U33->clk(ap_clk);
    attention_fadd_32pcA_U33->reset(ap_rst);
    attention_fadd_32pcA_U33->din0(v1_reg_1176);
    attention_fadd_32pcA_U33->din1(grp_fu_223_p1);
    attention_fadd_32pcA_U33->ce(ap_var_for_const0);
    attention_fadd_32pcA_U33->dout(grp_fu_223_p2);
    attention_fmul_32qcK_U34 = new attention_fmul_32qcK<1,4,32,32,32>("attention_fmul_32qcK_U34");
    attention_fmul_32qcK_U34->clk(ap_clk);
    attention_fmul_32qcK_U34->reset(ap_rst);
    attention_fmul_32qcK_U34->din0(reg_248);
    attention_fmul_32qcK_U34->din1(v_reg_1089);
    attention_fmul_32qcK_U34->ce(ap_var_for_const0);
    attention_fmul_32qcK_U34->dout(grp_fu_227_p2);
    attention_fdiv_32rcU_U35 = new attention_fdiv_32rcU<1,16,32,32,32>("attention_fdiv_32rcU_U35");
    attention_fdiv_32rcU_U35->clk(ap_clk);
    attention_fdiv_32rcU_U35->reset(ap_rst);
    attention_fdiv_32rcU_U35->din0(ap_var_for_const1);
    attention_fdiv_32rcU_U35->din1(grp_fu_231_p1);
    attention_fdiv_32rcU_U35->ce(ap_var_for_const0);
    attention_fdiv_32rcU_U35->dout(grp_fu_231_p2);
    attention_fpext_3sc4_U36 = new attention_fpext_3sc4<1,2,32,64>("attention_fpext_3sc4_U36");
    attention_fpext_3sc4_U36->clk(ap_clk);
    attention_fpext_3sc4_U36->reset(ap_rst);
    attention_fpext_3sc4_U36->din0(v_reg_1089);
    attention_fpext_3sc4_U36->ce(ap_var_for_const0);
    attention_fpext_3sc4_U36->dout(grp_fu_236_p1);
    attention_fcmp_32tde_U37 = new attention_fcmp_32tde<1,2,32,32,1>("attention_fcmp_32tde_U37");
    attention_fcmp_32tde_U37->clk(ap_clk);
    attention_fcmp_32tde_U37->reset(ap_rst);
    attention_fcmp_32tde_U37->din0(grp_fu_239_p0);
    attention_fcmp_32tde_U37->din1(grp_fu_239_p1);
    attention_fcmp_32tde_U37->ce(ap_var_for_const0);
    attention_fcmp_32tde_U37->opcode(grp_fu_239_opcode);
    attention_fcmp_32tde_U37->dout(grp_fu_239_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln100_fu_786_p2);
    sensitive << ( shl_ln_reg_1148 );
    sensitive << ( zext_ln99_fu_770_p1 );

    SC_METHOD(thread_add_ln121_fu_800_p2);
    sensitive << ( zext_ln99_1_reg_1153 );
    sensitive << ( zext_ln121_fu_796_p1 );

    SC_METHOD(thread_add_ln339_fu_895_p2);
    sensitive << ( zext_ln339_fu_891_p1 );

    SC_METHOD(thread_add_ln581_fu_547_p2);
    sensitive << ( sub_ln575_fu_535_p2 );

    SC_METHOD(thread_add_ln70_fu_260_p2);
    sensitive << ( j_0_0_reg_178 );

    SC_METHOD(thread_add_ln98_fu_752_p2);
    sensitive << ( j1_0_0_reg_201 );

    SC_METHOD(thread_add_ln99_fu_780_p2);
    sensitive << ( l_0_0_reg_212 );

    SC_METHOD(thread_and_ln103_fu_838_p2);
    sensitive << ( tmp_10_reg_1193 );
    sensitive << ( or_ln103_fu_834_p2 );

    SC_METHOD(thread_and_ln215_fu_455_p2);
    sensitive << ( tmp_8_reg_1079 );
    sensitive << ( or_ln215_fu_451_p2 );

    SC_METHOD(thread_and_ln581_fu_657_p2);
    sensitive << ( icmp_ln581_reg_1107 );
    sensitive << ( xor_ln582_fu_651_p2 );

    SC_METHOD(thread_and_ln582_fu_642_p2);
    sensitive << ( icmp_ln582_reg_1119 );
    sensitive << ( xor_ln571_fu_637_p2 );

    SC_METHOD(thread_and_ln585_1_fu_674_p2);
    sensitive << ( icmp_ln585_fu_590_p2 );
    sensitive << ( and_ln581_fu_657_p2 );

    SC_METHOD(thread_and_ln585_fu_668_p2);
    sensitive << ( and_ln581_fu_657_p2 );
    sensitive << ( xor_ln585_fu_662_p2 );

    SC_METHOD(thread_and_ln603_fu_691_p2);
    sensitive << ( icmp_ln603_fu_595_p2 );
    sensitive << ( xor_ln581_fu_685_p2 );

    SC_METHOD(thread_and_ln72_fu_307_p2);
    sensitive << ( grp_fu_239_p2 );
    sensitive << ( or_ln72_fu_301_p2 );

    SC_METHOD(thread_and_ln79_1_fu_408_p2);
    sensitive << ( grp_fu_239_p2 );
    sensitive << ( and_ln79_fu_402_p2 );

    SC_METHOD(thread_and_ln79_fu_402_p2);
    sensitive << ( or_ln79_fu_378_p2 );
    sensitive << ( or_ln79_1_fu_396_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state27);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state34);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state35);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state36);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state40);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state41);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state42);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state43);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( icmp_ln98_fu_746_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_phi_mux_v45_0_phi_fu_193_p4);
    sensitive << ( v45_0_reg_189 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( icmp_ln98_fu_746_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( select_ln603_3_reg_1136 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( icmp_ln98_fu_746_p2 );

    SC_METHOD(thread_ashr_ln586_fu_604_p2);
    sensitive << ( select_ln570_reg_1096 );
    sensitive << ( zext_ln586_fu_600_p1 );

    SC_METHOD(thread_bitcast_ln103_fu_805_p1);
    sensitive << ( v1_reg_1176 );

    SC_METHOD(thread_bitcast_ln215_fu_421_p1);
    sensitive << ( v45_0_reg_189 );

    SC_METHOD(thread_bitcast_ln696_1_fu_613_p1);
    sensitive << ( v_reg_1089 );

    SC_METHOD(thread_bitcast_ln696_fu_469_p1);
    sensitive << ( grp_fu_236_p1 );

    SC_METHOD(thread_bitcast_ln72_fu_271_p1);
    sensitive << ( reg_248 );

    SC_METHOD(thread_bitcast_ln73_fu_319_p1);
    sensitive << ( xor_ln73_fu_313_p2 );

    SC_METHOD(thread_bitcast_ln79_1_fu_349_p1);
    sensitive << ( select_ln74_reg_1057 );

    SC_METHOD(thread_bitcast_ln79_fu_331_p1);
    sensitive << ( v45_0_reg_189 );

    SC_METHOD(thread_grp_fu_223_p1);
    sensitive << ( ap_CS_fsm_state36 );
    sensitive << ( and_ln103_fu_838_p2 );

    SC_METHOD(thread_grp_fu_231_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( v45_0_reg_189 );
    sensitive << ( and_ln215_fu_455_p2 );

    SC_METHOD(thread_grp_fu_239_opcode);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln70_fu_254_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state34 );

    SC_METHOD(thread_grp_fu_239_p0);
    sensitive << ( v22_0_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( v1_reg_1176 );
    sensitive << ( ap_phi_mux_v45_0_phi_fu_193_p4 );
    sensitive << ( v45_0_reg_189 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state34 );

    SC_METHOD(thread_grp_fu_239_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( select_ln74_reg_1057 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state34 );

    SC_METHOD(thread_icmp_ln103_1_fu_828_p2);
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( trunc_ln103_fu_818_p1 );

    SC_METHOD(thread_icmp_ln103_fu_822_p2);
    sensitive << ( ap_CS_fsm_state35 );
    sensitive << ( tmp_4_fu_808_p4 );

    SC_METHOD(thread_icmp_ln112_fu_992_p2);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( p_Val2_6_fu_986_p3 );

    SC_METHOD(thread_icmp_ln114_fu_1008_p2);
    sensitive << ( ap_CS_fsm_state42 );
    sensitive << ( tmp_17_fu_998_p4 );

    SC_METHOD(thread_icmp_ln215_1_fu_445_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( trunc_ln215_fu_435_p1 );

    SC_METHOD(thread_icmp_ln215_fu_439_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_7_fu_425_p4 );

    SC_METHOD(thread_icmp_ln571_fu_529_p2);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( trunc_ln557_fu_473_p1 );

    SC_METHOD(thread_icmp_ln581_fu_541_p2);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( sub_ln575_fu_535_p2 );

    SC_METHOD(thread_icmp_ln582_fu_567_p2);
    sensitive << ( ap_CS_fsm_state25 );
    sensitive << ( sub_ln575_fu_535_p2 );

    SC_METHOD(thread_icmp_ln585_fu_590_p2);
    sensitive << ( select_ln581_reg_1113 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_icmp_ln603_fu_595_p2);
    sensitive << ( tmp_12_reg_1131 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_icmp_ln70_fu_254_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( j_0_0_reg_178 );

    SC_METHOD(thread_icmp_ln72_1_fu_295_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( trunc_ln72_fu_285_p1 );

    SC_METHOD(thread_icmp_ln72_fu_289_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_9_fu_275_p4 );

    SC_METHOD(thread_icmp_ln79_1_fu_372_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln79_fu_345_p1 );

    SC_METHOD(thread_icmp_ln79_2_fu_384_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_2_fu_352_p4 );

    SC_METHOD(thread_icmp_ln79_3_fu_390_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( trunc_ln79_1_fu_362_p1 );

    SC_METHOD(thread_icmp_ln79_fu_366_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_1_fu_335_p4 );

    SC_METHOD(thread_icmp_ln98_fu_746_p2);
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( j1_0_0_reg_201 );

    SC_METHOD(thread_icmp_ln99_fu_774_p2);
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( l_0_0_reg_212 );

    SC_METHOD(thread_isNeg_fu_901_p3);
    sensitive << ( add_ln339_fu_895_p2 );

    SC_METHOD(thread_mantissa_V_fu_877_p4);
    sensitive << ( tmp_V_1_fu_873_p1 );

    SC_METHOD(thread_or_ln103_fu_834_p2);
    sensitive << ( icmp_ln103_reg_1183 );
    sensitive << ( icmp_ln103_1_reg_1188 );

    SC_METHOD(thread_or_ln117_fu_1026_p2);
    sensitive << ( icmp_ln112_fu_992_p2 );
    sensitive << ( icmp_ln114_fu_1008_p2 );

    SC_METHOD(thread_or_ln215_fu_451_p2);
    sensitive << ( icmp_ln215_reg_1069 );
    sensitive << ( icmp_ln215_1_reg_1074 );

    SC_METHOD(thread_or_ln581_fu_680_p2);
    sensitive << ( icmp_ln581_reg_1107 );
    sensitive << ( or_ln582_fu_647_p2 );

    SC_METHOD(thread_or_ln582_fu_647_p2);
    sensitive << ( icmp_ln571_reg_1101 );
    sensitive << ( icmp_ln582_reg_1119 );

    SC_METHOD(thread_or_ln603_1_fu_718_p2);
    sensitive << ( and_ln585_fu_668_p2 );
    sensitive << ( and_ln582_fu_642_p2 );

    SC_METHOD(thread_or_ln603_2_fu_732_p2);
    sensitive << ( or_ln603_fu_705_p2 );
    sensitive << ( or_ln603_1_fu_718_p2 );

    SC_METHOD(thread_or_ln603_fu_705_p2);
    sensitive << ( and_ln603_fu_691_p2 );
    sensitive << ( and_ln585_1_fu_674_p2 );

    SC_METHOD(thread_or_ln72_fu_301_p2);
    sensitive << ( icmp_ln72_1_fu_295_p2 );
    sensitive << ( icmp_ln72_fu_289_p2 );

    SC_METHOD(thread_or_ln79_1_fu_396_p2);
    sensitive << ( icmp_ln79_3_fu_390_p2 );
    sensitive << ( icmp_ln79_2_fu_384_p2 );

    SC_METHOD(thread_or_ln79_fu_378_p2);
    sensitive << ( icmp_ln79_1_fu_372_p2 );
    sensitive << ( icmp_ln79_fu_366_p2 );

    SC_METHOD(thread_p_Result_s_fu_485_p4);
    sensitive << ( bitcast_ln696_fu_469_p1 );

    SC_METHOD(thread_p_Val2_5_fu_973_p3);
    sensitive << ( isNeg_fu_901_p3 );
    sensitive << ( zext_ln662_fu_959_p1 );
    sensitive << ( tmp_14_fu_963_p4 );

    SC_METHOD(thread_p_Val2_6_fu_986_p3);
    sensitive << ( p_Result_6_reg_1208 );
    sensitive << ( p_Val2_5_reg_1213 );
    sensitive << ( result_V_1_fu_981_p2 );

    SC_METHOD(thread_p_Val2_s_fu_852_p1);
    sensitive << ( x_assign_reg_1203 );

    SC_METHOD(thread_r_V_1_fu_945_p2);
    sensitive << ( zext_ln682_fu_887_p1 );
    sensitive << ( zext_ln1287_fu_935_p1 );

    SC_METHOD(thread_r_V_fu_939_p2);
    sensitive << ( mantissa_V_fu_877_p4 );
    sensitive << ( sext_ln1311_2_fu_931_p1 );

    SC_METHOD(thread_result_V_1_fu_981_p2);
    sensitive << ( p_Val2_5_reg_1213 );

    SC_METHOD(thread_select_ln117_1_fu_1032_p3);
    sensitive << ( or_ln117_fu_1026_p2 );
    sensitive << ( select_ln117_fu_1018_p3 );
    sensitive << ( trunc_ln117_fu_1014_p1 );

    SC_METHOD(thread_select_ln117_fu_1018_p3);
    sensitive << ( icmp_ln112_fu_992_p2 );

    SC_METHOD(thread_select_ln570_fu_521_p3);
    sensitive << ( zext_ln569_fu_511_p1 );
    sensitive << ( tmp_11_fu_477_p3 );
    sensitive << ( sub_ln461_fu_515_p2 );

    SC_METHOD(thread_select_ln581_fu_559_p3);
    sensitive << ( icmp_ln581_fu_541_p2 );
    sensitive << ( add_ln581_fu_547_p2 );
    sensitive << ( sub_ln581_fu_553_p2 );

    SC_METHOD(thread_select_ln588_fu_624_p3);
    sensitive << ( tmp_13_fu_616_p3 );

    SC_METHOD(thread_select_ln603_1_fu_711_p3);
    sensitive << ( trunc_ln583_reg_1125 );
    sensitive << ( and_ln585_fu_668_p2 );
    sensitive << ( select_ln588_fu_624_p3 );

    SC_METHOD(thread_select_ln603_2_fu_724_p3);
    sensitive << ( or_ln603_fu_705_p2 );
    sensitive << ( select_ln603_fu_697_p3 );
    sensitive << ( select_ln603_1_fu_711_p3 );

    SC_METHOD(thread_select_ln603_3_fu_738_p3);
    sensitive << ( or_ln603_2_fu_732_p2 );
    sensitive << ( select_ln603_2_fu_724_p3 );

    SC_METHOD(thread_select_ln603_fu_697_p3);
    sensitive << ( and_ln603_fu_691_p2 );
    sensitive << ( shl_ln604_fu_632_p2 );
    sensitive << ( trunc_ln586_fu_609_p1 );

    SC_METHOD(thread_select_ln74_fu_323_p3);
    sensitive << ( reg_248 );
    sensitive << ( and_ln72_fu_307_p2 );
    sensitive << ( bitcast_ln73_fu_319_p1 );

    SC_METHOD(thread_select_ln80_fu_414_p3);
    sensitive << ( select_ln74_reg_1057 );
    sensitive << ( v45_0_reg_189 );
    sensitive << ( and_ln79_1_fu_408_p2 );

    SC_METHOD(thread_sext_ln1311_1_fu_927_p1);
    sensitive << ( ush_fu_919_p3 );

    SC_METHOD(thread_sext_ln1311_2_fu_931_p1);
    sensitive << ( ush_fu_919_p3 );

    SC_METHOD(thread_sext_ln1311_fu_915_p1);
    sensitive << ( sub_ln1311_fu_909_p2 );

    SC_METHOD(thread_sext_ln581_fu_587_p1);
    sensitive << ( select_ln581_reg_1113 );

    SC_METHOD(thread_shl_ln604_fu_632_p2);
    sensitive << ( trunc_ln583_reg_1125 );
    sensitive << ( sext_ln581_fu_587_p1 );

    SC_METHOD(thread_shl_ln_fu_758_p3);
    sensitive << ( j1_0_0_reg_201 );

    SC_METHOD(thread_sub_ln1311_fu_909_p2);
    sensitive << ( tmp_V_fu_863_p4 );

    SC_METHOD(thread_sub_ln461_fu_515_p2);
    sensitive << ( zext_ln569_fu_511_p1 );

    SC_METHOD(thread_sub_ln575_fu_535_p2);
    sensitive << ( zext_ln461_fu_495_p1 );

    SC_METHOD(thread_sub_ln581_fu_553_p2);
    sensitive << ( sub_ln575_fu_535_p2 );

    SC_METHOD(thread_tmp_11_fu_477_p3);
    sensitive << ( bitcast_ln696_fu_469_p1 );

    SC_METHOD(thread_tmp_13_fu_616_p3);
    sensitive << ( bitcast_ln696_1_fu_613_p1 );

    SC_METHOD(thread_tmp_14_fu_963_p4);
    sensitive << ( r_V_1_fu_945_p2 );

    SC_METHOD(thread_tmp_16_fu_951_p3);
    sensitive << ( r_V_fu_939_p2 );

    SC_METHOD(thread_tmp_17_fu_998_p4);
    sensitive << ( p_Val2_6_fu_986_p3 );

    SC_METHOD(thread_tmp_1_fu_335_p4);
    sensitive << ( bitcast_ln79_fu_331_p1 );

    SC_METHOD(thread_tmp_2_fu_352_p4);
    sensitive << ( bitcast_ln79_1_fu_349_p1 );

    SC_METHOD(thread_tmp_4_fu_808_p4);
    sensitive << ( bitcast_ln103_fu_805_p1 );

    SC_METHOD(thread_tmp_5_fu_503_p3);
    sensitive << ( trunc_ln565_fu_499_p1 );

    SC_METHOD(thread_tmp_7_fu_425_p4);
    sensitive << ( bitcast_ln215_fu_421_p1 );

    SC_METHOD(thread_tmp_9_fu_275_p4);
    sensitive << ( bitcast_ln72_fu_271_p1 );

    SC_METHOD(thread_tmp_V_1_fu_873_p1);
    sensitive << ( p_Val2_s_fu_852_p1 );

    SC_METHOD(thread_tmp_V_fu_863_p4);
    sensitive << ( p_Val2_s_fu_852_p1 );

    SC_METHOD(thread_trunc_ln103_fu_818_p1);
    sensitive << ( bitcast_ln103_fu_805_p1 );

    SC_METHOD(thread_trunc_ln117_fu_1014_p1);
    sensitive << ( p_Val2_6_fu_986_p3 );

    SC_METHOD(thread_trunc_ln215_fu_435_p1);
    sensitive << ( bitcast_ln215_fu_421_p1 );

    SC_METHOD(thread_trunc_ln557_fu_473_p1);
    sensitive << ( bitcast_ln696_fu_469_p1 );

    SC_METHOD(thread_trunc_ln565_fu_499_p1);
    sensitive << ( bitcast_ln696_fu_469_p1 );

    SC_METHOD(thread_trunc_ln583_fu_573_p1);
    sensitive << ( select_ln570_fu_521_p3 );

    SC_METHOD(thread_trunc_ln586_fu_609_p1);
    sensitive << ( ashr_ln586_fu_604_p2 );

    SC_METHOD(thread_trunc_ln72_fu_285_p1);
    sensitive << ( bitcast_ln72_fu_271_p1 );

    SC_METHOD(thread_trunc_ln79_1_fu_362_p1);
    sensitive << ( bitcast_ln79_1_fu_349_p1 );

    SC_METHOD(thread_trunc_ln79_fu_345_p1);
    sensitive << ( bitcast_ln79_fu_331_p1 );

    SC_METHOD(thread_ush_fu_919_p3);
    sensitive << ( add_ln339_fu_895_p2 );
    sensitive << ( isNeg_fu_901_p3 );
    sensitive << ( sext_ln1311_fu_915_p1 );

    SC_METHOD(thread_v22_0_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( zext_ln71_fu_266_p1 );
    sensitive << ( zext_ln100_fu_791_p1 );

    SC_METHOD(thread_v22_0_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state28 );

    SC_METHOD(thread_v24_0_address0);
    sensitive << ( ap_CS_fsm_state43 );
    sensitive << ( zext_ln121_1_fu_1040_p1 );

    SC_METHOD(thread_v24_0_ce0);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_v24_0_d0);
    sensitive << ( select_ln117_1_reg_1219 );
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_v24_0_we0);
    sensitive << ( ap_CS_fsm_state43 );

    SC_METHOD(thread_xor_ln571_fu_637_p2);
    sensitive << ( icmp_ln571_reg_1101 );

    SC_METHOD(thread_xor_ln581_fu_685_p2);
    sensitive << ( or_ln581_fu_680_p2 );

    SC_METHOD(thread_xor_ln582_fu_651_p2);
    sensitive << ( or_ln582_fu_647_p2 );

    SC_METHOD(thread_xor_ln585_fu_662_p2);
    sensitive << ( icmp_ln585_fu_590_p2 );

    SC_METHOD(thread_xor_ln73_fu_313_p2);
    sensitive << ( bitcast_ln72_fu_271_p1 );

    SC_METHOD(thread_zext_ln100_fu_791_p1);
    sensitive << ( add_ln100_fu_786_p2 );

    SC_METHOD(thread_zext_ln121_1_fu_1040_p1);
    sensitive << ( add_ln121_reg_1171 );

    SC_METHOD(thread_zext_ln121_fu_796_p1);
    sensitive << ( l_0_0_reg_212 );

    SC_METHOD(thread_zext_ln1287_fu_935_p1);
    sensitive << ( sext_ln1311_1_fu_927_p1 );

    SC_METHOD(thread_zext_ln339_fu_891_p1);
    sensitive << ( tmp_V_fu_863_p4 );

    SC_METHOD(thread_zext_ln461_fu_495_p1);
    sensitive << ( p_Result_s_fu_485_p4 );

    SC_METHOD(thread_zext_ln569_fu_511_p1);
    sensitive << ( tmp_5_fu_503_p3 );

    SC_METHOD(thread_zext_ln586_fu_600_p1);
    sensitive << ( sext_ln581_fu_587_p1 );

    SC_METHOD(thread_zext_ln662_fu_959_p1);
    sensitive << ( tmp_16_fu_951_p3 );

    SC_METHOD(thread_zext_ln682_fu_887_p1);
    sensitive << ( mantissa_V_fu_877_p4 );

    SC_METHOD(thread_zext_ln71_fu_266_p1);
    sensitive << ( j_0_0_reg_178 );

    SC_METHOD(thread_zext_ln99_1_fu_766_p1);
    sensitive << ( shl_ln_fu_758_p3 );

    SC_METHOD(thread_zext_ln99_fu_770_p1);
    sensitive << ( l_0_0_reg_212 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln70_fu_254_p2 );
    sensitive << ( ap_CS_fsm_state27 );
    sensitive << ( icmp_ln98_fu_746_p2 );
    sensitive << ( ap_CS_fsm_state28 );
    sensitive << ( icmp_ln99_fu_774_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000000000000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "quantize_activation_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, v22_0_address0, "(port)v22_0_address0");
    sc_trace(mVcdFile, v22_0_ce0, "(port)v22_0_ce0");
    sc_trace(mVcdFile, v22_0_q0, "(port)v22_0_q0");
    sc_trace(mVcdFile, v24_0_address0, "(port)v24_0_address0");
    sc_trace(mVcdFile, v24_0_ce0, "(port)v24_0_ce0");
    sc_trace(mVcdFile, v24_0_we0, "(port)v24_0_we0");
    sc_trace(mVcdFile, v24_0_d0, "(port)v24_0_d0");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_248, "reg_248");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, add_ln70_fu_260_p2, "add_ln70_fu_260_p2");
    sc_trace(mVcdFile, add_ln70_reg_1047, "add_ln70_reg_1047");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln70_fu_254_p2, "icmp_ln70_fu_254_p2");
    sc_trace(mVcdFile, select_ln74_fu_323_p3, "select_ln74_fu_323_p3");
    sc_trace(mVcdFile, select_ln74_reg_1057, "select_ln74_reg_1057");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, select_ln80_fu_414_p3, "select_ln80_fu_414_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln215_fu_439_p2, "icmp_ln215_fu_439_p2");
    sc_trace(mVcdFile, icmp_ln215_reg_1069, "icmp_ln215_reg_1069");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln215_1_fu_445_p2, "icmp_ln215_1_fu_445_p2");
    sc_trace(mVcdFile, icmp_ln215_1_reg_1074, "icmp_ln215_1_reg_1074");
    sc_trace(mVcdFile, grp_fu_239_p2, "grp_fu_239_p2");
    sc_trace(mVcdFile, tmp_8_reg_1079, "tmp_8_reg_1079");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_231_p2, "grp_fu_231_p2");
    sc_trace(mVcdFile, v_reg_1089, "v_reg_1089");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, select_ln570_fu_521_p3, "select_ln570_fu_521_p3");
    sc_trace(mVcdFile, select_ln570_reg_1096, "select_ln570_reg_1096");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, icmp_ln571_fu_529_p2, "icmp_ln571_fu_529_p2");
    sc_trace(mVcdFile, icmp_ln571_reg_1101, "icmp_ln571_reg_1101");
    sc_trace(mVcdFile, icmp_ln581_fu_541_p2, "icmp_ln581_fu_541_p2");
    sc_trace(mVcdFile, icmp_ln581_reg_1107, "icmp_ln581_reg_1107");
    sc_trace(mVcdFile, select_ln581_fu_559_p3, "select_ln581_fu_559_p3");
    sc_trace(mVcdFile, select_ln581_reg_1113, "select_ln581_reg_1113");
    sc_trace(mVcdFile, icmp_ln582_fu_567_p2, "icmp_ln582_fu_567_p2");
    sc_trace(mVcdFile, icmp_ln582_reg_1119, "icmp_ln582_reg_1119");
    sc_trace(mVcdFile, trunc_ln583_fu_573_p1, "trunc_ln583_fu_573_p1");
    sc_trace(mVcdFile, trunc_ln583_reg_1125, "trunc_ln583_reg_1125");
    sc_trace(mVcdFile, tmp_12_reg_1131, "tmp_12_reg_1131");
    sc_trace(mVcdFile, select_ln603_3_fu_738_p3, "select_ln603_3_fu_738_p3");
    sc_trace(mVcdFile, select_ln603_3_reg_1136, "select_ln603_3_reg_1136");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, add_ln98_fu_752_p2, "add_ln98_fu_752_p2");
    sc_trace(mVcdFile, add_ln98_reg_1143, "add_ln98_reg_1143");
    sc_trace(mVcdFile, ap_CS_fsm_state27, "ap_CS_fsm_state27");
    sc_trace(mVcdFile, shl_ln_fu_758_p3, "shl_ln_fu_758_p3");
    sc_trace(mVcdFile, shl_ln_reg_1148, "shl_ln_reg_1148");
    sc_trace(mVcdFile, icmp_ln98_fu_746_p2, "icmp_ln98_fu_746_p2");
    sc_trace(mVcdFile, zext_ln99_1_fu_766_p1, "zext_ln99_1_fu_766_p1");
    sc_trace(mVcdFile, zext_ln99_1_reg_1153, "zext_ln99_1_reg_1153");
    sc_trace(mVcdFile, add_ln99_fu_780_p2, "add_ln99_fu_780_p2");
    sc_trace(mVcdFile, add_ln99_reg_1161, "add_ln99_reg_1161");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, icmp_ln99_fu_774_p2, "icmp_ln99_fu_774_p2");
    sc_trace(mVcdFile, add_ln121_fu_800_p2, "add_ln121_fu_800_p2");
    sc_trace(mVcdFile, add_ln121_reg_1171, "add_ln121_reg_1171");
    sc_trace(mVcdFile, grp_fu_227_p2, "grp_fu_227_p2");
    sc_trace(mVcdFile, v1_reg_1176, "v1_reg_1176");
    sc_trace(mVcdFile, ap_CS_fsm_state33, "ap_CS_fsm_state33");
    sc_trace(mVcdFile, icmp_ln103_fu_822_p2, "icmp_ln103_fu_822_p2");
    sc_trace(mVcdFile, icmp_ln103_reg_1183, "icmp_ln103_reg_1183");
    sc_trace(mVcdFile, ap_CS_fsm_state35, "ap_CS_fsm_state35");
    sc_trace(mVcdFile, icmp_ln103_1_fu_828_p2, "icmp_ln103_1_fu_828_p2");
    sc_trace(mVcdFile, icmp_ln103_1_reg_1188, "icmp_ln103_1_reg_1188");
    sc_trace(mVcdFile, tmp_10_reg_1193, "tmp_10_reg_1193");
    sc_trace(mVcdFile, ap_CS_fsm_state36, "ap_CS_fsm_state36");
    sc_trace(mVcdFile, grp_fu_223_p2, "grp_fu_223_p2");
    sc_trace(mVcdFile, x_assign_reg_1203, "x_assign_reg_1203");
    sc_trace(mVcdFile, ap_CS_fsm_state40, "ap_CS_fsm_state40");
    sc_trace(mVcdFile, p_Result_6_reg_1208, "p_Result_6_reg_1208");
    sc_trace(mVcdFile, ap_CS_fsm_state41, "ap_CS_fsm_state41");
    sc_trace(mVcdFile, p_Val2_5_fu_973_p3, "p_Val2_5_fu_973_p3");
    sc_trace(mVcdFile, p_Val2_5_reg_1213, "p_Val2_5_reg_1213");
    sc_trace(mVcdFile, select_ln117_1_fu_1032_p3, "select_ln117_1_fu_1032_p3");
    sc_trace(mVcdFile, select_ln117_1_reg_1219, "select_ln117_1_reg_1219");
    sc_trace(mVcdFile, ap_CS_fsm_state42, "ap_CS_fsm_state42");
    sc_trace(mVcdFile, j_0_0_reg_178, "j_0_0_reg_178");
    sc_trace(mVcdFile, ap_phi_mux_v45_0_phi_fu_193_p4, "ap_phi_mux_v45_0_phi_fu_193_p4");
    sc_trace(mVcdFile, v45_0_reg_189, "v45_0_reg_189");
    sc_trace(mVcdFile, j1_0_0_reg_201, "j1_0_0_reg_201");
    sc_trace(mVcdFile, l_0_0_reg_212, "l_0_0_reg_212");
    sc_trace(mVcdFile, ap_CS_fsm_state43, "ap_CS_fsm_state43");
    sc_trace(mVcdFile, zext_ln71_fu_266_p1, "zext_ln71_fu_266_p1");
    sc_trace(mVcdFile, zext_ln100_fu_791_p1, "zext_ln100_fu_791_p1");
    sc_trace(mVcdFile, zext_ln121_1_fu_1040_p1, "zext_ln121_1_fu_1040_p1");
    sc_trace(mVcdFile, grp_fu_223_p1, "grp_fu_223_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, grp_fu_231_p1, "grp_fu_231_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_239_p0, "grp_fu_239_p0");
    sc_trace(mVcdFile, grp_fu_239_p1, "grp_fu_239_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state34, "ap_CS_fsm_state34");
    sc_trace(mVcdFile, bitcast_ln72_fu_271_p1, "bitcast_ln72_fu_271_p1");
    sc_trace(mVcdFile, tmp_9_fu_275_p4, "tmp_9_fu_275_p4");
    sc_trace(mVcdFile, trunc_ln72_fu_285_p1, "trunc_ln72_fu_285_p1");
    sc_trace(mVcdFile, icmp_ln72_1_fu_295_p2, "icmp_ln72_1_fu_295_p2");
    sc_trace(mVcdFile, icmp_ln72_fu_289_p2, "icmp_ln72_fu_289_p2");
    sc_trace(mVcdFile, or_ln72_fu_301_p2, "or_ln72_fu_301_p2");
    sc_trace(mVcdFile, xor_ln73_fu_313_p2, "xor_ln73_fu_313_p2");
    sc_trace(mVcdFile, and_ln72_fu_307_p2, "and_ln72_fu_307_p2");
    sc_trace(mVcdFile, bitcast_ln73_fu_319_p1, "bitcast_ln73_fu_319_p1");
    sc_trace(mVcdFile, bitcast_ln79_fu_331_p1, "bitcast_ln79_fu_331_p1");
    sc_trace(mVcdFile, bitcast_ln79_1_fu_349_p1, "bitcast_ln79_1_fu_349_p1");
    sc_trace(mVcdFile, tmp_1_fu_335_p4, "tmp_1_fu_335_p4");
    sc_trace(mVcdFile, trunc_ln79_fu_345_p1, "trunc_ln79_fu_345_p1");
    sc_trace(mVcdFile, icmp_ln79_1_fu_372_p2, "icmp_ln79_1_fu_372_p2");
    sc_trace(mVcdFile, icmp_ln79_fu_366_p2, "icmp_ln79_fu_366_p2");
    sc_trace(mVcdFile, tmp_2_fu_352_p4, "tmp_2_fu_352_p4");
    sc_trace(mVcdFile, trunc_ln79_1_fu_362_p1, "trunc_ln79_1_fu_362_p1");
    sc_trace(mVcdFile, icmp_ln79_3_fu_390_p2, "icmp_ln79_3_fu_390_p2");
    sc_trace(mVcdFile, icmp_ln79_2_fu_384_p2, "icmp_ln79_2_fu_384_p2");
    sc_trace(mVcdFile, or_ln79_fu_378_p2, "or_ln79_fu_378_p2");
    sc_trace(mVcdFile, or_ln79_1_fu_396_p2, "or_ln79_1_fu_396_p2");
    sc_trace(mVcdFile, and_ln79_fu_402_p2, "and_ln79_fu_402_p2");
    sc_trace(mVcdFile, and_ln79_1_fu_408_p2, "and_ln79_1_fu_408_p2");
    sc_trace(mVcdFile, bitcast_ln215_fu_421_p1, "bitcast_ln215_fu_421_p1");
    sc_trace(mVcdFile, tmp_7_fu_425_p4, "tmp_7_fu_425_p4");
    sc_trace(mVcdFile, trunc_ln215_fu_435_p1, "trunc_ln215_fu_435_p1");
    sc_trace(mVcdFile, or_ln215_fu_451_p2, "or_ln215_fu_451_p2");
    sc_trace(mVcdFile, and_ln215_fu_455_p2, "and_ln215_fu_455_p2");
    sc_trace(mVcdFile, grp_fu_236_p1, "grp_fu_236_p1");
    sc_trace(mVcdFile, bitcast_ln696_fu_469_p1, "bitcast_ln696_fu_469_p1");
    sc_trace(mVcdFile, p_Result_s_fu_485_p4, "p_Result_s_fu_485_p4");
    sc_trace(mVcdFile, trunc_ln565_fu_499_p1, "trunc_ln565_fu_499_p1");
    sc_trace(mVcdFile, tmp_5_fu_503_p3, "tmp_5_fu_503_p3");
    sc_trace(mVcdFile, zext_ln569_fu_511_p1, "zext_ln569_fu_511_p1");
    sc_trace(mVcdFile, tmp_11_fu_477_p3, "tmp_11_fu_477_p3");
    sc_trace(mVcdFile, sub_ln461_fu_515_p2, "sub_ln461_fu_515_p2");
    sc_trace(mVcdFile, trunc_ln557_fu_473_p1, "trunc_ln557_fu_473_p1");
    sc_trace(mVcdFile, zext_ln461_fu_495_p1, "zext_ln461_fu_495_p1");
    sc_trace(mVcdFile, sub_ln575_fu_535_p2, "sub_ln575_fu_535_p2");
    sc_trace(mVcdFile, add_ln581_fu_547_p2, "add_ln581_fu_547_p2");
    sc_trace(mVcdFile, sub_ln581_fu_553_p2, "sub_ln581_fu_553_p2");
    sc_trace(mVcdFile, sext_ln581_fu_587_p1, "sext_ln581_fu_587_p1");
    sc_trace(mVcdFile, zext_ln586_fu_600_p1, "zext_ln586_fu_600_p1");
    sc_trace(mVcdFile, ashr_ln586_fu_604_p2, "ashr_ln586_fu_604_p2");
    sc_trace(mVcdFile, bitcast_ln696_1_fu_613_p1, "bitcast_ln696_1_fu_613_p1");
    sc_trace(mVcdFile, tmp_13_fu_616_p3, "tmp_13_fu_616_p3");
    sc_trace(mVcdFile, xor_ln571_fu_637_p2, "xor_ln571_fu_637_p2");
    sc_trace(mVcdFile, or_ln582_fu_647_p2, "or_ln582_fu_647_p2");
    sc_trace(mVcdFile, xor_ln582_fu_651_p2, "xor_ln582_fu_651_p2");
    sc_trace(mVcdFile, icmp_ln585_fu_590_p2, "icmp_ln585_fu_590_p2");
    sc_trace(mVcdFile, and_ln581_fu_657_p2, "and_ln581_fu_657_p2");
    sc_trace(mVcdFile, xor_ln585_fu_662_p2, "xor_ln585_fu_662_p2");
    sc_trace(mVcdFile, or_ln581_fu_680_p2, "or_ln581_fu_680_p2");
    sc_trace(mVcdFile, icmp_ln603_fu_595_p2, "icmp_ln603_fu_595_p2");
    sc_trace(mVcdFile, xor_ln581_fu_685_p2, "xor_ln581_fu_685_p2");
    sc_trace(mVcdFile, and_ln603_fu_691_p2, "and_ln603_fu_691_p2");
    sc_trace(mVcdFile, shl_ln604_fu_632_p2, "shl_ln604_fu_632_p2");
    sc_trace(mVcdFile, trunc_ln586_fu_609_p1, "trunc_ln586_fu_609_p1");
    sc_trace(mVcdFile, and_ln585_1_fu_674_p2, "and_ln585_1_fu_674_p2");
    sc_trace(mVcdFile, and_ln585_fu_668_p2, "and_ln585_fu_668_p2");
    sc_trace(mVcdFile, select_ln588_fu_624_p3, "select_ln588_fu_624_p3");
    sc_trace(mVcdFile, and_ln582_fu_642_p2, "and_ln582_fu_642_p2");
    sc_trace(mVcdFile, or_ln603_fu_705_p2, "or_ln603_fu_705_p2");
    sc_trace(mVcdFile, select_ln603_fu_697_p3, "select_ln603_fu_697_p3");
    sc_trace(mVcdFile, select_ln603_1_fu_711_p3, "select_ln603_1_fu_711_p3");
    sc_trace(mVcdFile, or_ln603_1_fu_718_p2, "or_ln603_1_fu_718_p2");
    sc_trace(mVcdFile, or_ln603_2_fu_732_p2, "or_ln603_2_fu_732_p2");
    sc_trace(mVcdFile, select_ln603_2_fu_724_p3, "select_ln603_2_fu_724_p3");
    sc_trace(mVcdFile, zext_ln99_fu_770_p1, "zext_ln99_fu_770_p1");
    sc_trace(mVcdFile, add_ln100_fu_786_p2, "add_ln100_fu_786_p2");
    sc_trace(mVcdFile, zext_ln121_fu_796_p1, "zext_ln121_fu_796_p1");
    sc_trace(mVcdFile, bitcast_ln103_fu_805_p1, "bitcast_ln103_fu_805_p1");
    sc_trace(mVcdFile, tmp_4_fu_808_p4, "tmp_4_fu_808_p4");
    sc_trace(mVcdFile, trunc_ln103_fu_818_p1, "trunc_ln103_fu_818_p1");
    sc_trace(mVcdFile, or_ln103_fu_834_p2, "or_ln103_fu_834_p2");
    sc_trace(mVcdFile, and_ln103_fu_838_p2, "and_ln103_fu_838_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_852_p1, "p_Val2_s_fu_852_p1");
    sc_trace(mVcdFile, tmp_V_1_fu_873_p1, "tmp_V_1_fu_873_p1");
    sc_trace(mVcdFile, mantissa_V_fu_877_p4, "mantissa_V_fu_877_p4");
    sc_trace(mVcdFile, tmp_V_fu_863_p4, "tmp_V_fu_863_p4");
    sc_trace(mVcdFile, zext_ln339_fu_891_p1, "zext_ln339_fu_891_p1");
    sc_trace(mVcdFile, add_ln339_fu_895_p2, "add_ln339_fu_895_p2");
    sc_trace(mVcdFile, sub_ln1311_fu_909_p2, "sub_ln1311_fu_909_p2");
    sc_trace(mVcdFile, isNeg_fu_901_p3, "isNeg_fu_901_p3");
    sc_trace(mVcdFile, sext_ln1311_fu_915_p1, "sext_ln1311_fu_915_p1");
    sc_trace(mVcdFile, ush_fu_919_p3, "ush_fu_919_p3");
    sc_trace(mVcdFile, sext_ln1311_1_fu_927_p1, "sext_ln1311_1_fu_927_p1");
    sc_trace(mVcdFile, sext_ln1311_2_fu_931_p1, "sext_ln1311_2_fu_931_p1");
    sc_trace(mVcdFile, zext_ln682_fu_887_p1, "zext_ln682_fu_887_p1");
    sc_trace(mVcdFile, zext_ln1287_fu_935_p1, "zext_ln1287_fu_935_p1");
    sc_trace(mVcdFile, r_V_fu_939_p2, "r_V_fu_939_p2");
    sc_trace(mVcdFile, tmp_16_fu_951_p3, "tmp_16_fu_951_p3");
    sc_trace(mVcdFile, r_V_1_fu_945_p2, "r_V_1_fu_945_p2");
    sc_trace(mVcdFile, zext_ln662_fu_959_p1, "zext_ln662_fu_959_p1");
    sc_trace(mVcdFile, tmp_14_fu_963_p4, "tmp_14_fu_963_p4");
    sc_trace(mVcdFile, result_V_1_fu_981_p2, "result_V_1_fu_981_p2");
    sc_trace(mVcdFile, p_Val2_6_fu_986_p3, "p_Val2_6_fu_986_p3");
    sc_trace(mVcdFile, tmp_17_fu_998_p4, "tmp_17_fu_998_p4");
    sc_trace(mVcdFile, icmp_ln112_fu_992_p2, "icmp_ln112_fu_992_p2");
    sc_trace(mVcdFile, icmp_ln114_fu_1008_p2, "icmp_ln114_fu_1008_p2");
    sc_trace(mVcdFile, or_ln117_fu_1026_p2, "or_ln117_fu_1026_p2");
    sc_trace(mVcdFile, select_ln117_fu_1018_p3, "select_ln117_fu_1018_p3");
    sc_trace(mVcdFile, trunc_ln117_fu_1014_p1, "trunc_ln117_fu_1014_p1");
    sc_trace(mVcdFile, grp_fu_239_opcode, "grp_fu_239_opcode");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

quantize_activation::~quantize_activation() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete attention_fadd_32pcA_U33;
    delete attention_fmul_32qcK_U34;
    delete attention_fdiv_32rcU_U35;
    delete attention_fpext_3sc4_U36;
    delete attention_fcmp_32tde_U37;
}

void quantize_activation::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void quantize_activation::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_42FE0000;
}

void quantize_activation::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && 
         esl_seteq<1,1,1>(icmp_ln99_fu_774_p2.read(), ap_const_lv1_1))) {
        j1_0_0_reg_201 = add_ln98_reg_1143.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        j1_0_0_reg_201 = ap_const_lv9_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_0_0_reg_178 = add_ln70_reg_1047.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_0_reg_178 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        l_0_0_reg_212 = add_ln99_reg_1161.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_746_p2.read()))) {
        l_0_0_reg_212 = ap_const_lv3_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        v45_0_reg_189 = select_ln80_fu_414_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        v45_0_reg_189 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln99_fu_774_p2.read()))) {
        add_ln121_reg_1171 = add_ln121_fu_800_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln70_reg_1047 = add_ln70_fu_260_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read())) {
        add_ln98_reg_1143 = add_ln98_fu_752_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        add_ln99_reg_1161 = add_ln99_fu_780_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state35.read())) {
        icmp_ln103_1_reg_1188 = icmp_ln103_1_fu_828_p2.read();
        icmp_ln103_reg_1183 = icmp_ln103_fu_822_p2.read();
        tmp_10_reg_1193 = grp_fu_239_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        icmp_ln215_1_reg_1074 = icmp_ln215_1_fu_445_p2.read();
        icmp_ln215_reg_1069 = icmp_ln215_fu_439_p2.read();
        tmp_8_reg_1079 = grp_fu_239_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        icmp_ln571_reg_1101 = icmp_ln571_fu_529_p2.read();
        icmp_ln581_reg_1107 = icmp_ln581_fu_541_p2.read();
        icmp_ln582_reg_1119 = icmp_ln582_fu_567_p2.read();
        select_ln570_reg_1096 = select_ln570_fu_521_p3.read();
        select_ln581_reg_1113 = select_ln581_fu_559_p3.read();
        tmp_12_reg_1131 = select_ln581_fu_559_p3.read().range(11, 5);
        trunc_ln583_reg_1125 = trunc_ln583_fu_573_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state41.read())) {
        p_Result_6_reg_1208 = p_Val2_s_fu_852_p1.read().range(31, 31);
        p_Val2_5_reg_1213 = p_Val2_5_fu_973_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state29.read()))) {
        reg_248 = v22_0_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state42.read())) {
        select_ln117_1_reg_1219 = select_ln117_1_fu_1032_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        select_ln603_3_reg_1136 = select_ln603_3_fu_738_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        select_ln74_reg_1057 = select_ln74_fu_323_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln98_fu_746_p2.read()))) {
        shl_ln_reg_1148 = shl_ln_fu_758_p3.read();
        zext_ln99_1_reg_1153 = zext_ln99_1_fu_766_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state33.read())) {
        v1_reg_1176 = grp_fu_227_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        v_reg_1089 = grp_fu_231_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state40.read())) {
        x_assign_reg_1203 = grp_fu_223_p2.read();
    }
}

void quantize_activation::thread_add_ln100_fu_786_p2() {
    add_ln100_fu_786_p2 = (!zext_ln99_fu_770_p1.read().is_01() || !shl_ln_reg_1148.read().is_01())? sc_lv<11>(): (sc_biguint<11>(zext_ln99_fu_770_p1.read()) + sc_biguint<11>(shl_ln_reg_1148.read()));
}

void quantize_activation::thread_add_ln121_fu_800_p2() {
    add_ln121_fu_800_p2 = (!zext_ln99_1_reg_1153.read().is_01() || !zext_ln121_fu_796_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln99_1_reg_1153.read()) + sc_biguint<12>(zext_ln121_fu_796_p1.read()));
}

void quantize_activation::thread_add_ln339_fu_895_p2() {
    add_ln339_fu_895_p2 = (!ap_const_lv9_181.is_01() || !zext_ln339_fu_891_p1.read().is_01())? sc_lv<9>(): (sc_bigint<9>(ap_const_lv9_181) + sc_biguint<9>(zext_ln339_fu_891_p1.read()));
}

void quantize_activation::thread_add_ln581_fu_547_p2() {
    add_ln581_fu_547_p2 = (!ap_const_lv12_FEC.is_01() || !sub_ln575_fu_535_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FEC) + sc_biguint<12>(sub_ln575_fu_535_p2.read()));
}

void quantize_activation::thread_add_ln70_fu_260_p2() {
    add_ln70_fu_260_p2 = (!j_0_0_reg_178.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(j_0_0_reg_178.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void quantize_activation::thread_add_ln98_fu_752_p2() {
    add_ln98_fu_752_p2 = (!j1_0_0_reg_201.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j1_0_0_reg_201.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void quantize_activation::thread_add_ln99_fu_780_p2() {
    add_ln99_fu_780_p2 = (!l_0_0_reg_212.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(l_0_0_reg_212.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void quantize_activation::thread_and_ln103_fu_838_p2() {
    and_ln103_fu_838_p2 = (or_ln103_fu_834_p2.read() & tmp_10_reg_1193.read());
}

void quantize_activation::thread_and_ln215_fu_455_p2() {
    and_ln215_fu_455_p2 = (or_ln215_fu_451_p2.read() & tmp_8_reg_1079.read());
}

void quantize_activation::thread_and_ln581_fu_657_p2() {
    and_ln581_fu_657_p2 = (icmp_ln581_reg_1107.read() & xor_ln582_fu_651_p2.read());
}

void quantize_activation::thread_and_ln582_fu_642_p2() {
    and_ln582_fu_642_p2 = (icmp_ln582_reg_1119.read() & xor_ln571_fu_637_p2.read());
}

void quantize_activation::thread_and_ln585_1_fu_674_p2() {
    and_ln585_1_fu_674_p2 = (and_ln581_fu_657_p2.read() & icmp_ln585_fu_590_p2.read());
}

void quantize_activation::thread_and_ln585_fu_668_p2() {
    and_ln585_fu_668_p2 = (and_ln581_fu_657_p2.read() & xor_ln585_fu_662_p2.read());
}

void quantize_activation::thread_and_ln603_fu_691_p2() {
    and_ln603_fu_691_p2 = (icmp_ln603_fu_595_p2.read() & xor_ln581_fu_685_p2.read());
}

void quantize_activation::thread_and_ln72_fu_307_p2() {
    and_ln72_fu_307_p2 = (or_ln72_fu_301_p2.read() & grp_fu_239_p2.read());
}

void quantize_activation::thread_and_ln79_1_fu_408_p2() {
    and_ln79_1_fu_408_p2 = (and_ln79_fu_402_p2.read() & grp_fu_239_p2.read());
}

void quantize_activation::thread_and_ln79_fu_402_p2() {
    and_ln79_fu_402_p2 = (or_ln79_fu_378_p2.read() & or_ln79_1_fu_396_p2.read());
}

void quantize_activation::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void quantize_activation::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void quantize_activation::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void quantize_activation::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void quantize_activation::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void quantize_activation::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void quantize_activation::thread_ap_CS_fsm_state27() {
    ap_CS_fsm_state27 = ap_CS_fsm.read()[26];
}

void quantize_activation::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read()[27];
}

void quantize_activation::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read()[28];
}

void quantize_activation::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void quantize_activation::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read()[29];
}

void quantize_activation::thread_ap_CS_fsm_state33() {
    ap_CS_fsm_state33 = ap_CS_fsm.read()[32];
}

void quantize_activation::thread_ap_CS_fsm_state34() {
    ap_CS_fsm_state34 = ap_CS_fsm.read()[33];
}

void quantize_activation::thread_ap_CS_fsm_state35() {
    ap_CS_fsm_state35 = ap_CS_fsm.read()[34];
}

void quantize_activation::thread_ap_CS_fsm_state36() {
    ap_CS_fsm_state36 = ap_CS_fsm.read()[35];
}

void quantize_activation::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void quantize_activation::thread_ap_CS_fsm_state40() {
    ap_CS_fsm_state40 = ap_CS_fsm.read()[39];
}

void quantize_activation::thread_ap_CS_fsm_state41() {
    ap_CS_fsm_state41 = ap_CS_fsm.read()[40];
}

void quantize_activation::thread_ap_CS_fsm_state42() {
    ap_CS_fsm_state42 = ap_CS_fsm.read()[41];
}

void quantize_activation::thread_ap_CS_fsm_state43() {
    ap_CS_fsm_state43 = ap_CS_fsm.read()[42];
}

void quantize_activation::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void quantize_activation::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void quantize_activation::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void quantize_activation::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void quantize_activation::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
          esl_seteq<1,1,1>(icmp_ln98_fu_746_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void quantize_activation::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void quantize_activation::thread_ap_phi_mux_v45_0_phi_fu_193_p4() {
    ap_phi_mux_v45_0_phi_fu_193_p4 = v45_0_reg_189.read();
}

void quantize_activation::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && 
         esl_seteq<1,1,1>(icmp_ln98_fu_746_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void quantize_activation::thread_ap_return() {
    ap_return = select_ln603_3_reg_1136.read();
}

void quantize_activation::thread_ashr_ln586_fu_604_p2() {
    ashr_ln586_fu_604_p2 = (!select_ln570_reg_1096.read().is_01() || !zext_ln586_fu_600_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(select_ln570_reg_1096.read()) >> (unsigned short)zext_ln586_fu_600_p1.read().to_uint();
}

void quantize_activation::thread_bitcast_ln103_fu_805_p1() {
    bitcast_ln103_fu_805_p1 = v1_reg_1176.read();
}

void quantize_activation::thread_bitcast_ln215_fu_421_p1() {
    bitcast_ln215_fu_421_p1 = v45_0_reg_189.read();
}

void quantize_activation::thread_bitcast_ln696_1_fu_613_p1() {
    bitcast_ln696_1_fu_613_p1 = v_reg_1089.read();
}

void quantize_activation::thread_bitcast_ln696_fu_469_p1() {
    bitcast_ln696_fu_469_p1 = grp_fu_236_p1.read();
}

void quantize_activation::thread_bitcast_ln72_fu_271_p1() {
    bitcast_ln72_fu_271_p1 = reg_248.read();
}

void quantize_activation::thread_bitcast_ln73_fu_319_p1() {
    bitcast_ln73_fu_319_p1 = xor_ln73_fu_313_p2.read();
}

void quantize_activation::thread_bitcast_ln79_1_fu_349_p1() {
    bitcast_ln79_1_fu_349_p1 = select_ln74_reg_1057.read();
}

void quantize_activation::thread_bitcast_ln79_fu_331_p1() {
    bitcast_ln79_fu_331_p1 = v45_0_reg_189.read();
}

void quantize_activation::thread_grp_fu_223_p1() {
    grp_fu_223_p1 = (!and_ln103_fu_838_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln103_fu_838_p2.read()[0].to_bool())? ap_const_lv32_3F000000: ap_const_lv32_BF000000);
}

void quantize_activation::thread_grp_fu_231_p1() {
    grp_fu_231_p1 = (!and_ln215_fu_455_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln215_fu_455_p2.read()[0].to_bool())? ap_const_lv32_3727C5AC: v45_0_reg_189.read());
}

void quantize_activation::thread_grp_fu_239_opcode() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()))) {
        grp_fu_239_opcode = ap_const_lv5_2;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 esl_seteq<1,1,1>(icmp_ln70_fu_254_p2.read(), ap_const_lv1_1)))) {
        grp_fu_239_opcode = ap_const_lv5_4;
    } else {
        grp_fu_239_opcode = "XXXXX";
    }
}

void quantize_activation::thread_grp_fu_239_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read())) {
        grp_fu_239_p0 = v1_reg_1176.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_239_p0 = v45_0_reg_189.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        grp_fu_239_p0 = v22_0_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_239_p0 = ap_phi_mux_v45_0_phi_fu_193_p4.read();
    } else {
        grp_fu_239_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void quantize_activation::thread_grp_fu_239_p1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        grp_fu_239_p1 = select_ln74_reg_1057.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state34.read()))) {
        grp_fu_239_p1 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        grp_fu_239_p1 = ap_const_lv32_3727C5AC;
    } else {
        grp_fu_239_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void quantize_activation::thread_icmp_ln103_1_fu_828_p2() {
    icmp_ln103_1_fu_828_p2 = (!trunc_ln103_fu_818_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln103_fu_818_p1.read() == ap_const_lv23_0);
}

void quantize_activation::thread_icmp_ln103_fu_822_p2() {
    icmp_ln103_fu_822_p2 = (!tmp_4_fu_808_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_4_fu_808_p4.read() != ap_const_lv8_FF);
}

void quantize_activation::thread_icmp_ln112_fu_992_p2() {
    icmp_ln112_fu_992_p2 = (!p_Val2_6_fu_986_p3.read().is_01() || !ap_const_lv32_FFFFFF80.is_01())? sc_lv<1>(): (sc_bigint<32>(p_Val2_6_fu_986_p3.read()) < sc_bigint<32>(ap_const_lv32_FFFFFF80));
}

void quantize_activation::thread_icmp_ln114_fu_1008_p2() {
    icmp_ln114_fu_1008_p2 = (!tmp_17_fu_998_p4.read().is_01() || !ap_const_lv25_0.is_01())? sc_lv<1>(): (sc_bigint<25>(tmp_17_fu_998_p4.read()) > sc_bigint<25>(ap_const_lv25_0));
}

void quantize_activation::thread_icmp_ln215_1_fu_445_p2() {
    icmp_ln215_1_fu_445_p2 = (!trunc_ln215_fu_435_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln215_fu_435_p1.read() == ap_const_lv23_0);
}

void quantize_activation::thread_icmp_ln215_fu_439_p2() {
    icmp_ln215_fu_439_p2 = (!tmp_7_fu_425_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_7_fu_425_p4.read() != ap_const_lv8_FF);
}

void quantize_activation::thread_icmp_ln571_fu_529_p2() {
    icmp_ln571_fu_529_p2 = (!trunc_ln557_fu_473_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln557_fu_473_p1.read() == ap_const_lv63_0);
}

void quantize_activation::thread_icmp_ln581_fu_541_p2() {
    icmp_ln581_fu_541_p2 = (!sub_ln575_fu_535_p2.read().is_01() || !ap_const_lv12_14.is_01())? sc_lv<1>(): (sc_bigint<12>(sub_ln575_fu_535_p2.read()) > sc_bigint<12>(ap_const_lv12_14));
}

void quantize_activation::thread_icmp_ln582_fu_567_p2() {
    icmp_ln582_fu_567_p2 = (!sub_ln575_fu_535_p2.read().is_01() || !ap_const_lv12_14.is_01())? sc_lv<1>(): sc_lv<1>(sub_ln575_fu_535_p2.read() == ap_const_lv12_14);
}

void quantize_activation::thread_icmp_ln585_fu_590_p2() {
    icmp_ln585_fu_590_p2 = (!select_ln581_reg_1113.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(select_ln581_reg_1113.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void quantize_activation::thread_icmp_ln603_fu_595_p2() {
    icmp_ln603_fu_595_p2 = (!tmp_12_reg_1131.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_12_reg_1131.read() == ap_const_lv7_0);
}

void quantize_activation::thread_icmp_ln70_fu_254_p2() {
    icmp_ln70_fu_254_p2 = (!j_0_0_reg_178.read().is_01() || !ap_const_lv11_600.is_01())? sc_lv<1>(): sc_lv<1>(j_0_0_reg_178.read() == ap_const_lv11_600);
}

void quantize_activation::thread_icmp_ln72_1_fu_295_p2() {
    icmp_ln72_1_fu_295_p2 = (!trunc_ln72_fu_285_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln72_fu_285_p1.read() == ap_const_lv23_0);
}

void quantize_activation::thread_icmp_ln72_fu_289_p2() {
    icmp_ln72_fu_289_p2 = (!tmp_9_fu_275_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_9_fu_275_p4.read() != ap_const_lv8_FF);
}

void quantize_activation::thread_icmp_ln79_1_fu_372_p2() {
    icmp_ln79_1_fu_372_p2 = (!trunc_ln79_fu_345_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln79_fu_345_p1.read() == ap_const_lv23_0);
}

void quantize_activation::thread_icmp_ln79_2_fu_384_p2() {
    icmp_ln79_2_fu_384_p2 = (!tmp_2_fu_352_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_2_fu_352_p4.read() != ap_const_lv8_FF);
}

void quantize_activation::thread_icmp_ln79_3_fu_390_p2() {
    icmp_ln79_3_fu_390_p2 = (!trunc_ln79_1_fu_362_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln79_1_fu_362_p1.read() == ap_const_lv23_0);
}

void quantize_activation::thread_icmp_ln79_fu_366_p2() {
    icmp_ln79_fu_366_p2 = (!tmp_1_fu_335_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_1_fu_335_p4.read() != ap_const_lv8_FF);
}

void quantize_activation::thread_icmp_ln98_fu_746_p2() {
    icmp_ln98_fu_746_p2 = (!j1_0_0_reg_201.read().is_01() || !ap_const_lv9_180.is_01())? sc_lv<1>(): sc_lv<1>(j1_0_0_reg_201.read() == ap_const_lv9_180);
}

void quantize_activation::thread_icmp_ln99_fu_774_p2() {
    icmp_ln99_fu_774_p2 = (!l_0_0_reg_212.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(l_0_0_reg_212.read() == ap_const_lv3_4);
}

void quantize_activation::thread_isNeg_fu_901_p3() {
    isNeg_fu_901_p3 = add_ln339_fu_895_p2.read().range(8, 8);
}

void quantize_activation::thread_mantissa_V_fu_877_p4() {
    mantissa_V_fu_877_p4 = esl_concat<24,1>(esl_concat<1,23>(ap_const_lv1_1, tmp_V_1_fu_873_p1.read()), ap_const_lv1_0);
}

void quantize_activation::thread_or_ln103_fu_834_p2() {
    or_ln103_fu_834_p2 = (icmp_ln103_1_reg_1188.read() | icmp_ln103_reg_1183.read());
}

void quantize_activation::thread_or_ln117_fu_1026_p2() {
    or_ln117_fu_1026_p2 = (icmp_ln112_fu_992_p2.read() | icmp_ln114_fu_1008_p2.read());
}

void quantize_activation::thread_or_ln215_fu_451_p2() {
    or_ln215_fu_451_p2 = (icmp_ln215_1_reg_1074.read() | icmp_ln215_reg_1069.read());
}

void quantize_activation::thread_or_ln581_fu_680_p2() {
    or_ln581_fu_680_p2 = (or_ln582_fu_647_p2.read() | icmp_ln581_reg_1107.read());
}

void quantize_activation::thread_or_ln582_fu_647_p2() {
    or_ln582_fu_647_p2 = (icmp_ln571_reg_1101.read() | icmp_ln582_reg_1119.read());
}

void quantize_activation::thread_or_ln603_1_fu_718_p2() {
    or_ln603_1_fu_718_p2 = (and_ln585_fu_668_p2.read() | and_ln582_fu_642_p2.read());
}

void quantize_activation::thread_or_ln603_2_fu_732_p2() {
    or_ln603_2_fu_732_p2 = (or_ln603_fu_705_p2.read() | or_ln603_1_fu_718_p2.read());
}

void quantize_activation::thread_or_ln603_fu_705_p2() {
    or_ln603_fu_705_p2 = (and_ln603_fu_691_p2.read() | and_ln585_1_fu_674_p2.read());
}

void quantize_activation::thread_or_ln72_fu_301_p2() {
    or_ln72_fu_301_p2 = (icmp_ln72_1_fu_295_p2.read() | icmp_ln72_fu_289_p2.read());
}

void quantize_activation::thread_or_ln79_1_fu_396_p2() {
    or_ln79_1_fu_396_p2 = (icmp_ln79_3_fu_390_p2.read() | icmp_ln79_2_fu_384_p2.read());
}

void quantize_activation::thread_or_ln79_fu_378_p2() {
    or_ln79_fu_378_p2 = (icmp_ln79_1_fu_372_p2.read() | icmp_ln79_fu_366_p2.read());
}

void quantize_activation::thread_p_Result_s_fu_485_p4() {
    p_Result_s_fu_485_p4 = bitcast_ln696_fu_469_p1.read().range(62, 52);
}

void quantize_activation::thread_p_Val2_5_fu_973_p3() {
    p_Val2_5_fu_973_p3 = (!isNeg_fu_901_p3.read()[0].is_01())? sc_lv<32>(): ((isNeg_fu_901_p3.read()[0].to_bool())? zext_ln662_fu_959_p1.read(): tmp_14_fu_963_p4.read());
}

void quantize_activation::thread_p_Val2_6_fu_986_p3() {
    p_Val2_6_fu_986_p3 = (!p_Result_6_reg_1208.read()[0].is_01())? sc_lv<32>(): ((p_Result_6_reg_1208.read()[0].to_bool())? result_V_1_fu_981_p2.read(): p_Val2_5_reg_1213.read());
}

void quantize_activation::thread_p_Val2_s_fu_852_p1() {
    p_Val2_s_fu_852_p1 = x_assign_reg_1203.read();
}

void quantize_activation::thread_r_V_1_fu_945_p2() {
    r_V_1_fu_945_p2 = (!zext_ln1287_fu_935_p1.read().is_01())? sc_lv<79>(): zext_ln682_fu_887_p1.read() << (unsigned short)zext_ln1287_fu_935_p1.read().to_uint();
}

void quantize_activation::thread_r_V_fu_939_p2() {
    r_V_fu_939_p2 = (!sext_ln1311_2_fu_931_p1.read().is_01())? sc_lv<25>(): mantissa_V_fu_877_p4.read() >> (unsigned short)sext_ln1311_2_fu_931_p1.read().to_uint();
}

void quantize_activation::thread_result_V_1_fu_981_p2() {
    result_V_1_fu_981_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_5_reg_1213.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_5_reg_1213.read()));
}

void quantize_activation::thread_select_ln117_1_fu_1032_p3() {
    select_ln117_1_fu_1032_p3 = (!or_ln117_fu_1026_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln117_fu_1026_p2.read()[0].to_bool())? select_ln117_fu_1018_p3.read(): trunc_ln117_fu_1014_p1.read());
}

void quantize_activation::thread_select_ln117_fu_1018_p3() {
    select_ln117_fu_1018_p3 = (!icmp_ln112_fu_992_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln112_fu_992_p2.read()[0].to_bool())? ap_const_lv8_80: ap_const_lv8_7F);
}

void quantize_activation::thread_select_ln570_fu_521_p3() {
    select_ln570_fu_521_p3 = (!tmp_11_fu_477_p3.read()[0].is_01())? sc_lv<54>(): ((tmp_11_fu_477_p3.read()[0].to_bool())? sub_ln461_fu_515_p2.read(): zext_ln569_fu_511_p1.read());
}

void quantize_activation::thread_select_ln581_fu_559_p3() {
    select_ln581_fu_559_p3 = (!icmp_ln581_fu_541_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln581_fu_541_p2.read()[0].to_bool())? add_ln581_fu_547_p2.read(): sub_ln581_fu_553_p2.read());
}

void quantize_activation::thread_select_ln588_fu_624_p3() {
    select_ln588_fu_624_p3 = (!tmp_13_fu_616_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_13_fu_616_p3.read()[0].to_bool())? ap_const_lv32_FFFFFFFF: ap_const_lv32_0);
}

void quantize_activation::thread_select_ln603_1_fu_711_p3() {
    select_ln603_1_fu_711_p3 = (!and_ln585_fu_668_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln585_fu_668_p2.read()[0].to_bool())? select_ln588_fu_624_p3.read(): trunc_ln583_reg_1125.read());
}

void quantize_activation::thread_select_ln603_2_fu_724_p3() {
    select_ln603_2_fu_724_p3 = (!or_ln603_fu_705_p2.read()[0].is_01())? sc_lv<32>(): ((or_ln603_fu_705_p2.read()[0].to_bool())? select_ln603_fu_697_p3.read(): select_ln603_1_fu_711_p3.read());
}

void quantize_activation::thread_select_ln603_3_fu_738_p3() {
    select_ln603_3_fu_738_p3 = (!or_ln603_2_fu_732_p2.read()[0].is_01())? sc_lv<32>(): ((or_ln603_2_fu_732_p2.read()[0].to_bool())? select_ln603_2_fu_724_p3.read(): ap_const_lv32_0);
}

void quantize_activation::thread_select_ln603_fu_697_p3() {
    select_ln603_fu_697_p3 = (!and_ln603_fu_691_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln603_fu_691_p2.read()[0].to_bool())? shl_ln604_fu_632_p2.read(): trunc_ln586_fu_609_p1.read());
}

void quantize_activation::thread_select_ln74_fu_323_p3() {
    select_ln74_fu_323_p3 = (!and_ln72_fu_307_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln72_fu_307_p2.read()[0].to_bool())? reg_248.read(): bitcast_ln73_fu_319_p1.read());
}

void quantize_activation::thread_select_ln80_fu_414_p3() {
    select_ln80_fu_414_p3 = (!and_ln79_1_fu_408_p2.read()[0].is_01())? sc_lv<32>(): ((and_ln79_1_fu_408_p2.read()[0].to_bool())? select_ln74_reg_1057.read(): v45_0_reg_189.read());
}

void quantize_activation::thread_sext_ln1311_1_fu_927_p1() {
    sext_ln1311_1_fu_927_p1 = esl_sext<32,9>(ush_fu_919_p3.read());
}

void quantize_activation::thread_sext_ln1311_2_fu_931_p1() {
    sext_ln1311_2_fu_931_p1 = esl_sext<25,9>(ush_fu_919_p3.read());
}

void quantize_activation::thread_sext_ln1311_fu_915_p1() {
    sext_ln1311_fu_915_p1 = esl_sext<9,8>(sub_ln1311_fu_909_p2.read());
}

void quantize_activation::thread_sext_ln581_fu_587_p1() {
    sext_ln581_fu_587_p1 = esl_sext<32,12>(select_ln581_reg_1113.read());
}

void quantize_activation::thread_shl_ln604_fu_632_p2() {
    shl_ln604_fu_632_p2 = (!sext_ln581_fu_587_p1.read().is_01())? sc_lv<32>(): trunc_ln583_reg_1125.read() << (unsigned short)sext_ln581_fu_587_p1.read().to_uint();
}

void quantize_activation::thread_shl_ln_fu_758_p3() {
    shl_ln_fu_758_p3 = esl_concat<9,2>(j1_0_0_reg_201.read(), ap_const_lv2_0);
}

void quantize_activation::thread_sub_ln1311_fu_909_p2() {
    sub_ln1311_fu_909_p2 = (!ap_const_lv8_7F.is_01() || !tmp_V_fu_863_p4.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_7F) - sc_biguint<8>(tmp_V_fu_863_p4.read()));
}

void quantize_activation::thread_sub_ln461_fu_515_p2() {
    sub_ln461_fu_515_p2 = (!ap_const_lv54_0.is_01() || !zext_ln569_fu_511_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(zext_ln569_fu_511_p1.read()));
}

void quantize_activation::thread_sub_ln575_fu_535_p2() {
    sub_ln575_fu_535_p2 = (!ap_const_lv12_433.is_01() || !zext_ln461_fu_495_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(zext_ln461_fu_495_p1.read()));
}

void quantize_activation::thread_sub_ln581_fu_553_p2() {
    sub_ln581_fu_553_p2 = (!ap_const_lv12_14.is_01() || !sub_ln575_fu_535_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_14) - sc_biguint<12>(sub_ln575_fu_535_p2.read()));
}

void quantize_activation::thread_tmp_11_fu_477_p3() {
    tmp_11_fu_477_p3 = bitcast_ln696_fu_469_p1.read().range(63, 63);
}

void quantize_activation::thread_tmp_13_fu_616_p3() {
    tmp_13_fu_616_p3 = bitcast_ln696_1_fu_613_p1.read().range(31, 31);
}

void quantize_activation::thread_tmp_14_fu_963_p4() {
    tmp_14_fu_963_p4 = r_V_1_fu_945_p2.read().range(55, 24);
}

void quantize_activation::thread_tmp_16_fu_951_p3() {
    tmp_16_fu_951_p3 = r_V_fu_939_p2.read().range(24, 24);
}

void quantize_activation::thread_tmp_17_fu_998_p4() {
    tmp_17_fu_998_p4 = p_Val2_6_fu_986_p3.read().range(31, 7);
}

void quantize_activation::thread_tmp_1_fu_335_p4() {
    tmp_1_fu_335_p4 = bitcast_ln79_fu_331_p1.read().range(30, 23);
}

void quantize_activation::thread_tmp_2_fu_352_p4() {
    tmp_2_fu_352_p4 = bitcast_ln79_1_fu_349_p1.read().range(30, 23);
}

void quantize_activation::thread_tmp_4_fu_808_p4() {
    tmp_4_fu_808_p4 = bitcast_ln103_fu_805_p1.read().range(30, 23);
}

void quantize_activation::thread_tmp_5_fu_503_p3() {
    tmp_5_fu_503_p3 = esl_concat<1,52>(ap_const_lv1_1, trunc_ln565_fu_499_p1.read());
}

void quantize_activation::thread_tmp_7_fu_425_p4() {
    tmp_7_fu_425_p4 = bitcast_ln215_fu_421_p1.read().range(30, 23);
}

void quantize_activation::thread_tmp_9_fu_275_p4() {
    tmp_9_fu_275_p4 = bitcast_ln72_fu_271_p1.read().range(30, 23);
}

void quantize_activation::thread_tmp_V_1_fu_873_p1() {
    tmp_V_1_fu_873_p1 = p_Val2_s_fu_852_p1.read().range(23-1, 0);
}

void quantize_activation::thread_tmp_V_fu_863_p4() {
    tmp_V_fu_863_p4 = p_Val2_s_fu_852_p1.read().range(30, 23);
}

void quantize_activation::thread_trunc_ln103_fu_818_p1() {
    trunc_ln103_fu_818_p1 = bitcast_ln103_fu_805_p1.read().range(23-1, 0);
}

void quantize_activation::thread_trunc_ln117_fu_1014_p1() {
    trunc_ln117_fu_1014_p1 = p_Val2_6_fu_986_p3.read().range(8-1, 0);
}

void quantize_activation::thread_trunc_ln215_fu_435_p1() {
    trunc_ln215_fu_435_p1 = bitcast_ln215_fu_421_p1.read().range(23-1, 0);
}

void quantize_activation::thread_trunc_ln557_fu_473_p1() {
    trunc_ln557_fu_473_p1 = bitcast_ln696_fu_469_p1.read().range(63-1, 0);
}

void quantize_activation::thread_trunc_ln565_fu_499_p1() {
    trunc_ln565_fu_499_p1 = bitcast_ln696_fu_469_p1.read().range(52-1, 0);
}

void quantize_activation::thread_trunc_ln583_fu_573_p1() {
    trunc_ln583_fu_573_p1 = select_ln570_fu_521_p3.read().range(32-1, 0);
}

void quantize_activation::thread_trunc_ln586_fu_609_p1() {
    trunc_ln586_fu_609_p1 = ashr_ln586_fu_604_p2.read().range(32-1, 0);
}

void quantize_activation::thread_trunc_ln72_fu_285_p1() {
    trunc_ln72_fu_285_p1 = bitcast_ln72_fu_271_p1.read().range(23-1, 0);
}

void quantize_activation::thread_trunc_ln79_1_fu_362_p1() {
    trunc_ln79_1_fu_362_p1 = bitcast_ln79_1_fu_349_p1.read().range(23-1, 0);
}

void quantize_activation::thread_trunc_ln79_fu_345_p1() {
    trunc_ln79_fu_345_p1 = bitcast_ln79_fu_331_p1.read().range(23-1, 0);
}

void quantize_activation::thread_ush_fu_919_p3() {
    ush_fu_919_p3 = (!isNeg_fu_901_p3.read()[0].is_01())? sc_lv<9>(): ((isNeg_fu_901_p3.read()[0].to_bool())? sext_ln1311_fu_915_p1.read(): add_ln339_fu_895_p2.read());
}

void quantize_activation::thread_v22_0_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read())) {
        v22_0_address0 =  (sc_lv<11>) (zext_ln100_fu_791_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        v22_0_address0 =  (sc_lv<11>) (zext_ln71_fu_266_p1.read());
    } else {
        v22_0_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void quantize_activation::thread_v22_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()))) {
        v22_0_ce0 = ap_const_logic_1;
    } else {
        v22_0_ce0 = ap_const_logic_0;
    }
}

void quantize_activation::thread_v24_0_address0() {
    v24_0_address0 =  (sc_lv<11>) (zext_ln121_1_fu_1040_p1.read());
}

void quantize_activation::thread_v24_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        v24_0_ce0 = ap_const_logic_1;
    } else {
        v24_0_ce0 = ap_const_logic_0;
    }
}

void quantize_activation::thread_v24_0_d0() {
    v24_0_d0 = select_ln117_1_reg_1219.read();
}

void quantize_activation::thread_v24_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state43.read())) {
        v24_0_we0 = ap_const_logic_1;
    } else {
        v24_0_we0 = ap_const_logic_0;
    }
}

void quantize_activation::thread_xor_ln571_fu_637_p2() {
    xor_ln571_fu_637_p2 = (icmp_ln571_reg_1101.read() ^ ap_const_lv1_1);
}

void quantize_activation::thread_xor_ln581_fu_685_p2() {
    xor_ln581_fu_685_p2 = (or_ln581_fu_680_p2.read() ^ ap_const_lv1_1);
}

void quantize_activation::thread_xor_ln582_fu_651_p2() {
    xor_ln582_fu_651_p2 = (or_ln582_fu_647_p2.read() ^ ap_const_lv1_1);
}

void quantize_activation::thread_xor_ln585_fu_662_p2() {
    xor_ln585_fu_662_p2 = (icmp_ln585_fu_590_p2.read() ^ ap_const_lv1_1);
}

void quantize_activation::thread_xor_ln73_fu_313_p2() {
    xor_ln73_fu_313_p2 = (bitcast_ln72_fu_271_p1.read() ^ ap_const_lv32_80000000);
}

void quantize_activation::thread_zext_ln100_fu_791_p1() {
    zext_ln100_fu_791_p1 = esl_zext<64,11>(add_ln100_fu_786_p2.read());
}

void quantize_activation::thread_zext_ln121_1_fu_1040_p1() {
    zext_ln121_1_fu_1040_p1 = esl_zext<64,12>(add_ln121_reg_1171.read());
}

void quantize_activation::thread_zext_ln121_fu_796_p1() {
    zext_ln121_fu_796_p1 = esl_zext<12,3>(l_0_0_reg_212.read());
}

void quantize_activation::thread_zext_ln1287_fu_935_p1() {
    zext_ln1287_fu_935_p1 = esl_zext<79,32>(sext_ln1311_1_fu_927_p1.read());
}

void quantize_activation::thread_zext_ln339_fu_891_p1() {
    zext_ln339_fu_891_p1 = esl_zext<9,8>(tmp_V_fu_863_p4.read());
}

void quantize_activation::thread_zext_ln461_fu_495_p1() {
    zext_ln461_fu_495_p1 = esl_zext<12,11>(p_Result_s_fu_485_p4.read());
}

void quantize_activation::thread_zext_ln569_fu_511_p1() {
    zext_ln569_fu_511_p1 = esl_zext<54,53>(tmp_5_fu_503_p3.read());
}

void quantize_activation::thread_zext_ln586_fu_600_p1() {
    zext_ln586_fu_600_p1 = esl_zext<54,32>(sext_ln581_fu_587_p1.read());
}

void quantize_activation::thread_zext_ln662_fu_959_p1() {
    zext_ln662_fu_959_p1 = esl_zext<32,1>(tmp_16_fu_951_p3.read());
}

void quantize_activation::thread_zext_ln682_fu_887_p1() {
    zext_ln682_fu_887_p1 = esl_zext<79,25>(mantissa_V_fu_877_p4.read());
}

void quantize_activation::thread_zext_ln71_fu_266_p1() {
    zext_ln71_fu_266_p1 = esl_zext<64,11>(j_0_0_reg_178.read());
}

void quantize_activation::thread_zext_ln99_1_fu_766_p1() {
    zext_ln99_1_fu_766_p1 = esl_zext<12,11>(shl_ln_fu_758_p3.read());
}

void quantize_activation::thread_zext_ln99_fu_770_p1() {
    zext_ln99_fu_770_p1 = esl_zext<11,3>(l_0_0_reg_212.read());
}

void quantize_activation::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln70_fu_254_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state27.read()) && esl_seteq<1,1,1>(icmp_ln98_fu_746_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state28;
            }
            break;
        case 134217728 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state28.read()) && esl_seteq<1,1,1>(icmp_ln99_fu_774_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state27;
            } else {
                ap_NS_fsm = ap_ST_fsm_state29;
            }
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 274877906944 : 
            ap_NS_fsm = ap_ST_fsm_state40;
            break;
        case 549755813888 : 
            ap_NS_fsm = ap_ST_fsm_state41;
            break;
        case 1099511627776 : 
            ap_NS_fsm = ap_ST_fsm_state42;
            break;
        case 2199023255552 : 
            ap_NS_fsm = ap_ST_fsm_state43;
            break;
        case 4398046511104 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<43>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

