-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity quantize_activation is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_V_address0 : OUT STD_LOGIC_VECTOR (8 downto 0);
    input_0_V_ce0 : OUT STD_LOGIC;
    input_0_V_q0 : IN STD_LOGIC_VECTOR (39 downto 0);
    output_states_0_0_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    output_states_0_0_V_ce0 : OUT STD_LOGIC;
    output_states_0_0_V_we0 : OUT STD_LOGIC;
    output_states_0_0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_states_1_0_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    output_states_1_0_V_ce0 : OUT STD_LOGIC;
    output_states_1_0_V_we0 : OUT STD_LOGIC;
    output_states_1_0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_states_2_0_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    output_states_2_0_V_ce0 : OUT STD_LOGIC;
    output_states_2_0_V_we0 : OUT STD_LOGIC;
    output_states_2_0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_states_3_0_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    output_states_3_0_V_ce0 : OUT STD_LOGIC;
    output_states_3_0_V_we0 : OUT STD_LOGIC;
    output_states_3_0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (39 downto 0) );
end;


architecture behav of quantize_activation is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000100000000000000000000000000";
    constant ap_ST_fsm_state28 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000001000000000000000000000000000";
    constant ap_ST_fsm_state29 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000010000000000000000000000000000";
    constant ap_ST_fsm_state30 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000100000000000000000000000000000";
    constant ap_ST_fsm_state31 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000001000000000000000000000000000000";
    constant ap_ST_fsm_state32 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000010000000000000000000000000000000";
    constant ap_ST_fsm_state33 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000100000000000000000000000000000000";
    constant ap_ST_fsm_state34 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000001000000000000000000000000000000000";
    constant ap_ST_fsm_state35 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000010000000000000000000000000000000000";
    constant ap_ST_fsm_state36 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000100000000000000000000000000000000000";
    constant ap_ST_fsm_state37 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000001000000000000000000000000000000000000";
    constant ap_ST_fsm_state38 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000010000000000000000000000000000000000000";
    constant ap_ST_fsm_state39 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000100000000000000000000000000000000000000";
    constant ap_ST_fsm_state40 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000001000000000000000000000000000000000000000";
    constant ap_ST_fsm_state41 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000010000000000000000000000000000000000000000";
    constant ap_ST_fsm_state42 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000100000000000000000000000000000000000000000";
    constant ap_ST_fsm_state43 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000001000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state44 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000010000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state45 : STD_LOGIC_VECTOR (55 downto 0) := "00000000000100000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state46 : STD_LOGIC_VECTOR (55 downto 0) := "00000000001000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state47 : STD_LOGIC_VECTOR (55 downto 0) := "00000000010000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state48 : STD_LOGIC_VECTOR (55 downto 0) := "00000000100000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state49 : STD_LOGIC_VECTOR (55 downto 0) := "00000001000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state50 : STD_LOGIC_VECTOR (55 downto 0) := "00000010000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state51 : STD_LOGIC_VECTOR (55 downto 0) := "00000100000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state52 : STD_LOGIC_VECTOR (55 downto 0) := "00001000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state53 : STD_LOGIC_VECTOR (55 downto 0) := "00010000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state54 : STD_LOGIC_VECTOR (55 downto 0) := "00100000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state55 : STD_LOGIC_VECTOR (55 downto 0) := "01000000000000000000000000000000000000000000000000000000";
    constant ap_ST_fsm_state56 : STD_LOGIC_VECTOR (55 downto 0) := "10000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_32 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110010";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv40_0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    constant ap_const_lv9_180 : STD_LOGIC_VECTOR (8 downto 0) := "110000000";
    constant ap_const_lv40_7F00000000 : STD_LOGIC_VECTOR (39 downto 0) := "0111111100000000000000000000000000000000";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv40_8000 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000001000000000000000";
    constant ap_const_lv40_FFFFFF8000 : STD_LOGIC_VECTOR (39 downto 0) := "1111111111111111111111111000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv24_1 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv24_FFFF80 : STD_LOGIC_VECTOR (23 downto 0) := "111111111111111110000000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (55 downto 0) := "00000000000000000000000000000000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_fu_252_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal p_Val2_10_reg_526 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln128_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln128_fu_271_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln128_reg_539 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_12_reg_544 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_Val2_13_fu_288_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_277_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal udiv_ln1148_reg_555 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state49 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state49 : signal is "none";
    signal zext_ln135_fu_295_p1 : STD_LOGIC_VECTOR (55 downto 0);
    signal zext_ln135_reg_559 : STD_LOGIC_VECTOR (55 downto 0);
    signal add_ln135_fu_305_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln135_reg_567 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state50 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state50 : signal is "none";
    signal shl_ln_fu_311_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln_reg_572 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln135_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln136_fu_329_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln136_reg_580 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state51 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state51 : signal is "none";
    signal shl_ln1_fu_340_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln1_reg_585 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln136_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_states_0_0_s_reg_590 : STD_LOGIC_VECTOR (6 downto 0);
    signal output_states_1_0_s_reg_595 : STD_LOGIC_VECTOR (6 downto 0);
    signal output_states_2_0_s_reg_600 : STD_LOGIC_VECTOR (6 downto 0);
    signal output_states_3_0_s_reg_605 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln138_fu_366_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln138_reg_613 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state52 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state52 : signal is "none";
    signal icmp_ln138_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln180_fu_382_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln180_reg_623 : STD_LOGIC_VECTOR (1 downto 0);
    signal input_0_V_load_reg_627 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state53 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state53 : signal is "none";
    signal p_Val2_9_reg_632 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state54 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state54 : signal is "none";
    signal select_ln850_fu_464_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal select_ln850_reg_638 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state55 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state55 : signal is "none";
    signal tmp_76_reg_644 : STD_LOGIC_VECTOR (16 downto 0);
    signal max_val_V_0_0_reg_184 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal j_0_0_reg_194 : STD_LOGIC_VECTOR (8 downto 0);
    signal jo_0_0_reg_205 : STD_LOGIC_VECTOR (2 downto 0);
    signal ji_0_0_reg_216 : STD_LOGIC_VECTOR (4 downto 0);
    signal k_0_0_reg_227 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state56 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state56 : signal is "none";
    signal zext_ln129_fu_266_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln141_fu_348_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln139_fu_377_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln887_1_fu_509_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_238_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_246_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal icmp_ln1494_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln136_fu_319_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln137_fu_335_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln138_fu_356_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln139_fu_372_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln1118_fu_389_p0 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln1118_fu_389_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal mul_ln1118_fu_389_p2 : STD_LOGIC_VECTOR (55 downto 0);
    signal icmp_ln1494_26_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln108_fu_409_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal add_ln108_fu_417_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal trunc_ln851_fu_440_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Result_s_fu_422_p4 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln851_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_fu_450_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_75_fu_432_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_fu_456_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal icmp_ln887_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln895_fu_487_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln887_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln887_fu_495_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln140_fu_492_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_277_ap_start : STD_LOGIC;
    signal grp_fu_277_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (55 downto 0);

    component dut_udiv_40ns_40neOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (39 downto 0);
        din1 : IN STD_LOGIC_VECTOR (39 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (39 downto 0) );
    end component;



begin
    dut_udiv_40ns_40neOg_U14 : component dut_udiv_40ns_40neOg
    generic map (
        ID => 1,
        NUM_STAGE => 44,
        din0_WIDTH => 40,
        din1_WIDTH => 40,
        dout_WIDTH => 40)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_277_ap_start,
        done => grp_fu_277_ap_done,
        din0 => ap_const_lv40_7F00000000,
        din1 => max_val_V_0_0_reg_184,
        ce => ap_const_logic_1,
        dout => grp_fu_277_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    j_0_0_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_0_0_reg_194 <= add_ln128_reg_539;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                j_0_0_reg_194 <= ap_const_lv9_1;
            end if; 
        end if;
    end process;

    ji_0_0_reg_216_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state52) and (icmp_ln138_fu_360_p2 = ap_const_lv1_1))) then 
                ji_0_0_reg_216 <= add_ln136_reg_580;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state50) and (icmp_ln135_fu_299_p2 = ap_const_lv1_0))) then 
                ji_0_0_reg_216 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    jo_0_0_reg_205_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state51) and (icmp_ln136_fu_323_p2 = ap_const_lv1_1))) then 
                jo_0_0_reg_205 <= add_ln135_reg_567;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state49)) then 
                jo_0_0_reg_205 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    k_0_0_reg_227_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
                k_0_0_reg_227 <= add_ln138_reg_613;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state51) and (icmp_ln136_fu_323_p2 = ap_const_lv1_0))) then 
                k_0_0_reg_227 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    max_val_V_0_0_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                max_val_V_0_0_reg_184 <= p_Val2_13_fu_288_p3;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                max_val_V_0_0_reg_184 <= p_Val2_10_reg_526;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_260_p2 = ap_const_lv1_0))) then
                add_ln128_reg_539 <= add_ln128_fu_271_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state50)) then
                add_ln135_reg_567 <= add_ln135_fu_305_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state51)) then
                add_ln136_reg_580 <= add_ln136_fu_329_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state52)) then
                add_ln138_reg_613 <= add_ln138_fu_366_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state53)) then
                input_0_V_load_reg_627 <= input_0_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state51) and (icmp_ln136_fu_323_p2 = ap_const_lv1_0))) then
                output_states_0_0_s_reg_590 <= zext_ln141_fu_348_p1(7 - 1 downto 0);
                output_states_1_0_s_reg_595 <= zext_ln141_fu_348_p1(7 - 1 downto 0);
                output_states_2_0_s_reg_600 <= zext_ln141_fu_348_p1(7 - 1 downto 0);
                output_states_3_0_s_reg_605 <= zext_ln141_fu_348_p1(7 - 1 downto 0);
                    shl_ln1_reg_585(8 downto 2) <= shl_ln1_fu_340_p3(8 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_Val2_10_reg_526 <= grp_fu_252_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                p_Val2_12_reg_544 <= grp_fu_252_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state54)) then
                p_Val2_9_reg_632 <= mul_ln1118_fu_389_p2(55 downto 16);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state55)) then
                select_ln850_reg_638 <= select_ln850_fu_464_p3;
                tmp_76_reg_644 <= select_ln850_fu_464_p3(23 downto 7);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state50) and (icmp_ln135_fu_299_p2 = ap_const_lv1_0))) then
                    shl_ln_reg_572(6 downto 4) <= shl_ln_fu_311_p3(6 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state52) and (icmp_ln138_fu_360_p2 = ap_const_lv1_0))) then
                trunc_ln180_reg_623 <= trunc_ln180_fu_382_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state49)) then
                udiv_ln1148_reg_555 <= grp_fu_277_p2;
                    zext_ln135_reg_559(39 downto 0) <= zext_ln135_fu_295_p1(39 downto 0);
            end if;
        end if;
    end process;
    zext_ln135_reg_559(55 downto 40) <= "0000000000000000";
    shl_ln_reg_572(3 downto 0) <= "0000";
    shl_ln1_reg_585(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state4, icmp_ln128_fu_260_p2, ap_CS_fsm_state50, icmp_ln135_fu_299_p2, ap_CS_fsm_state51, icmp_ln136_fu_323_p2, ap_CS_fsm_state52, icmp_ln138_fu_360_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_260_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when ap_ST_fsm_state26 => 
                ap_NS_fsm <= ap_ST_fsm_state27;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state28;
            when ap_ST_fsm_state28 => 
                ap_NS_fsm <= ap_ST_fsm_state29;
            when ap_ST_fsm_state29 => 
                ap_NS_fsm <= ap_ST_fsm_state30;
            when ap_ST_fsm_state30 => 
                ap_NS_fsm <= ap_ST_fsm_state31;
            when ap_ST_fsm_state31 => 
                ap_NS_fsm <= ap_ST_fsm_state32;
            when ap_ST_fsm_state32 => 
                ap_NS_fsm <= ap_ST_fsm_state33;
            when ap_ST_fsm_state33 => 
                ap_NS_fsm <= ap_ST_fsm_state34;
            when ap_ST_fsm_state34 => 
                ap_NS_fsm <= ap_ST_fsm_state35;
            when ap_ST_fsm_state35 => 
                ap_NS_fsm <= ap_ST_fsm_state36;
            when ap_ST_fsm_state36 => 
                ap_NS_fsm <= ap_ST_fsm_state37;
            when ap_ST_fsm_state37 => 
                ap_NS_fsm <= ap_ST_fsm_state38;
            when ap_ST_fsm_state38 => 
                ap_NS_fsm <= ap_ST_fsm_state39;
            when ap_ST_fsm_state39 => 
                ap_NS_fsm <= ap_ST_fsm_state40;
            when ap_ST_fsm_state40 => 
                ap_NS_fsm <= ap_ST_fsm_state41;
            when ap_ST_fsm_state41 => 
                ap_NS_fsm <= ap_ST_fsm_state42;
            when ap_ST_fsm_state42 => 
                ap_NS_fsm <= ap_ST_fsm_state43;
            when ap_ST_fsm_state43 => 
                ap_NS_fsm <= ap_ST_fsm_state44;
            when ap_ST_fsm_state44 => 
                ap_NS_fsm <= ap_ST_fsm_state45;
            when ap_ST_fsm_state45 => 
                ap_NS_fsm <= ap_ST_fsm_state46;
            when ap_ST_fsm_state46 => 
                ap_NS_fsm <= ap_ST_fsm_state47;
            when ap_ST_fsm_state47 => 
                ap_NS_fsm <= ap_ST_fsm_state48;
            when ap_ST_fsm_state48 => 
                ap_NS_fsm <= ap_ST_fsm_state49;
            when ap_ST_fsm_state49 => 
                ap_NS_fsm <= ap_ST_fsm_state50;
            when ap_ST_fsm_state50 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state50) and (icmp_ln135_fu_299_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state51;
                end if;
            when ap_ST_fsm_state51 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state51) and (icmp_ln136_fu_323_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state50;
                else
                    ap_NS_fsm <= ap_ST_fsm_state52;
                end if;
            when ap_ST_fsm_state52 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state52) and (icmp_ln138_fu_360_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state51;
                else
                    ap_NS_fsm <= ap_ST_fsm_state53;
                end if;
            when ap_ST_fsm_state53 => 
                ap_NS_fsm <= ap_ST_fsm_state54;
            when ap_ST_fsm_state54 => 
                ap_NS_fsm <= ap_ST_fsm_state55;
            when ap_ST_fsm_state55 => 
                ap_NS_fsm <= ap_ST_fsm_state56;
            when ap_ST_fsm_state56 => 
                ap_NS_fsm <= ap_ST_fsm_state52;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln108_fu_417_p2 <= std_logic_vector(unsigned(p_Val2_9_reg_632) + unsigned(select_ln108_fu_409_p3));
    add_ln128_fu_271_p2 <= std_logic_vector(unsigned(j_0_0_reg_194) + unsigned(ap_const_lv9_1));
    add_ln135_fu_305_p2 <= std_logic_vector(unsigned(jo_0_0_reg_205) + unsigned(ap_const_lv3_1));
    add_ln136_fu_329_p2 <= std_logic_vector(unsigned(ji_0_0_reg_216) + unsigned(ap_const_lv5_1));
    add_ln137_fu_335_p2 <= std_logic_vector(unsigned(zext_ln136_fu_319_p1) + unsigned(shl_ln_reg_572));
    add_ln138_fu_366_p2 <= std_logic_vector(unsigned(k_0_0_reg_227) + unsigned(ap_const_lv3_1));
    add_ln139_fu_372_p2 <= std_logic_vector(unsigned(shl_ln1_reg_585) + unsigned(zext_ln138_fu_356_p1));
    add_ln700_fu_450_p2 <= std_logic_vector(unsigned(ap_const_lv24_1) + unsigned(p_Result_s_fu_422_p4));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state49 <= ap_CS_fsm(48);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state50 <= ap_CS_fsm(49);
    ap_CS_fsm_state51 <= ap_CS_fsm(50);
    ap_CS_fsm_state52 <= ap_CS_fsm(51);
    ap_CS_fsm_state53 <= ap_CS_fsm(52);
    ap_CS_fsm_state54 <= ap_CS_fsm(53);
    ap_CS_fsm_state55 <= ap_CS_fsm(54);
    ap_CS_fsm_state56 <= ap_CS_fsm(55);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state50, icmp_ln135_fu_299_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state50) and (icmp_ln135_fu_299_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state50, icmp_ln135_fu_299_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state50) and (icmp_ln135_fu_299_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= udiv_ln1148_reg_555;
    grp_fu_238_p3 <= input_0_V_q0(39 downto 39);
    grp_fu_246_p2 <= std_logic_vector(unsigned(ap_const_lv40_0) - unsigned(input_0_V_q0));
    grp_fu_252_p3 <= 
        grp_fu_246_p2 when (grp_fu_238_p3(0) = '1') else 
        input_0_V_q0;

    grp_fu_277_ap_start_assign_proc : process(ap_CS_fsm_state4, icmp_ln128_fu_260_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_260_p2 = ap_const_lv1_1))) then 
            grp_fu_277_ap_start <= ap_const_logic_1;
        else 
            grp_fu_277_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln128_fu_260_p2 <= "1" when (j_0_0_reg_194 = ap_const_lv9_180) else "0";
    icmp_ln135_fu_299_p2 <= "1" when (jo_0_0_reg_205 = ap_const_lv3_6) else "0";
    icmp_ln136_fu_323_p2 <= "1" when (ji_0_0_reg_216 = ap_const_lv5_10) else "0";
    icmp_ln138_fu_360_p2 <= "1" when (k_0_0_reg_227 = ap_const_lv3_4) else "0";
    icmp_ln1494_26_fu_404_p2 <= "1" when (signed(p_Val2_9_reg_632) > signed(ap_const_lv40_0)) else "0";
    icmp_ln1494_fu_283_p2 <= "1" when (signed(p_Val2_12_reg_544) > signed(max_val_V_0_0_reg_184)) else "0";
    icmp_ln851_fu_444_p2 <= "1" when (trunc_ln851_fu_440_p1 = ap_const_lv16_0) else "0";
    icmp_ln887_fu_482_p2 <= "1" when (signed(select_ln850_reg_638) < signed(ap_const_lv24_FFFF80)) else "0";
    icmp_ln895_fu_487_p2 <= "1" when (signed(tmp_76_reg_644) > signed(ap_const_lv17_0)) else "0";

    input_0_V_address0_assign_proc : process(ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state52, zext_ln129_fu_266_p1, zext_ln139_fu_377_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state52)) then 
            input_0_V_address0 <= zext_ln139_fu_377_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            input_0_V_address0 <= zext_ln129_fu_266_p1(9 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            input_0_V_address0 <= ap_const_lv64_0(9 - 1 downto 0);
        else 
            input_0_V_address0 <= "XXXXXXXXX";
        end if; 
    end process;


    input_0_V_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4, ap_CS_fsm_state52)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state52) or (ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            input_0_V_ce0 <= ap_const_logic_1;
        else 
            input_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    mul_ln1118_fu_389_p0 <= zext_ln135_reg_559(40 - 1 downto 0);
    mul_ln1118_fu_389_p1 <= input_0_V_load_reg_627;
    mul_ln1118_fu_389_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed('0' &mul_ln1118_fu_389_p0) * signed(mul_ln1118_fu_389_p1))), 56));
    or_ln887_fu_503_p2 <= (icmp_ln895_fu_487_p2 or icmp_ln887_fu_482_p2);
    output_states_0_0_V_address0 <= output_states_0_0_s_reg_590;

    output_states_0_0_V_ce0_assign_proc : process(ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            output_states_0_0_V_ce0 <= ap_const_logic_1;
        else 
            output_states_0_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_0_0_V_d0 <= select_ln887_1_fu_509_p3;

    output_states_0_0_V_we0_assign_proc : process(trunc_ln180_reg_623, ap_CS_fsm_state56)
    begin
        if (((trunc_ln180_reg_623 = ap_const_lv2_0) and (ap_const_logic_1 = ap_CS_fsm_state56))) then 
            output_states_0_0_V_we0 <= ap_const_logic_1;
        else 
            output_states_0_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_1_0_V_address0 <= output_states_1_0_s_reg_595;

    output_states_1_0_V_ce0_assign_proc : process(ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            output_states_1_0_V_ce0 <= ap_const_logic_1;
        else 
            output_states_1_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_1_0_V_d0 <= select_ln887_1_fu_509_p3;

    output_states_1_0_V_we0_assign_proc : process(trunc_ln180_reg_623, ap_CS_fsm_state56)
    begin
        if (((trunc_ln180_reg_623 = ap_const_lv2_1) and (ap_const_logic_1 = ap_CS_fsm_state56))) then 
            output_states_1_0_V_we0 <= ap_const_logic_1;
        else 
            output_states_1_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_2_0_V_address0 <= output_states_2_0_s_reg_600;

    output_states_2_0_V_ce0_assign_proc : process(ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            output_states_2_0_V_ce0 <= ap_const_logic_1;
        else 
            output_states_2_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_2_0_V_d0 <= select_ln887_1_fu_509_p3;

    output_states_2_0_V_we0_assign_proc : process(trunc_ln180_reg_623, ap_CS_fsm_state56)
    begin
        if (((trunc_ln180_reg_623 = ap_const_lv2_2) and (ap_const_logic_1 = ap_CS_fsm_state56))) then 
            output_states_2_0_V_we0 <= ap_const_logic_1;
        else 
            output_states_2_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_3_0_V_address0 <= output_states_3_0_s_reg_605;

    output_states_3_0_V_ce0_assign_proc : process(ap_CS_fsm_state56)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state56)) then 
            output_states_3_0_V_ce0 <= ap_const_logic_1;
        else 
            output_states_3_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_states_3_0_V_d0 <= select_ln887_1_fu_509_p3;

    output_states_3_0_V_we0_assign_proc : process(trunc_ln180_reg_623, ap_CS_fsm_state56)
    begin
        if (((trunc_ln180_reg_623 = ap_const_lv2_3) and (ap_const_logic_1 = ap_CS_fsm_state56))) then 
            output_states_3_0_V_we0 <= ap_const_logic_1;
        else 
            output_states_3_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_Result_s_fu_422_p4 <= add_ln108_fu_417_p2(39 downto 16);
    p_Val2_13_fu_288_p3 <= 
        p_Val2_12_reg_544 when (icmp_ln1494_fu_283_p2(0) = '1') else 
        max_val_V_0_0_reg_184;
    select_ln108_fu_409_p3 <= 
        ap_const_lv40_8000 when (icmp_ln1494_26_fu_404_p2(0) = '1') else 
        ap_const_lv40_FFFFFF8000;
    select_ln850_fu_464_p3 <= 
        select_ln851_fu_456_p3 when (tmp_75_fu_432_p3(0) = '1') else 
        p_Result_s_fu_422_p4;
    select_ln851_fu_456_p3 <= 
        p_Result_s_fu_422_p4 when (icmp_ln851_fu_444_p2(0) = '1') else 
        add_ln700_fu_450_p2;
    select_ln887_1_fu_509_p3 <= 
        select_ln887_fu_495_p3 when (or_ln887_fu_503_p2(0) = '1') else 
        trunc_ln140_fu_492_p1;
    select_ln887_fu_495_p3 <= 
        ap_const_lv8_80 when (icmp_ln887_fu_482_p2(0) = '1') else 
        ap_const_lv8_7F;
    shl_ln1_fu_340_p3 <= (add_ln137_fu_335_p2 & ap_const_lv2_0);
    shl_ln_fu_311_p3 <= (jo_0_0_reg_205 & ap_const_lv4_0);
    tmp_75_fu_432_p3 <= add_ln108_fu_417_p2(39 downto 39);
    trunc_ln140_fu_492_p1 <= select_ln850_reg_638(8 - 1 downto 0);
    trunc_ln180_fu_382_p1 <= k_0_0_reg_227(2 - 1 downto 0);
    trunc_ln851_fu_440_p1 <= add_ln108_fu_417_p2(16 - 1 downto 0);
    zext_ln129_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_0_reg_194),64));
    zext_ln135_fu_295_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_277_p2),56));
    zext_ln136_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ji_0_0_reg_216),7));
    zext_ln138_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_0_0_reg_227),9));
    zext_ln139_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln139_fu_372_p2),64));
    zext_ln141_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln137_fu_335_p2),64));
end behav;
