directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>:mux#16 RESOURCE_NAME RESHAPE_2D_TO_3D_LOOP_3:mux#33:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3:mux#33 RESOURCE_NAME RESHAPE_2D_TO_3D_LOOP_3:mux#33:rg
directive set /dut/dut:core/dut:core:conc/operator+=<40,24,true,AC_TRN,AC_WRAP,8,true>#1:mux#16 RESOURCE_NAME RESHAPE_2D_TO_3D_LOOP_3#1:mux#33:rg
directive set /dut/dut:core/dut:core:conc/RESHAPE_2D_TO_3D_LOOP_3#1:mux#33 RESOURCE_NAME RESHAPE_2D_TO_3D_LOOP_3#1:mux#33:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:mux#22 RESOURCE_NAME RMS_NORM_LOOP_1#2:mux:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:mux RESOURCE_NAME RMS_NORM_LOOP_1#2:mux:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_3:acc#4 RESOURCE_NAME CACHE_UPDATE_LOOP_2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_4#2:acc#2 RESOURCE_NAME CACHE_UPDATE_LOOP_2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3:acc#1 RESOURCE_NAME CACHE_UPDATE_LOOP_2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_2:acc#1 RESOURCE_NAME CACHE_UPDATE_LOOP_2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#7 RESOURCE_NAME CACHE_UPDATE_LOOP_2:acc#1:rg
directive set /dut/dut:core/dut:core:conc/CACHE_UPDATE_LOOP_2#1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3#1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_1:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#15:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_3#2:acc#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#15:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:acc#15 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:acc#15:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:acc#1 RESOURCE_NAME RMS_NORM_LOOP_1#1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:acc#1 RESOURCE_NAME RMS_NORM_LOOP_1#1:acc#1:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:acc#4 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_4#1:GEMM_3D_FLOAT_LOOP_4#1:acc#4:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#3 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#3:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#2:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#1:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#3:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#1:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#1:RMS_NORM_LOOP_1#1:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt:for:guess_inv:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_3:quantized_value:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/APPLY_ROTARY_POS_EMB_LOOP_6:mul#2 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:GEMM_3D_FLOAT_LOOP_4:mul#1 RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/SOFTMAX_LOOP_4:sqr RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_1#2:RMS_NORM_LOOP_1#2:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt#1:for:guess_inv:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/QUANTIZE_ACTIVATION_LOOP_3#1:quantized_value:mul RESOURCE_NAME APPLY_ROTARY_POS_EMB_LOOP_6:mul#2:rg
directive set /dut/dut:core/dut:core:conc/TRANSPOSE_LAST_TWO_DIMS_LOOP_3:acc#10 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#5:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_3:acc#5 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#5:rg
directive set /dut/dut:core/dut:core:conc/GEMM_3D_FLOAT_LOOP_4:acc#11 RESOURCE_NAME GEMM_3D_FLOAT_LOOP_3:acc#5:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:acc RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#2:rg
directive set /dut/dut:core/dut:core:conc/compute_sqrt:for:acc#2 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#2:rg
directive set /dut/dut:core/dut:core:conc/LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#2 RESOURCE_NAME LINEAR_FORWARD_NO_MUL_LOOP_2#1:acc#2:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2#2:mul RESOURCE_NAME RMS_NORM_LOOP_2#2:mul:rg
directive set /dut/dut:core/dut:core:conc/RMS_NORM_LOOP_2:mul RESOURCE_NAME RMS_NORM_LOOP_2#2:mul:rg
